[2024-09-16 02:49:05,053][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-09-16 02:49:08,179][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 168615876813.0, 'CPU': 256.0, 'GPU': 1.0, 'accelerator_type:G': 1.0, 'node:115.145.172.224': 1.0, 'object_store_memory': 76549661491.0, 'node:__internal_head__': 1.0}
[2024-09-16 02:49:08,179][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-09-16 02:49:08,179][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 64, 'num_gpus': 0.1}
[2024-09-16 02:49:08,194][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 4 actors
[2024-09-16 02:49:08,194][flwr][INFO] - [INIT]
[2024-09-16 02:49:08,194][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-16 02:49:12,528][flwr][INFO] - Received initial parameters from one random client
[2024-09-16 02:49:12,528][flwr][INFO] - Evaluating initial global parameters
[2024-09-16 02:49:19,045][flwr][INFO] - initial parameters (loss, other metrics): 221.9475461244583, {'accuracy': 0.22011107863197896}
[2024-09-16 02:49:19,045][flwr][INFO] - 
[2024-09-16 02:49:19,045][flwr][INFO] - [ROUND 1]
[2024-09-16 02:49:19,046][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:49:25,596][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:49:25,802][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-09-16 02:49:31,206][flwr][INFO] - fit progress: (1, 222.40712189674377, {'accuracy': 0.15580239695995324}, 12.160164144821465)
[2024-09-16 02:49:31,206][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:49:31,647][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:49:31,648][flwr][INFO] - 
[2024-09-16 02:49:31,648][flwr][INFO] - [ROUND 2]
[2024-09-16 02:49:31,648][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:49:33,461][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:49:38,293][flwr][INFO] - fit progress: (2, 225.8277063369751, {'accuracy': 0.09090909090909091}, 19.247854771092534)
[2024-09-16 02:49:38,294][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:49:38,895][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:49:38,896][flwr][INFO] - 
[2024-09-16 02:49:38,896][flwr][INFO] - [ROUND 3]
[2024-09-16 02:49:38,896][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:49:41,480][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:49:46,196][flwr][INFO] - fit progress: (3, 226.9033453464508, {'accuracy': 0.09646302250803858}, 27.15085417078808)
[2024-09-16 02:49:46,197][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:49:46,586][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:49:46,587][flwr][INFO] - 
[2024-09-16 02:49:46,587][flwr][INFO] - [ROUND 4]
[2024-09-16 02:49:46,587][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:49:49,751][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:49:54,743][flwr][INFO] - fit progress: (4, 219.2742246389389, {'accuracy': 0.1657410114001754}, 35.69719398813322)
[2024-09-16 02:49:54,743][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:49:55,077][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:49:55,078][flwr][INFO] - 
[2024-09-16 02:49:55,078][flwr][INFO] - [ROUND 5]
[2024-09-16 02:49:55,078][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:49:58,201][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:04,673][flwr][INFO] - fit progress: (5, 225.71227169036865, {'accuracy': 0.1824028061970184}, 45.62726671714336)
[2024-09-16 02:50:04,674][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:04,992][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:50:04,992][flwr][INFO] - 
[2024-09-16 02:50:04,992][flwr][INFO] - [ROUND 6]
[2024-09-16 02:50:04,992][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:50:08,567][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:15,163][flwr][INFO] - fit progress: (6, 212.69008207321167, {'accuracy': 0.24904998538439052}, 56.11765234498307)
[2024-09-16 02:50:15,163][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:15,237][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:50:15,237][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:50:15,448][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-16 02:50:15,449][flwr][INFO] - 
[2024-09-16 02:50:15,449][flwr][INFO] - [ROUND 7]
[2024-09-16 02:50:15,449][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:50:17,352][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:23,309][flwr][INFO] - fit progress: (7, 210.99747705459595, {'accuracy': 0.2584039754457761}, 64.26366478810087)
[2024-09-16 02:50:23,310][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:23,643][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:50:23,643][flwr][INFO] - 
[2024-09-16 02:50:23,643][flwr][INFO] - [ROUND 8]
[2024-09-16 02:50:23,643][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:50:27,587][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:33,603][flwr][INFO] - fit progress: (8, 217.75655806064606, {'accuracy': 0.19847997661502484}, 74.55722181592137)
[2024-09-16 02:50:33,603][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:33,998][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:50:33,999][flwr][INFO] - 
[2024-09-16 02:50:33,999][flwr][INFO] - [ROUND 9]
[2024-09-16 02:50:33,999][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:50:36,548][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:41,789][flwr][INFO] - fit progress: (9, 211.53920936584473, {'accuracy': 0.278865828705057}, 82.74400079576299)
[2024-09-16 02:50:41,790][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:42,228][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:50:42,229][flwr][INFO] - 
[2024-09-16 02:50:42,229][flwr][INFO] - [ROUND 10]
[2024-09-16 02:50:42,229][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:50:43,708][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:48,578][flwr][INFO] - fit progress: (10, 212.4496339559555, {'accuracy': 0.19497223034200525}, 89.53280046582222)
[2024-09-16 02:50:48,579][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:49,109][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:50:49,110][flwr][INFO] - 
[2024-09-16 02:50:49,110][flwr][INFO] - [ROUND 11]
[2024-09-16 02:50:49,110][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:50:52,280][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:50:57,911][flwr][INFO] - fit progress: (11, 207.85789918899536, {'accuracy': 0.2958199356913183}, 98.8659296920523)
[2024-09-16 02:50:57,912][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:50:58,315][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:50:58,315][flwr][INFO] - 
[2024-09-16 02:50:58,315][flwr][INFO] - [ROUND 12]
[2024-09-16 02:50:58,315][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:51:02,328][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:51:07,770][flwr][INFO] - fit progress: (12, 197.9943803548813, {'accuracy': 0.29815843320666474}, 108.7245032559149)
[2024-09-16 02:51:07,770][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:51:08,076][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:51:08,076][flwr][INFO] - 
[2024-09-16 02:51:08,076][flwr][INFO] - [ROUND 13]
[2024-09-16 02:51:08,076][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:51:14,316][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:51:20,395][flwr][INFO] - fit progress: (13, 200.7959372997284, {'accuracy': 0.29026600409237063}, 121.34945529699326)
[2024-09-16 02:51:20,395][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:51:20,703][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:51:20,703][flwr][INFO] - 
[2024-09-16 02:51:20,703][flwr][INFO] - [ROUND 14]
[2024-09-16 02:51:20,703][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:51:27,236][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:51:32,958][flwr][INFO] - fit progress: (14, 196.58305251598358, {'accuracy': 0.3218357205495469}, 133.91219063010067)
[2024-09-16 02:51:32,958][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:51:33,315][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:51:33,315][flwr][INFO] - 
[2024-09-16 02:51:33,315][flwr][INFO] - [ROUND 15]
[2024-09-16 02:51:33,315][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:51:36,683][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:51:42,164][flwr][INFO] - fit progress: (15, 197.37777757644653, {'accuracy': 0.3183279742765273}, 143.11819014698267)
[2024-09-16 02:51:42,164][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:51:42,536][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:51:42,536][flwr][INFO] - 
[2024-09-16 02:51:42,536][flwr][INFO] - [ROUND 16]
[2024-09-16 02:51:42,536][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:51:48,361][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:51:53,458][flwr][INFO] - fit progress: (16, 184.78413355350494, {'accuracy': 0.32066647179187374}, 154.41266845399514)
[2024-09-16 02:51:53,459][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:51:53,772][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:51:53,772][flwr][INFO] - 
[2024-09-16 02:51:53,772][flwr][INFO] - [ROUND 17]
[2024-09-16 02:51:53,772][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:51:58,287][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:52:03,231][flwr][INFO] - fit progress: (17, 178.26583349704742, {'accuracy': 0.43583747442268345}, 164.1857636431232)
[2024-09-16 02:52:03,231][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:52:03,630][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:52:03,630][flwr][INFO] - 
[2024-09-16 02:52:03,631][flwr][INFO] - [ROUND 18]
[2024-09-16 02:52:03,631][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:52:06,821][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:52:12,069][flwr][INFO] - fit progress: (18, 184.12346136569977, {'accuracy': 0.29961999415375623}, 173.0238357419148)
[2024-09-16 02:52:12,070][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:52:12,598][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:52:12,598][flwr][INFO] - 
[2024-09-16 02:52:12,598][flwr][INFO] - [ROUND 19]
[2024-09-16 02:52:12,598][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:52:14,272][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:52:19,537][flwr][INFO] - fit progress: (19, 180.85946345329285, {'accuracy': 0.4688687518269512}, 180.49173245811835)
[2024-09-16 02:52:19,538][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:52:19,617][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:52:19,617][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:52:19,840][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-16 02:52:19,841][flwr][INFO] - 
[2024-09-16 02:52:19,841][flwr][INFO] - [ROUND 20]
[2024-09-16 02:52:19,841][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:52:24,021][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:52:29,129][flwr][INFO] - fit progress: (20, 186.5087388753891, {'accuracy': 0.3054662379421222}, 190.08355459198356)
[2024-09-16 02:52:29,130][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:52:29,425][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:52:29,426][flwr][INFO] - 
[2024-09-16 02:52:29,426][flwr][INFO] - [ROUND 21]
[2024-09-16 02:52:29,426][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:52:35,156][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:52:40,263][flwr][INFO] - fit progress: (21, 175.166854262352, {'accuracy': 0.4016369482607425}, 201.2179489149712)
[2024-09-16 02:52:40,264][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:52:40,727][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:52:40,727][flwr][INFO] - 
[2024-09-16 02:52:40,728][flwr][INFO] - [ROUND 22]
[2024-09-16 02:52:40,728][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:52:40,859][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:52:40,859][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014830, ip=115.145.172.224, actor_id=f6b6c3c02e93878d3866d8d001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fefbc395750>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:52:43,608][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:52:49,064][flwr][INFO] - fit progress: (22, 162.01871716976166, {'accuracy': 0.4858228588132125}, 210.01856835978106)
[2024-09-16 02:52:49,065][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:52:49,436][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:52:49,436][flwr][INFO] - 
[2024-09-16 02:52:49,436][flwr][INFO] - [ROUND 23]
[2024-09-16 02:52:49,436][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:52:56,832][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:01,733][flwr][INFO] - fit progress: (23, 165.10507678985596, {'accuracy': 0.518561824028062}, 222.68777551874518)
[2024-09-16 02:53:01,733][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:02,064][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:53:02,064][flwr][INFO] - 
[2024-09-16 02:53:02,064][flwr][INFO] - [ROUND 24]
[2024-09-16 02:53:02,064][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:02,191][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:53:02,191][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:53:04,727][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:53:09,634][flwr][INFO] - fit progress: (24, 159.22582721710205, {'accuracy': 0.4744226834258989}, 230.58891929406673)
[2024-09-16 02:53:09,635][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:09,962][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:53:09,962][flwr][INFO] - 
[2024-09-16 02:53:09,962][flwr][INFO] - [ROUND 25]
[2024-09-16 02:53:09,962][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:11,816][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:17,812][flwr][INFO] - fit progress: (25, 162.30230152606964, {'accuracy': 0.4425606547793043}, 238.76617994485423)
[2024-09-16 02:53:17,812][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:18,306][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:53:18,306][flwr][INFO] - 
[2024-09-16 02:53:18,306][flwr][INFO] - [ROUND 26]
[2024-09-16 02:53:18,306][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:21,624][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:26,505][flwr][INFO] - fit progress: (26, 155.5759711265564, {'accuracy': 0.6170710318620286}, 247.45948380604386)
[2024-09-16 02:53:26,505][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:26,625][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:53:26,625][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:53:26,805][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-16 02:53:26,805][flwr][INFO] - 
[2024-09-16 02:53:26,805][flwr][INFO] - [ROUND 27]
[2024-09-16 02:53:26,805][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:31,447][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:36,333][flwr][INFO] - fit progress: (27, 158.5099893808365, {'accuracy': 0.6030400467699503}, 257.2872030697763)
[2024-09-16 02:53:36,333][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:36,673][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:53:36,673][flwr][INFO] - 
[2024-09-16 02:53:36,674][flwr][INFO] - [ROUND 28]
[2024-09-16 02:53:36,674][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:38,127][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:43,408][flwr][INFO] - fit progress: (28, 163.218106508255, {'accuracy': 0.5290850628471208}, 264.3629210740328)
[2024-09-16 02:53:43,409][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:43,909][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:53:43,909][flwr][INFO] - 
[2024-09-16 02:53:43,909][flwr][INFO] - [ROUND 29]
[2024-09-16 02:53:43,909][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:46,522][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:51,387][flwr][INFO] - fit progress: (29, 161.19386267662048, {'accuracy': 0.6141479099678456}, 272.3420937489718)
[2024-09-16 02:53:51,388][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:53:51,793][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:53:51,794][flwr][INFO] - 
[2024-09-16 02:53:51,794][flwr][INFO] - [ROUND 30]
[2024-09-16 02:53:51,794][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:53:54,838][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:53:59,739][flwr][INFO] - fit progress: (30, 147.68206596374512, {'accuracy': 0.5565624086524408}, 280.6931669730693)
[2024-09-16 02:53:59,739][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:00,185][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:00,185][flwr][INFO] - 
[2024-09-16 02:54:00,185][flwr][INFO] - [ROUND 31]
[2024-09-16 02:54:00,185][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:54:02,677][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:54:07,897][flwr][INFO] - fit progress: (31, 156.5080590248108, {'accuracy': 0.42443729903536975}, 288.8517203279771)
[2024-09-16 02:54:07,898][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:08,234][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:08,234][flwr][INFO] - 
[2024-09-16 02:54:08,234][flwr][INFO] - [ROUND 32]
[2024-09-16 02:54:08,235][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:54:14,580][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:54:19,780][flwr][INFO] - fit progress: (32, 155.5536868572235, {'accuracy': 0.49956153171587253}, 300.7349364371039)
[2024-09-16 02:54:19,781][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:20,235][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:20,235][flwr][INFO] - 
[2024-09-16 02:54:20,235][flwr][INFO] - [ROUND 33]
[2024-09-16 02:54:20,235][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:54:22,599][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:54:27,817][flwr][INFO] - fit progress: (33, 148.333890914917, {'accuracy': 0.6045016077170418}, 308.77157686976716)
[2024-09-16 02:54:27,817][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:28,126][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:28,127][flwr][INFO] - 
[2024-09-16 02:54:28,127][flwr][INFO] - [ROUND 34]
[2024-09-16 02:54:28,127][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:54:33,627][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:54:38,546][flwr][INFO] - fit progress: (34, 141.71960389614105, {'accuracy': 0.5363928675825782}, 319.50096405111253)
[2024-09-16 02:54:38,547][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:39,049][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:39,049][flwr][INFO] - 
[2024-09-16 02:54:39,049][flwr][INFO] - [ROUND 35]
[2024-09-16 02:54:39,049][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:54:39,153][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:54:39,153][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:54:43,199][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:54:48,323][flwr][INFO] - fit progress: (35, 147.51415634155273, {'accuracy': 0.5428237357497807}, 329.277355351951)
[2024-09-16 02:54:48,323][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:48,704][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:48,705][flwr][INFO] - 
[2024-09-16 02:54:48,705][flwr][INFO] - [ROUND 36]
[2024-09-16 02:54:48,705][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:54:51,226][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:54:56,329][flwr][INFO] - fit progress: (36, 156.3957018852234, {'accuracy': 0.43642209880152}, 337.2840844038874)
[2024-09-16 02:54:56,330][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:54:56,697][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:54:56,698][flwr][INFO] - 
[2024-09-16 02:54:56,698][flwr][INFO] - [ROUND 37]
[2024-09-16 02:54:56,698][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:01,726][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:55:06,667][flwr][INFO] - fit progress: (37, 155.1593643426895, {'accuracy': 0.4840689856767027}, 347.62169868079945)
[2024-09-16 02:55:06,667][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:07,028][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:07,028][flwr][INFO] - 
[2024-09-16 02:55:07,028][flwr][INFO] - [ROUND 38]
[2024-09-16 02:55:07,028][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:10,142][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:55:15,231][flwr][INFO] - fit progress: (38, 138.9142925143242, {'accuracy': 0.47500730780473543}, 356.18542082887143)
[2024-09-16 02:55:15,231][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:15,798][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:15,798][flwr][INFO] - 
[2024-09-16 02:55:15,798][flwr][INFO] - [ROUND 39]
[2024-09-16 02:55:15,798][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:18,701][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:55:23,652][flwr][INFO] - fit progress: (39, 140.5434558391571, {'accuracy': 0.586085939783689}, 364.6065545519814)
[2024-09-16 02:55:23,652][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:23,988][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:23,988][flwr][INFO] - 
[2024-09-16 02:55:23,988][flwr][INFO] - [ROUND 40]
[2024-09-16 02:55:23,988][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:25,585][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:55:30,721][flwr][INFO] - fit progress: (40, 136.8436460494995, {'accuracy': 0.6024554223911137}, 371.67606785008684)
[2024-09-16 02:55:30,722][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:31,054][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:31,055][flwr][INFO] - 
[2024-09-16 02:55:31,055][flwr][INFO] - [ROUND 41]
[2024-09-16 02:55:31,055][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:35,788][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:55:40,789][flwr][INFO] - fit progress: (41, 128.22308945655823, {'accuracy': 0.6395790704472376}, 381.7439750437625)
[2024-09-16 02:55:40,790][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:41,339][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:41,339][flwr][INFO] - 
[2024-09-16 02:55:41,339][flwr][INFO] - [ROUND 42]
[2024-09-16 02:55:41,339][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:44,294][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:55:49,428][flwr][INFO] - fit progress: (42, 130.4853333234787, {'accuracy': 0.5618240280619702}, 390.3825643900782)
[2024-09-16 02:55:49,428][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:49,791][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:49,791][flwr][INFO] - 
[2024-09-16 02:55:49,791][flwr][INFO] - [ROUND 43]
[2024-09-16 02:55:49,791][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:49,898][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:55:49,898][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:55:51,588][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:55:56,386][flwr][INFO] - fit progress: (43, 145.06326830387115, {'accuracy': 0.38672902660040925}, 397.34092401200905)
[2024-09-16 02:55:56,387][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:55:56,808][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:55:56,808][flwr][INFO] - 
[2024-09-16 02:55:56,809][flwr][INFO] - [ROUND 44]
[2024-09-16 02:55:56,809][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:55:58,959][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:56:04,011][flwr][INFO] - fit progress: (44, 140.64496791362762, {'accuracy': 0.4425606547793043}, 404.9655583780259)
[2024-09-16 02:56:04,011][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:56:04,384][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:56:04,385][flwr][INFO] - 
[2024-09-16 02:56:04,385][flwr][INFO] - [ROUND 45]
[2024-09-16 02:56:04,385][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:56:04,493][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:56:04,493][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:56:06,616][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:56:11,525][flwr][INFO] - fit progress: (45, 130.67094790935516, {'accuracy': 0.6641332943583748}, 412.4795056087896)
[2024-09-16 02:56:11,525][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:56:11,899][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:56:11,899][flwr][INFO] - 
[2024-09-16 02:56:11,899][flwr][INFO] - [ROUND 46]
[2024-09-16 02:56:11,900][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:56:16,525][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:56:22,931][flwr][INFO] - fit progress: (46, 129.7549602985382, {'accuracy': 0.6103478515054078}, 423.88594619883224)
[2024-09-16 02:56:22,932][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:56:23,310][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:56:23,311][flwr][INFO] - 
[2024-09-16 02:56:23,311][flwr][INFO] - [ROUND 47]
[2024-09-16 02:56:23,311][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:56:27,831][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:56:32,758][flwr][INFO] - fit progress: (47, 120.85648685693741, {'accuracy': 0.6255480853551593}, 433.71239760611206)
[2024-09-16 02:56:32,758][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:56:33,092][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:56:33,092][flwr][INFO] - 
[2024-09-16 02:56:33,092][flwr][INFO] - [ROUND 48]
[2024-09-16 02:56:33,093][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:56:36,360][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:56:41,457][flwr][INFO] - fit progress: (48, 123.90543097257614, {'accuracy': 0.6305173925752704}, 442.41150820301846)
[2024-09-16 02:56:41,457][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:56:41,859][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:56:41,859][flwr][INFO] - 
[2024-09-16 02:56:41,859][flwr][INFO] - [ROUND 49]
[2024-09-16 02:56:41,860][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:56:45,349][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:56:50,300][flwr][INFO] - fit progress: (49, 131.517172396183, {'accuracy': 0.49663840982168955}, 451.2545463410206)
[2024-09-16 02:56:50,300][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:56:50,725][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:56:50,726][flwr][INFO] - 
[2024-09-16 02:56:50,726][flwr][INFO] - [ROUND 50]
[2024-09-16 02:56:50,726][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:56:55,007][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:00,108][flwr][INFO] - fit progress: (50, 125.22823405265808, {'accuracy': 0.5451622332651271}, 461.0628292998299)
[2024-09-16 02:57:00,108][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:00,452][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:00,452][flwr][INFO] - 
[2024-09-16 02:57:00,452][flwr][INFO] - [ROUND 51]
[2024-09-16 02:57:00,452][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:04,468][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:09,327][flwr][INFO] - fit progress: (51, 127.52915245294571, {'accuracy': 0.5176848874598071}, 470.28141832817346)
[2024-09-16 02:57:09,327][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:09,717][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:09,718][flwr][INFO] - 
[2024-09-16 02:57:09,718][flwr][INFO] - [ROUND 52]
[2024-09-16 02:57:09,718][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:13,172][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:18,260][flwr][INFO] - fit progress: (52, 117.87029469013214, {'accuracy': 0.628178895059924}, 479.214387179818)
[2024-09-16 02:57:18,260][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:18,534][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:18,534][flwr][INFO] - 
[2024-09-16 02:57:18,534][flwr][INFO] - [ROUND 53]
[2024-09-16 02:57:18,534][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:20,073][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:25,210][flwr][INFO] - fit progress: (53, 116.6356161236763, {'accuracy': 0.7024261911721719}, 486.1645105709322)
[2024-09-16 02:57:25,210][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:25,614][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:25,614][flwr][INFO] - 
[2024-09-16 02:57:25,614][flwr][INFO] - [ROUND 54]
[2024-09-16 02:57:25,614][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:27,829][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:32,683][flwr][INFO] - fit progress: (54, 126.7243824005127, {'accuracy': 0.5378544285296697}, 493.63798647373915)
[2024-09-16 02:57:32,684][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:33,084][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:33,084][flwr][INFO] - 
[2024-09-16 02:57:33,084][flwr][INFO] - [ROUND 55]
[2024-09-16 02:57:33,084][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:37,394][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:42,434][flwr][INFO] - fit progress: (55, 117.54354667663574, {'accuracy': 0.715287927506577}, 503.3887776341289)
[2024-09-16 02:57:42,434][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:42,725][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:42,726][flwr][INFO] - 
[2024-09-16 02:57:42,726][flwr][INFO] - [ROUND 56]
[2024-09-16 02:57:42,726][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:46,794][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:57:52,025][flwr][INFO] - fit progress: (56, 109.19422489404678, {'accuracy': 0.6384098216895645}, 512.9792775809765)
[2024-09-16 02:57:52,025][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:57:52,420][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:57:52,421][flwr][INFO] - 
[2024-09-16 02:57:52,421][flwr][INFO] - [ROUND 57]
[2024-09-16 02:57:52,421][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:57:57,372][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:58:02,212][flwr][INFO] - fit progress: (57, 110.72377771139145, {'accuracy': 0.6591639871382636}, 523.1661630119197)
[2024-09-16 02:58:02,212][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:02,560][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:02,560][flwr][INFO] - 
[2024-09-16 02:58:02,560][flwr][INFO] - [ROUND 58]
[2024-09-16 02:58:02,560][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:58:03,986][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:58:09,146][flwr][INFO] - fit progress: (58, 123.30316191911697, {'accuracy': 0.5641625255773166}, 530.1002193908207)
[2024-09-16 02:58:09,146][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:09,508][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:09,508][flwr][INFO] - 
[2024-09-16 02:58:09,508][flwr][INFO] - [ROUND 59]
[2024-09-16 02:58:09,508][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:58:12,497][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:58:17,439][flwr][INFO] - fit progress: (59, 110.33936667442322, {'accuracy': 0.7439345220695703}, 538.3935478758067)
[2024-09-16 02:58:17,439][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:17,743][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:17,743][flwr][INFO] - 
[2024-09-16 02:58:17,743][flwr][INFO] - [ROUND 60]
[2024-09-16 02:58:17,743][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:58:17,850][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:58:17,850][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:58:24,279][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:58:29,496][flwr][INFO] - fit progress: (60, 111.92079746723175, {'accuracy': 0.6349020754165449}, 550.450306897983)
[2024-09-16 02:58:29,496][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:29,956][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:29,956][flwr][INFO] - 
[2024-09-16 02:58:29,956][flwr][INFO] - [ROUND 61]
[2024-09-16 02:58:29,956][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:58:35,255][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:58:40,159][flwr][INFO] - fit progress: (61, 109.74626690149307, {'accuracy': 0.6696872259573224}, 561.1139423688874)
[2024-09-16 02:58:40,160][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:40,471][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:40,471][flwr][INFO] - 
[2024-09-16 02:58:40,471][flwr][INFO] - [ROUND 62]
[2024-09-16 02:58:40,471][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:58:43,582][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:58:48,562][flwr][INFO] - fit progress: (62, 108.98256075382233, {'accuracy': 0.6533177433498977}, 569.5164446551353)
[2024-09-16 02:58:48,562][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:49,120][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:49,120][flwr][INFO] - 
[2024-09-16 02:58:49,120][flwr][INFO] - [ROUND 63]
[2024-09-16 02:58:49,120][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:58:49,192][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:58:49,193][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014828, ip=115.145.172.224, actor_id=febd2ec03062241ee3bfced501000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fdd047857b0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:58:51,945][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 02:58:57,041][flwr][INFO] - fit progress: (63, 107.0101757645607, {'accuracy': 0.7278573516515638}, 577.9955646158196)
[2024-09-16 02:58:57,041][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:58:57,313][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:58:57,314][flwr][INFO] - 
[2024-09-16 02:58:57,314][flwr][INFO] - [ROUND 64]
[2024-09-16 02:58:57,314][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:03,098][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:08,106][flwr][INFO] - fit progress: (64, 100.3701508641243, {'accuracy': 0.7228880444314528}, 589.0611347868107)
[2024-09-16 02:59:08,107][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:08,425][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:59:08,426][flwr][INFO] - 
[2024-09-16 02:59:08,426][flwr][INFO] - [ROUND 65]
[2024-09-16 02:59:08,426][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:11,382][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:16,551][flwr][INFO] - fit progress: (65, 102.9333398938179, {'accuracy': 0.7144109909383222}, 597.5057609057985)
[2024-09-16 02:59:16,552][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:16,928][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:59:16,928][flwr][INFO] - 
[2024-09-16 02:59:16,928][flwr][INFO] - [ROUND 66]
[2024-09-16 02:59:16,928][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:19,050][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:24,001][flwr][INFO] - fit progress: (66, 107.52050477266312, {'accuracy': 0.6881028938906752}, 604.9551519849338)
[2024-09-16 02:59:24,001][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:24,422][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:59:24,422][flwr][INFO] - 
[2024-09-16 02:59:24,422][flwr][INFO] - [ROUND 67]
[2024-09-16 02:59:24,422][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:29,111][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:34,228][flwr][INFO] - fit progress: (67, 105.32294470071793, {'accuracy': 0.7114878690441392}, 615.1825920627452)
[2024-09-16 02:59:34,229][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:34,553][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:59:34,554][flwr][INFO] - 
[2024-09-16 02:59:34,554][flwr][INFO] - [ROUND 68]
[2024-09-16 02:59:34,554][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:36,332][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:41,206][flwr][INFO] - fit progress: (68, 125.37100952863693, {'accuracy': 0.5828705057000877}, 622.1602872209623)
[2024-09-16 02:59:41,206][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:41,281][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 02:59:41,281][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 02:59:41,495][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-16 02:59:41,496][flwr][INFO] - 
[2024-09-16 02:59:41,496][flwr][INFO] - [ROUND 69]
[2024-09-16 02:59:41,496][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:44,962][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:49,998][flwr][INFO] - fit progress: (69, 107.98051297664642, {'accuracy': 0.7386729026600409}, 630.9527766038664)
[2024-09-16 02:59:49,998][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:50,513][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:59:50,513][flwr][INFO] - 
[2024-09-16 02:59:50,513][flwr][INFO] - [ROUND 70]
[2024-09-16 02:59:50,513][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 02:59:54,482][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 02:59:59,373][flwr][INFO] - fit progress: (70, 146.30827462673187, {'accuracy': 0.4688687518269512}, 640.3273696759716)
[2024-09-16 02:59:59,373][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 02:59:59,756][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 02:59:59,756][flwr][INFO] - 
[2024-09-16 02:59:59,756][flwr][INFO] - [ROUND 71]
[2024-09-16 02:59:59,757][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:01,734][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:00:06,864][flwr][INFO] - fit progress: (71, 128.77412295341492, {'accuracy': 0.5612394036831336}, 647.8183050891384)
[2024-09-16 03:00:06,864][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:07,176][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:07,176][flwr][INFO] - 
[2024-09-16 03:00:07,176][flwr][INFO] - [ROUND 72]
[2024-09-16 03:00:07,177][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:13,152][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:00:18,842][flwr][INFO] - fit progress: (72, 101.58014035224915, {'accuracy': 0.7339959076293482}, 659.7964395200834)
[2024-09-16 03:00:18,842][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:19,358][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:19,358][flwr][INFO] - 
[2024-09-16 03:00:19,358][flwr][INFO] - [ROUND 73]
[2024-09-16 03:00:19,358][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:21,374][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:00:26,615][flwr][INFO] - fit progress: (73, 96.21172338724136, {'accuracy': 0.7360420929552762}, 667.5700568761677)
[2024-09-16 03:00:26,616][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:26,944][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:26,944][flwr][INFO] - 
[2024-09-16 03:00:26,944][flwr][INFO] - [ROUND 74]
[2024-09-16 03:00:26,945][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:29,883][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:00:34,762][flwr][INFO] - fit progress: (74, 103.31158798933029, {'accuracy': 0.6933645133002047}, 675.7161885690875)
[2024-09-16 03:00:34,762][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:35,337][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:35,337][flwr][INFO] - 
[2024-09-16 03:00:35,337][flwr][INFO] - [ROUND 75]
[2024-09-16 03:00:35,337][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:37,950][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:00:43,863][flwr][INFO] - fit progress: (75, 104.75244671106339, {'accuracy': 0.6971645717626425}, 684.8171201669611)
[2024-09-16 03:00:43,864][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:44,229][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:44,229][flwr][INFO] - 
[2024-09-16 03:00:44,229][flwr][INFO] - [ROUND 76]
[2024-09-16 03:00:44,230][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:46,245][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:00:51,463][flwr][INFO] - fit progress: (76, 104.27346605062485, {'accuracy': 0.6881028938906752}, 692.4175224890932)
[2024-09-16 03:00:51,463][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:51,920][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:51,920][flwr][INFO] - 
[2024-09-16 03:00:51,920][flwr][INFO] - [ROUND 77]
[2024-09-16 03:00:51,920][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:00:52,175][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 03:00:52,176][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 03:00:53,851][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 03:00:59,168][flwr][INFO] - fit progress: (77, 101.53887623548508, {'accuracy': 0.7664425606547793}, 700.1230073510669)
[2024-09-16 03:00:59,169][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:00:59,602][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:00:59,603][flwr][INFO] - 
[2024-09-16 03:00:59,603][flwr][INFO] - [ROUND 78]
[2024-09-16 03:00:59,603][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:04,398][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:01:09,591][flwr][INFO] - fit progress: (78, 103.17368078231812, {'accuracy': 0.69073370359544}, 710.5451708449982)
[2024-09-16 03:01:09,591][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:01:10,040][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:01:10,041][flwr][INFO] - 
[2024-09-16 03:01:10,041][flwr][INFO] - [ROUND 79]
[2024-09-16 03:01:10,041][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:13,373][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:01:18,436][flwr][INFO] - fit progress: (79, 106.45165646076202, {'accuracy': 0.6495176848874598}, 719.3902518581599)
[2024-09-16 03:01:18,436][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:01:18,763][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:01:18,763][flwr][INFO] - 
[2024-09-16 03:01:18,763][flwr][INFO] - [ROUND 80]
[2024-09-16 03:01:18,763][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:21,880][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:01:27,046][flwr][INFO] - fit progress: (80, 121.40717434883118, {'accuracy': 0.5694241449868459}, 728.0011277068406)
[2024-09-16 03:01:27,047][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:01:27,525][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:01:27,526][flwr][INFO] - 
[2024-09-16 03:01:27,526][flwr][INFO] - [ROUND 81]
[2024-09-16 03:01:27,526][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:30,728][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:01:35,634][flwr][INFO] - fit progress: (81, 117.82858872413635, {'accuracy': 0.6480561239403683}, 736.5883067310788)
[2024-09-16 03:01:35,634][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:01:35,992][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:01:35,993][flwr][INFO] - 
[2024-09-16 03:01:35,993][flwr][INFO] - [ROUND 82]
[2024-09-16 03:01:35,993][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:40,741][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:01:45,653][flwr][INFO] - fit progress: (82, 103.95496916770935, {'accuracy': 0.7185033615901784}, 746.6079689147882)
[2024-09-16 03:01:45,654][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:01:45,947][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:01:45,947][flwr][INFO] - 
[2024-09-16 03:01:45,947][flwr][INFO] - [ROUND 83]
[2024-09-16 03:01:45,947][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:49,978][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:01:55,011][flwr][INFO] - fit progress: (83, 103.82803964614868, {'accuracy': 0.6574101140017539}, 755.9660992641002)
[2024-09-16 03:01:55,012][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:01:55,665][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:01:55,665][flwr][INFO] - 
[2024-09-16 03:01:55,666][flwr][INFO] - [ROUND 84]
[2024-09-16 03:01:55,666][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:01:59,201][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:02:04,057][flwr][INFO] - fit progress: (84, 87.73694461584091, {'accuracy': 0.7290266004092371}, 765.0119839878753)
[2024-09-16 03:02:04,058][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:04,491][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:04,492][flwr][INFO] - 
[2024-09-16 03:02:04,492][flwr][INFO] - [ROUND 85]
[2024-09-16 03:02:04,492][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:02:10,932][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:02:16,539][flwr][INFO] - fit progress: (85, 92.67124742269516, {'accuracy': 0.7760888629055832}, 777.4936902271584)
[2024-09-16 03:02:16,539][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:17,060][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:17,060][flwr][INFO] - 
[2024-09-16 03:02:17,060][flwr][INFO] - [ROUND 86]
[2024-09-16 03:02:17,060][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:02:19,965][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:02:25,592][flwr][INFO] - fit progress: (86, 94.95612770318985, {'accuracy': 0.7538731365097925}, 786.5465086749755)
[2024-09-16 03:02:25,592][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:26,124][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:26,124][flwr][INFO] - 
[2024-09-16 03:02:26,124][flwr][INFO] - [ROUND 87]
[2024-09-16 03:02:26,124][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:02:28,990][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:02:34,060][flwr][INFO] - fit progress: (87, 100.7184567451477, {'accuracy': 0.721134171294943}, 795.0144041609019)
[2024-09-16 03:02:34,060][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:34,449][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:34,449][flwr][INFO] - 
[2024-09-16 03:02:34,449][flwr][INFO] - [ROUND 88]
[2024-09-16 03:02:34,449][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:02:38,856][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:02:43,719][flwr][INFO] - fit progress: (88, 86.9513486623764, {'accuracy': 0.7418883367436422}, 804.6735118008219)
[2024-09-16 03:02:43,719][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:44,069][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:44,069][flwr][INFO] - 
[2024-09-16 03:02:44,069][flwr][INFO] - [ROUND 89]
[2024-09-16 03:02:44,069][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:02:47,779][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:02:52,882][flwr][INFO] - fit progress: (89, 80.47499492764473, {'accuracy': 0.7728734288219818}, 813.8365402268246)
[2024-09-16 03:02:52,882][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:53,215][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:53,215][flwr][INFO] - 
[2024-09-16 03:02:53,215][flwr][INFO] - [ROUND 90]
[2024-09-16 03:02:53,215][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:02:53,315][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 03:02:53,316][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014831, ip=115.145.172.224, actor_id=d87dda5269a3360359ed222e01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f90b0395780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 03:02:54,681][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-16 03:02:59,498][flwr][INFO] - fit progress: (90, 115.00060242414474, {'accuracy': 0.6021631102016954}, 820.4525060718879)
[2024-09-16 03:02:59,498][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:02:59,843][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:02:59,844][flwr][INFO] - 
[2024-09-16 03:02:59,844][flwr][INFO] - [ROUND 91]
[2024-09-16 03:02:59,844][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:03:07,380][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:03:12,467][flwr][INFO] - fit progress: (91, 81.70718479156494, {'accuracy': 0.7784273604209295}, 833.4214144959114)
[2024-09-16 03:03:12,467][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:03:12,926][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:03:12,927][flwr][INFO] - 
[2024-09-16 03:03:12,927][flwr][INFO] - [ROUND 92]
[2024-09-16 03:03:12,927][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:03:15,814][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:03:21,505][flwr][INFO] - fit progress: (92, 103.58090108633041, {'accuracy': 0.6772873428821982}, 842.4595450051129)
[2024-09-16 03:03:21,505][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:03:21,868][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:03:21,868][flwr][INFO] - 
[2024-09-16 03:03:21,868][flwr][INFO] - [ROUND 93]
[2024-09-16 03:03:21,869][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:03:23,615][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:03:28,916][flwr][INFO] - fit progress: (93, 85.42463451623917, {'accuracy': 0.7886582870505701}, 849.8704799371772)
[2024-09-16 03:03:28,916][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:03:29,196][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:03:29,197][flwr][INFO] - 
[2024-09-16 03:03:29,197][flwr][INFO] - [ROUND 94]
[2024-09-16 03:03:29,197][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:03:32,603][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:03:37,607][flwr][INFO] - fit progress: (94, 101.14766174554825, {'accuracy': 0.6430868167202572}, 858.5615897127427)
[2024-09-16 03:03:37,607][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:03:37,927][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:03:37,927][flwr][INFO] - 
[2024-09-16 03:03:37,927][flwr][INFO] - [ROUND 95]
[2024-09-16 03:03:37,927][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:03:39,535][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:03:44,725][flwr][INFO] - fit progress: (95, 93.58360749483109, {'accuracy': 0.7076878105817013}, 865.6801104098558)
[2024-09-16 03:03:44,726][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:03:44,800][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-16 03:03:44,800][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_posoned/fednova_mobilnet/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1014829, ip=115.145.172.224, actor_id=967226362e01df27b4abfb0801000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb28839d780>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-16 03:03:44,998][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-16 03:03:44,998][flwr][INFO] - 
[2024-09-16 03:03:44,998][flwr][INFO] - [ROUND 96]
[2024-09-16 03:03:44,998][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:03:49,002][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:03:53,959][flwr][INFO] - fit progress: (96, 90.3151027560234, {'accuracy': 0.769073370359544}, 874.913709927816)
[2024-09-16 03:03:53,959][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:03:54,349][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:03:54,349][flwr][INFO] - 
[2024-09-16 03:03:54,349][flwr][INFO] - [ROUND 97]
[2024-09-16 03:03:54,349][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:04:00,413][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:04:05,508][flwr][INFO] - fit progress: (97, 99.13649773597717, {'accuracy': 0.6863490207541655}, 886.4625344667584)
[2024-09-16 03:04:05,508][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:04:06,035][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:04:06,035][flwr][INFO] - 
[2024-09-16 03:04:06,035][flwr][INFO] - [ROUND 98]
[2024-09-16 03:04:06,035][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:04:08,612][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:04:15,009][flwr][INFO] - fit progress: (98, 92.16321298480034, {'accuracy': 0.7410114001753874}, 895.9638822460547)
[2024-09-16 03:04:15,010][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:04:15,428][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:04:15,428][flwr][INFO] - 
[2024-09-16 03:04:15,428][flwr][INFO] - [ROUND 99]
[2024-09-16 03:04:15,429][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:04:21,200][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:04:26,322][flwr][INFO] - fit progress: (99, 98.04035091400146, {'accuracy': 0.7234726688102894}, 907.276472541038)
[2024-09-16 03:04:26,322][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:04:26,749][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:04:26,750][flwr][INFO] - 
[2024-09-16 03:04:26,750][flwr][INFO] - [ROUND 100]
[2024-09-16 03:04:26,750][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-16 03:04:29,856][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-16 03:04:36,028][flwr][INFO] - fit progress: (100, 106.13965421915054, {'accuracy': 0.623209587839813}, 916.9827577359974)
[2024-09-16 03:04:36,029][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-16 03:04:36,356][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-16 03:04:36,357][flwr][INFO] - 
[2024-09-16 03:04:36,357][flwr][INFO] - [SUMMARY]
[2024-09-16 03:04:36,357][flwr][INFO] - Run finished 100 round(s) in 917.31s
[2024-09-16 03:04:36,360][flwr][INFO] - 	History (loss, distributed):
[2024-09-16 03:04:36,360][flwr][INFO] - 		round 1: 2.172071492085691
[2024-09-16 03:04:36,360][flwr][INFO] - 		round 2: 3.7394238337874413
[2024-09-16 03:04:36,360][flwr][INFO] - 		round 3: 1.788475432179191
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 4: 2.0317351818084717
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 5: 2.5569558007376534
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 6: 1.4871506690979004
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 7: 2.3279940563699473
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 8: 1.672414207458496
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 9: 1.6853660106658936
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 10: 1.9071306330817086
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 11: 1.497049837696309
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 12: 2.479320764541626
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 13: 2.24758486394529
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 14: 2.59278928861022
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 15: 1.861792190508409
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 16: 1.1673902355391403
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 17: 1.0863582406725203
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 18: 1.8179751421724046
[2024-09-16 03:04:36,361][flwr][INFO] - 		round 19: 2.8558006286621094
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 20: 2.319314420223236
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 21: 1.4307489837918963
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 22: 2.218864470720291
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 23: 1.3600371948310308
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 24: 1.0230097594084564
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 25: 2.2304091691970824
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 26: 1.09461510181427
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 27: 1.2955045189176286
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 28: 1.5359626577255574
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 29: 1.4836938536685447
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 30: 1.7122653722763062
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 31: 1.1430976967016855
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 32: 0.9448336233695348
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 33: 1.2606585443019866
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 34: 1.495863607951573
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 35: 0.6124526212612788
[2024-09-16 03:04:36,362][flwr][INFO] - 		round 36: 2.0123113323660458
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 37: 1.0268867083958217
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 38: 1.5739220885130076
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 39: 1.2437685944817283
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 40: 0.6895687788724899
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 41: 1.1293358522302963
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 42: 0.8887108325958252
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 43: 1.3714683897355024
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 44: 0.6896893531084061
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 45: 1.4863484972401668
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 46: 0.7235236667817638
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 47: 1.1879129535273503
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 48: 1.261106379916159
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 49: 0.69579017162323
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 50: 0.7180100546942817
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 51: 1.7206446240929996
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 52: 1.8095980733633041
[2024-09-16 03:04:36,363][flwr][INFO] - 		round 53: 1.1374306797981262
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 54: 0.9762965637009319
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 55: 1.4793090469696943
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 56: 0.8377955081157906
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 57: 0.9087468238977285
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 58: 0.5953842816145524
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 59: 1.1730986333662463
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 60: 1.1139833883002952
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 61: 0.9992419183254242
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 62: 0.7109835772745071
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 63: 0.4932631687684493
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 64: 0.6540229483084246
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 65: 0.6057405603396429
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 66: 0.6790811602885907
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 67: 0.956501339163099
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 68: 0.7990399599075317
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 69: 1.4336918173609554
[2024-09-16 03:04:36,364][flwr][INFO] - 		round 70: 2.2463064051487227
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 71: 1.8224166929721832
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 72: 1.8531928360462189
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 73: 0.808379665017128
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 74: 1.5351784148731746
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 75: 1.70332454196338
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 76: 1.9316190532408655
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 77: 1.4926246994673604
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 78: 1.4423209641660963
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 79: 0.2209437812368075
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 80: 0.6720108778580375
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 81: 1.5453394752437786
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 82: 2.6520683765411377
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 83: 0.8044956803321839
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 84: 0.7081207674700063
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 85: 0.6416193232816808
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 86: 0.8883433813850085
[2024-09-16 03:04:36,365][flwr][INFO] - 		round 87: 0.8669685856862501
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 88: 0.23237356882203708
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 89: 0.3160924380645156
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 90: 0.48671468923676686
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 91: 0.8831061178178929
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 92: 1.211938391129176
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 93: 0.5740930267742702
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 94: 0.5638471277984413
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 95: 0.5481218695640564
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 96: 0.6646849903567084
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 97: 0.4039863306900551
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 98: 0.8136872053146362
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 99: 0.9290501416465382
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 100: 0.7920279891594596
[2024-09-16 03:04:36,366][flwr][INFO] - 	History (loss, centralized):
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 0: 221.9475461244583
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 1: 222.40712189674377
[2024-09-16 03:04:36,366][flwr][INFO] - 		round 2: 225.8277063369751
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 3: 226.9033453464508
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 4: 219.2742246389389
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 5: 225.71227169036865
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 6: 212.69008207321167
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 7: 210.99747705459595
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 8: 217.75655806064606
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 9: 211.53920936584473
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 10: 212.4496339559555
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 11: 207.85789918899536
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 12: 197.9943803548813
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 13: 200.7959372997284
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 14: 196.58305251598358
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 15: 197.37777757644653
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 16: 184.78413355350494
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 17: 178.26583349704742
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 18: 184.12346136569977
[2024-09-16 03:04:36,367][flwr][INFO] - 		round 19: 180.85946345329285
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 20: 186.5087388753891
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 21: 175.166854262352
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 22: 162.01871716976166
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 23: 165.10507678985596
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 24: 159.22582721710205
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 25: 162.30230152606964
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 26: 155.5759711265564
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 27: 158.5099893808365
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 28: 163.218106508255
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 29: 161.19386267662048
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 30: 147.68206596374512
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 31: 156.5080590248108
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 32: 155.5536868572235
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 33: 148.333890914917
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 34: 141.71960389614105
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 35: 147.51415634155273
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 36: 156.3957018852234
[2024-09-16 03:04:36,368][flwr][INFO] - 		round 37: 155.1593643426895
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 38: 138.9142925143242
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 39: 140.5434558391571
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 40: 136.8436460494995
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 41: 128.22308945655823
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 42: 130.4853333234787
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 43: 145.06326830387115
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 44: 140.64496791362762
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 45: 130.67094790935516
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 46: 129.7549602985382
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 47: 120.85648685693741
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 48: 123.90543097257614
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 49: 131.517172396183
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 50: 125.22823405265808
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 51: 127.52915245294571
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 52: 117.87029469013214
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 53: 116.6356161236763
[2024-09-16 03:04:36,369][flwr][INFO] - 		round 54: 126.7243824005127
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 55: 117.54354667663574
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 56: 109.19422489404678
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 57: 110.72377771139145
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 58: 123.30316191911697
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 59: 110.33936667442322
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 60: 111.92079746723175
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 61: 109.74626690149307
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 62: 108.98256075382233
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 63: 107.0101757645607
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 64: 100.3701508641243
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 65: 102.9333398938179
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 66: 107.52050477266312
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 67: 105.32294470071793
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 68: 125.37100952863693
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 69: 107.98051297664642
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 70: 146.30827462673187
[2024-09-16 03:04:36,370][flwr][INFO] - 		round 71: 128.77412295341492
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 72: 101.58014035224915
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 73: 96.21172338724136
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 74: 103.31158798933029
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 75: 104.75244671106339
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 76: 104.27346605062485
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 77: 101.53887623548508
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 78: 103.17368078231812
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 79: 106.45165646076202
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 80: 121.40717434883118
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 81: 117.82858872413635
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 82: 103.95496916770935
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 83: 103.82803964614868
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 84: 87.73694461584091
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 85: 92.67124742269516
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 86: 94.95612770318985
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 87: 100.7184567451477
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 88: 86.9513486623764
[2024-09-16 03:04:36,371][flwr][INFO] - 		round 89: 80.47499492764473
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 90: 115.00060242414474
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 91: 81.70718479156494
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 92: 103.58090108633041
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 93: 85.42463451623917
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 94: 101.14766174554825
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 95: 93.58360749483109
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 96: 90.3151027560234
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 97: 99.13649773597717
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 98: 92.16321298480034
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 99: 98.04035091400146
[2024-09-16 03:04:36,372][flwr][INFO] - 		round 100: 106.13965421915054
[2024-09-16 03:04:36,372][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-09-16 03:04:36,372][flwr][INFO] - 	{'accuracy': [(1, 0.08196721311475409),
[2024-09-16 03:04:36,372][flwr][INFO] - 	              (2, 0.0),
[2024-09-16 03:04:36,372][flwr][INFO] - 	              (3, 0.030303030303030304),
[2024-09-16 03:04:36,372][flwr][INFO] - 	              (4, 0.15384615384615385),
[2024-09-16 03:04:36,372][flwr][INFO] - 	              (5, 0.0),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (6, 0.625),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (7, 0.06521739130434782),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (8, 0.2571428571428571),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (9, 0.6),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (10, 0.25),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (11, 0.6938775510204082),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (12, 0.0),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (13, 0.037037037037037035),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (14, 0.09375),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (15, 0.030303030303030304),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (16, 0.6551724137931034),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (17, 0.6857142857142857),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (18, 0.08928571428571429),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (19, 0.0),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (20, 0.0),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (21, 0.7),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (22, 0.16666666666666666),
[2024-09-16 03:04:36,373][flwr][INFO] - 	              (23, 0.5714285714285714),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (24, 0.8888888888888888),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (25, 0.13333333333333333),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (26, 0.75),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (27, 0.7142857142857143),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (28, 0.574468085106383),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (29, 0.717391304347826),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (30, 0.1388888888888889),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (31, 0.5333333333333333),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (32, 0.6666666666666666),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (33, 0.7),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (34, 0.42857142857142855),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (35, 0.9444444444444444),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (36, 0.27450980392156865),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (37, 0.6571428571428571),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (38, 0.3384615384615385),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (39, 0.6666666666666666),
[2024-09-16 03:04:36,374][flwr][INFO] - 	              (40, 0.925),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (41, 0.5882352941176471),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (42, 0.6),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (43, 0.35294117647058826),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (44, 1.0),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (45, 0.5263157894736842),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (46, 0.9354838709677419),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (47, 0.6842105263157895),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (48, 0.6292134831460674),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (49, 0.85),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (50, 0.7777777777777778),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (51, 0.17647058823529413),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (52, 0.25),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (53, 0.9),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (54, 0.7804878048780488),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (55, 0.4117647058823529),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (56, 0.6511627906976745),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (57, 0.7230769230769231),
[2024-09-16 03:04:36,375][flwr][INFO] - 	              (58, 0.9130434782608695),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (59, 0.6129032258064516),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (60, 0.48148148148148145),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (61, 0.6666666666666666),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (62, 0.7419354838709677),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (63, 1.0),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (64, 0.9090909090909091),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (65, 0.8701298701298701),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (66, 0.8653846153846154),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (67, 0.8035714285714286),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (68, 1.0),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (69, 0.43243243243243246),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (70, 0.20454545454545456),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (71, 0.075),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (72, 0.7941176470588235),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (73, 0.8888888888888888),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (74, 0.43243243243243246),
[2024-09-16 03:04:36,376][flwr][INFO] - 	              (75, 0.15517241379310345),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (76, 0.609375),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (77, 0.9090909090909091),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (78, 0.35714285714285715),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (79, 1.0),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (80, 0.8115942028985508),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (81, 0.5084745762711864),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (82, 0.0),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (83, 0.7428571428571429),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (84, 0.958041958041958),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (85, 0.8941176470588236),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (86, 0.7916666666666666),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (87, 0.9242424242424242),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (88, 0.9772727272727273),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (89, 0.8958333333333334),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (90, 0.9622641509433962),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (91, 0.7761194029850746),
[2024-09-16 03:04:36,377][flwr][INFO] - 	              (92, 0.4791666666666667),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (93, 0.8571428571428571),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (94, 0.7837837837837838),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (95, 0.75),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (96, 0.896551724137931),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (97, 0.896551724137931),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (98, 0.8194444444444444),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (99, 0.7283950617283951),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (100, 0.7391304347826086)]}
[2024-09-16 03:04:36,378][flwr][INFO] - 	History (metrics, centralized):
[2024-09-16 03:04:36,378][flwr][INFO] - 	{'accuracy': [(0, 0.22011107863197896),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (1, 0.15580239695995324),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (2, 0.09090909090909091),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (3, 0.09646302250803858),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (4, 0.1657410114001754),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (5, 0.1824028061970184),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (6, 0.24904998538439052),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (7, 0.2584039754457761),
[2024-09-16 03:04:36,378][flwr][INFO] - 	              (8, 0.19847997661502484),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (9, 0.278865828705057),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (10, 0.19497223034200525),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (11, 0.2958199356913183),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (12, 0.29815843320666474),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (13, 0.29026600409237063),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (14, 0.3218357205495469),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (15, 0.3183279742765273),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (16, 0.32066647179187374),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (17, 0.43583747442268345),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (18, 0.29961999415375623),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (19, 0.4688687518269512),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (20, 0.3054662379421222),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (21, 0.4016369482607425),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (22, 0.4858228588132125),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (23, 0.518561824028062),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (24, 0.4744226834258989),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (25, 0.4425606547793043),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (26, 0.6170710318620286),
[2024-09-16 03:04:36,379][flwr][INFO] - 	              (27, 0.6030400467699503),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (28, 0.5290850628471208),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (29, 0.6141479099678456),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (30, 0.5565624086524408),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (31, 0.42443729903536975),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (32, 0.49956153171587253),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (33, 0.6045016077170418),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (34, 0.5363928675825782),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (35, 0.5428237357497807),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (36, 0.43642209880152),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (37, 0.4840689856767027),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (38, 0.47500730780473543),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (39, 0.586085939783689),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (40, 0.6024554223911137),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (41, 0.6395790704472376),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (42, 0.5618240280619702),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (43, 0.38672902660040925),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (44, 0.4425606547793043),
[2024-09-16 03:04:36,380][flwr][INFO] - 	              (45, 0.6641332943583748),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (46, 0.6103478515054078),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (47, 0.6255480853551593),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (48, 0.6305173925752704),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (49, 0.49663840982168955),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (50, 0.5451622332651271),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (51, 0.5176848874598071),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (52, 0.628178895059924),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (53, 0.7024261911721719),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (54, 0.5378544285296697),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (55, 0.715287927506577),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (56, 0.6384098216895645),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (57, 0.6591639871382636),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (58, 0.5641625255773166),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (59, 0.7439345220695703),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (60, 0.6349020754165449),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (61, 0.6696872259573224),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (62, 0.6533177433498977),
[2024-09-16 03:04:36,381][flwr][INFO] - 	              (63, 0.7278573516515638),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (64, 0.7228880444314528),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (65, 0.7144109909383222),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (66, 0.6881028938906752),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (67, 0.7114878690441392),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (68, 0.5828705057000877),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (69, 0.7386729026600409),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (70, 0.4688687518269512),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (71, 0.5612394036831336),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (72, 0.7339959076293482),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (73, 0.7360420929552762),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (74, 0.6933645133002047),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (75, 0.6971645717626425),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (76, 0.6881028938906752),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (77, 0.7664425606547793),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (78, 0.69073370359544),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (79, 0.6495176848874598),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (80, 0.5694241449868459),
[2024-09-16 03:04:36,382][flwr][INFO] - 	              (81, 0.6480561239403683),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (82, 0.7185033615901784),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (83, 0.6574101140017539),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (84, 0.7290266004092371),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (85, 0.7760888629055832),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (86, 0.7538731365097925),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (87, 0.721134171294943),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (88, 0.7418883367436422),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (89, 0.7728734288219818),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (90, 0.6021631102016954),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (91, 0.7784273604209295),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (92, 0.6772873428821982),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (93, 0.7886582870505701),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (94, 0.6430868167202572),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (95, 0.7076878105817013),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (96, 0.769073370359544),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (97, 0.6863490207541655),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (98, 0.7410114001753874),
[2024-09-16 03:04:36,383][flwr][INFO] - 	              (99, 0.7234726688102894),
[2024-09-16 03:04:36,384][flwr][INFO] - 	              (100, 0.623209587839813)]}
[2024-09-16 03:04:36,384][flwr][INFO] - 
