[2024-09-12 12:31:47,199][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-09-12 12:31:50,305][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 256.0, 'node:__internal_head__': 1.0, 'memory': 168651825767.0, 'GPU': 1.0, 'accelerator_type:G': 1.0, 'node:115.145.172.224': 1.0, 'object_store_memory': 76565068185.0}
[2024-09-12 12:31:50,305][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-09-12 12:31:50,305][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 128, 'num_gpus': 0.1}
[2024-09-12 12:31:50,316][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2024-09-12 12:31:50,317][flwr][INFO] - [INIT]
[2024-09-12 12:31:50,317][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 12:31:54,480][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 12:31:54,480][flwr][INFO] - Evaluating initial global parameters
[2024-09-12 12:32:01,044][flwr][INFO] - initial parameters (loss, other metrics): 224.4763035774231, {'accuracy': 0.10435545162233265}
[2024-09-12 12:32:01,044][flwr][INFO] - 
[2024-09-12 12:32:01,044][flwr][INFO] - [ROUND 1]
[2024-09-12 12:32:01,044][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:06,181][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:32:06,404][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-09-12 12:32:12,405][flwr][INFO] - fit progress: (1, 218.73634576797485, {'accuracy': 0.24963460976322713}, 11.36096579162404)
[2024-09-12 12:32:12,406][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:32:12,978][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:32:12,979][flwr][INFO] - 
[2024-09-12 12:32:12,979][flwr][INFO] - [ROUND 2]
[2024-09-12 12:32:12,979][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:15,106][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:32:20,289][flwr][INFO] - fit progress: (2, 214.38134014606476, {'accuracy': 0.2297573808827828}, 19.245257114060223)
[2024-09-12 12:32:20,290][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:32:20,881][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:32:20,882][flwr][INFO] - 
[2024-09-12 12:32:20,882][flwr][INFO] - [ROUND 3]
[2024-09-12 12:32:20,883][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:23,251][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:32:28,783][flwr][INFO] - fit progress: (3, 223.89596319198608, {'accuracy': 0.17217187956737795}, 27.738870192784816)
[2024-09-12 12:32:28,783][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:32:29,330][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:32:29,330][flwr][INFO] - 
[2024-09-12 12:32:29,330][flwr][INFO] - [ROUND 4]
[2024-09-12 12:32:29,330][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:32,186][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:32:37,383][flwr][INFO] - fit progress: (4, 206.39018177986145, {'accuracy': 0.1370944168371821}, 36.33906899578869)
[2024-09-12 12:32:37,388][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:32:37,750][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:32:37,750][flwr][INFO] - 
[2024-09-12 12:32:37,750][flwr][INFO] - [ROUND 5]
[2024-09-12 12:32:37,751][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:40,719][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:32:46,097][flwr][INFO] - fit progress: (5, 191.75265038013458, {'accuracy': 0.34258988599824614}, 45.0532654277049)
[2024-09-12 12:32:46,098][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:32:46,561][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:32:46,562][flwr][INFO] - 
[2024-09-12 12:32:46,562][flwr][INFO] - [ROUND 6]
[2024-09-12 12:32:46,562][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:49,647][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:32:54,563][flwr][INFO] - fit progress: (6, 194.1141241788864, {'accuracy': 0.49780765857936277}, 53.51912160171196)
[2024-09-12 12:32:54,564][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:32:54,661][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:32:54,662][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:32:54,845][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-12 12:32:54,845][flwr][INFO] - 
[2024-09-12 12:32:54,845][flwr][INFO] - [ROUND 7]
[2024-09-12 12:32:54,845][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:32:57,472][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:02,441][flwr][INFO] - fit progress: (7, 159.81848740577698, {'accuracy': 0.40748319204910843}, 61.39738924568519)
[2024-09-12 12:33:02,442][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:02,829][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:02,829][flwr][INFO] - 
[2024-09-12 12:33:02,829][flwr][INFO] - [ROUND 8]
[2024-09-12 12:33:02,829][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:33:06,361][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:11,314][flwr][INFO] - fit progress: (8, 176.66063261032104, {'accuracy': 0.34112832505115465}, 70.270033064764)
[2024-09-12 12:33:11,314][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:11,788][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:11,788][flwr][INFO] - 
[2024-09-12 12:33:11,788][flwr][INFO] - [ROUND 9]
[2024-09-12 12:33:11,789][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:33:13,958][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:19,323][flwr][INFO] - fit progress: (9, 176.88831615447998, {'accuracy': 0.3893598363051739}, 78.27940111979842)
[2024-09-12 12:33:19,324][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:19,686][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:19,686][flwr][INFO] - 
[2024-09-12 12:33:19,687][flwr][INFO] - [ROUND 10]
[2024-09-12 12:33:19,687][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:33:22,260][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:28,400][flwr][INFO] - fit progress: (10, 177.2875176668167, {'accuracy': 0.4191756796258404}, 87.35566096100956)
[2024-09-12 12:33:28,400][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:28,899][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:28,900][flwr][INFO] - 
[2024-09-12 12:33:28,900][flwr][INFO] - [ROUND 11]
[2024-09-12 12:33:28,901][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:33:33,169][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:37,988][flwr][INFO] - fit progress: (11, 208.2570571899414, {'accuracy': 0.388482899736919}, 96.9445306607522)
[2024-09-12 12:33:37,989][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:38,389][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:38,389][flwr][INFO] - 
[2024-09-12 12:33:38,389][flwr][INFO] - [ROUND 12]
[2024-09-12 12:33:38,389][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:33:41,673][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:46,612][flwr][INFO] - fit progress: (12, 306.2243883609772, {'accuracy': 0.33528208126278863}, 105.56816595094278)
[2024-09-12 12:33:46,613][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:46,951][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:46,951][flwr][INFO] - 
[2024-09-12 12:33:46,951][flwr][INFO] - [ROUND 13]
[2024-09-12 12:33:46,951][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:33:52,470][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:33:57,269][flwr][INFO] - fit progress: (13, 271.39337491989136, {'accuracy': 0.31102016954106987}, 116.22537520574406)
[2024-09-12 12:33:57,270][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:33:57,645][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:33:57,645][flwr][INFO] - 
[2024-09-12 12:33:57,645][flwr][INFO] - [ROUND 14]
[2024-09-12 12:33:57,645][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:02,206][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:34:07,306][flwr][INFO] - fit progress: (14, 157.50979244709015, {'accuracy': 0.6170710318620286}, 126.26209230860695)
[2024-09-12 12:34:07,307][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:34:07,745][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:34:07,746][flwr][INFO] - 
[2024-09-12 12:34:07,746][flwr][INFO] - [ROUND 15]
[2024-09-12 12:34:07,746][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:11,378][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:34:16,082][flwr][INFO] - fit progress: (15, 254.55610156059265, {'accuracy': 0.35135925168079507}, 135.03788888873532)
[2024-09-12 12:34:16,082][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:34:16,653][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:34:16,654][flwr][INFO] - 
[2024-09-12 12:34:16,654][flwr][INFO] - [ROUND 16]
[2024-09-12 12:34:16,654][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:22,216][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:34:27,108][flwr][INFO] - fit progress: (16, 171.85407900810242, {'accuracy': 0.4717918737211342}, 146.06427398882806)
[2024-09-12 12:34:27,109][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:34:27,581][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:34:27,582][flwr][INFO] - 
[2024-09-12 12:34:27,582][flwr][INFO] - [ROUND 17]
[2024-09-12 12:34:27,582][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:31,689][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:34:36,733][flwr][INFO] - fit progress: (17, 156.52006256580353, {'accuracy': 0.35282081262788656}, 155.68867131974548)
[2024-09-12 12:34:36,733][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:34:37,319][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:34:37,319][flwr][INFO] - 
[2024-09-12 12:34:37,320][flwr][INFO] - [ROUND 18]
[2024-09-12 12:34:37,320][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:41,015][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:34:45,804][flwr][INFO] - fit progress: (18, 235.9917290210724, {'accuracy': 0.36451330020461853}, 164.7602354027331)
[2024-09-12 12:34:45,805][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:34:46,286][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:34:46,286][flwr][INFO] - 
[2024-09-12 12:34:46,287][flwr][INFO] - [ROUND 19]
[2024-09-12 12:34:46,287][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:48,616][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:34:54,226][flwr][INFO] - fit progress: (19, 521.2437977790833, {'accuracy': 0.16924875767319497}, 173.18216360965744)
[2024-09-12 12:34:54,226][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:34:54,300][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:34:54,301][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:34:54,540][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-12 12:34:54,540][flwr][INFO] - 
[2024-09-12 12:34:54,540][flwr][INFO] - [ROUND 20]
[2024-09-12 12:34:54,541][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:34:58,933][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:35:03,644][flwr][INFO] - fit progress: (20, 183.07517886161804, {'accuracy': 0.3440514469453376}, 182.60001125000417)
[2024-09-12 12:35:03,645][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:35:04,060][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:35:04,060][flwr][INFO] - 
[2024-09-12 12:35:04,060][flwr][INFO] - [ROUND 21]
[2024-09-12 12:35:04,060][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:35:09,426][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:35:14,085][flwr][INFO] - fit progress: (21, 161.4519603252411, {'accuracy': 0.5299619994153756}, 193.04131262982264)
[2024-09-12 12:35:14,086][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:35:14,610][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:35:14,610][flwr][INFO] - 
[2024-09-12 12:35:14,610][flwr][INFO] - [ROUND 22]
[2024-09-12 12:35:14,610][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:35:15,763][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:35:15,763][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:35:17,462][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:35:22,462][flwr][INFO] - fit progress: (22, 125.29056358337402, {'accuracy': 0.6199941537562116}, 201.41833045100793)
[2024-09-12 12:35:22,463][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:35:22,975][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:35:22,975][flwr][INFO] - 
[2024-09-12 12:35:22,975][flwr][INFO] - [ROUND 23]
[2024-09-12 12:35:22,976][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:35:29,392][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:35:34,588][flwr][INFO] - fit progress: (23, 143.08278685808182, {'accuracy': 0.5849166910260157}, 213.54381861863658)
[2024-09-12 12:35:34,588][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:35:34,954][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:35:34,954][flwr][INFO] - 
[2024-09-12 12:35:34,954][flwr][INFO] - [ROUND 24]
[2024-09-12 12:35:34,955][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:35:36,500][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:35:36,500][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:35:38,605][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:35:43,237][flwr][INFO] - fit progress: (24, 173.47260415554047, {'accuracy': 0.3925752703887752}, 222.1932514156215)
[2024-09-12 12:35:43,238][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:35:43,600][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:35:43,601][flwr][INFO] - 
[2024-09-12 12:35:43,601][flwr][INFO] - [ROUND 25]
[2024-09-12 12:35:43,601][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:35:46,664][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:35:51,571][flwr][INFO] - fit progress: (25, 133.29799109697342, {'accuracy': 0.5483776673487284}, 230.52715556882322)
[2024-09-12 12:35:51,571][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:35:51,949][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:35:51,950][flwr][INFO] - 
[2024-09-12 12:35:51,950][flwr][INFO] - [ROUND 26]
[2024-09-12 12:35:51,951][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:35:57,415][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:02,140][flwr][INFO] - fit progress: (26, 140.69135808944702, {'accuracy': 0.6296404560070155}, 241.09610463073477)
[2024-09-12 12:36:02,140][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:02,229][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:36:02,229][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:36:02,464][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-12 12:36:02,465][flwr][INFO] - 
[2024-09-12 12:36:02,465][flwr][INFO] - [ROUND 27]
[2024-09-12 12:36:02,465][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:36:06,884][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:11,976][flwr][INFO] - fit progress: (27, 142.79382157325745, {'accuracy': 0.6059631686641332}, 250.93232723977417)
[2024-09-12 12:36:11,977][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:12,344][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:36:12,345][flwr][INFO] - 
[2024-09-12 12:36:12,345][flwr][INFO] - [ROUND 28]
[2024-09-12 12:36:12,345][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:36:14,126][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:18,826][flwr][INFO] - fit progress: (28, 147.7572784423828, {'accuracy': 0.4539608301666179}, 257.7822786876932)
[2024-09-12 12:36:18,827][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:19,372][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:36:19,373][flwr][INFO] - 
[2024-09-12 12:36:19,373][flwr][INFO] - [ROUND 29]
[2024-09-12 12:36:19,373][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:36:22,881][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:27,623][flwr][INFO] - fit progress: (29, 134.17205375432968, {'accuracy': 0.664425606547793}, 266.57907601678744)
[2024-09-12 12:36:27,623][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:28,004][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:36:28,004][flwr][INFO] - 
[2024-09-12 12:36:28,005][flwr][INFO] - [ROUND 30]
[2024-09-12 12:36:28,005][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:36:32,055][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:36,788][flwr][INFO] - fit progress: (30, 148.52940702438354, {'accuracy': 0.4633148202280035}, 275.74386440077797)
[2024-09-12 12:36:36,788][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:37,132][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:36:37,132][flwr][INFO] - 
[2024-09-12 12:36:37,132][flwr][INFO] - [ROUND 31]
[2024-09-12 12:36:37,133][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:36:40,821][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:46,345][flwr][INFO] - fit progress: (31, 248.02169287204742, {'accuracy': 0.2727272727272727}, 285.3012781669386)
[2024-09-12 12:36:46,346][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:46,744][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:36:46,744][flwr][INFO] - 
[2024-09-12 12:36:46,744][flwr][INFO] - [ROUND 32]
[2024-09-12 12:36:46,745][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:36:51,916][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:36:56,829][flwr][INFO] - fit progress: (32, 143.41301548480988, {'accuracy': 0.6480561239403683}, 295.78466734383255)
[2024-09-12 12:36:56,829][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:36:57,267][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:36:57,267][flwr][INFO] - 
[2024-09-12 12:36:57,268][flwr][INFO] - [ROUND 33]
[2024-09-12 12:36:57,268][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:00,133][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:37:04,934][flwr][INFO] - fit progress: (33, 144.0656032562256, {'accuracy': 0.5434083601286174}, 303.89016485773027)
[2024-09-12 12:37:04,934][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:37:05,406][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:37:05,407][flwr][INFO] - 
[2024-09-12 12:37:05,407][flwr][INFO] - [ROUND 34]
[2024-09-12 12:37:05,407][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:10,792][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:37:15,672][flwr][INFO] - fit progress: (34, 125.13351809978485, {'accuracy': 0.5703010815551008}, 314.62764887092635)
[2024-09-12 12:37:15,672][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:37:16,133][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:37:16,133][flwr][INFO] - 
[2024-09-12 12:37:16,134][flwr][INFO] - [ROUND 35]
[2024-09-12 12:37:16,134][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:17,654][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:37:17,654][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:37:19,828][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:37:24,561][flwr][INFO] - fit progress: (35, 164.75990629196167, {'accuracy': 0.3686056708564747}, 323.5172212808393)
[2024-09-12 12:37:24,562][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:37:24,961][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:37:24,961][flwr][INFO] - 
[2024-09-12 12:37:24,961][flwr][INFO] - [ROUND 36]
[2024-09-12 12:37:24,962][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:27,758][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:37:32,666][flwr][INFO] - fit progress: (36, 172.55711483955383, {'accuracy': 0.3545746857643964}, 331.62208421481773)
[2024-09-12 12:37:32,666][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:37:33,016][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:37:33,017][flwr][INFO] - 
[2024-09-12 12:37:33,018][flwr][INFO] - [ROUND 37]
[2024-09-12 12:37:33,018][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:37,222][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:37:41,900][flwr][INFO] - fit progress: (37, 169.3026648759842, {'accuracy': 0.4180064308681672}, 340.8558172429912)
[2024-09-12 12:37:41,900][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:37:42,325][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:37:42,325][flwr][INFO] - 
[2024-09-12 12:37:42,325][flwr][INFO] - [ROUND 38]
[2024-09-12 12:37:42,326][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:46,322][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:37:51,083][flwr][INFO] - fit progress: (38, 155.1872662305832, {'accuracy': 0.48085355159310145}, 350.03919102670625)
[2024-09-12 12:37:51,083][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:37:51,563][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:37:51,563][flwr][INFO] - 
[2024-09-12 12:37:51,563][flwr][INFO] - [ROUND 39]
[2024-09-12 12:37:51,563][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:37:55,012][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:37:59,916][flwr][INFO] - fit progress: (39, 144.7092308998108, {'accuracy': 0.5469161064016369}, 358.8721903269179)
[2024-09-12 12:37:59,916][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:00,543][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:00,544][flwr][INFO] - 
[2024-09-12 12:38:00,544][flwr][INFO] - [ROUND 40]
[2024-09-12 12:38:00,544][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:03,829][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:38:09,628][flwr][INFO] - fit progress: (40, 102.96461355686188, {'accuracy': 0.6650102309266296}, 368.5842746319249)
[2024-09-12 12:38:09,629][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:10,006][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:10,006][flwr][INFO] - 
[2024-09-12 12:38:10,006][flwr][INFO] - [ROUND 41]
[2024-09-12 12:38:10,006][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:14,821][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:38:19,512][flwr][INFO] - fit progress: (41, 113.50659114122391, {'accuracy': 0.6796258403975446}, 378.4680501646362)
[2024-09-12 12:38:19,512][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:20,096][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:20,097][flwr][INFO] - 
[2024-09-12 12:38:20,097][flwr][INFO] - [ROUND 42]
[2024-09-12 12:38:20,097][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:23,949][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:38:29,810][flwr][INFO] - fit progress: (42, 182.27149879932404, {'accuracy': 0.47471499561531716}, 388.7662149099633)
[2024-09-12 12:38:29,811][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:30,322][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:30,322][flwr][INFO] - 
[2024-09-12 12:38:30,322][flwr][INFO] - [ROUND 43]
[2024-09-12 12:38:30,323][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:30,861][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:38:30,861][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:38:33,490][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:38:38,378][flwr][INFO] - fit progress: (43, 232.7007645368576, {'accuracy': 0.36071324174218067}, 397.3337534596212)
[2024-09-12 12:38:38,378][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:38,826][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:38,827][flwr][INFO] - 
[2024-09-12 12:38:38,827][flwr][INFO] - [ROUND 44]
[2024-09-12 12:38:38,827][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:42,907][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:38:47,718][flwr][INFO] - fit progress: (44, 167.87448108196259, {'accuracy': 0.3648056123940368}, 406.67438201094046)
[2024-09-12 12:38:47,719][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:48,041][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:48,042][flwr][INFO] - 
[2024-09-12 12:38:48,042][flwr][INFO] - [ROUND 45]
[2024-09-12 12:38:48,042][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:49,423][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:38:49,425][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:38:49,922][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:38:54,874][flwr][INFO] - fit progress: (45, 137.67231440544128, {'accuracy': 0.7018415667933353}, 413.83005952788517)
[2024-09-12 12:38:54,875][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:38:55,416][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:38:55,416][flwr][INFO] - 
[2024-09-12 12:38:55,416][flwr][INFO] - [ROUND 46]
[2024-09-12 12:38:55,416][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:38:59,331][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:39:04,070][flwr][INFO] - fit progress: (46, 147.75232136249542, {'accuracy': 0.5790704472376498}, 423.02619003597647)
[2024-09-12 12:39:04,071][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:39:04,541][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:39:04,541][flwr][INFO] - 
[2024-09-12 12:39:04,541][flwr][INFO] - [ROUND 47]
[2024-09-12 12:39:04,542][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:39:09,227][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:39:14,142][flwr][INFO] - fit progress: (47, 146.86439102888107, {'accuracy': 0.5358082432037415}, 433.0983115597628)
[2024-09-12 12:39:14,143][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:39:14,599][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:39:14,600][flwr][INFO] - 
[2024-09-12 12:39:14,600][flwr][INFO] - [ROUND 48]
[2024-09-12 12:39:14,600][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:39:17,651][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:39:23,509][flwr][INFO] - fit progress: (48, 142.21672594547272, {'accuracy': 0.552762350190003}, 442.4655398069881)
[2024-09-12 12:39:23,510][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:39:23,911][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:39:23,911][flwr][INFO] - 
[2024-09-12 12:39:23,912][flwr][INFO] - [ROUND 49]
[2024-09-12 12:39:23,912][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:39:26,526][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:39:32,165][flwr][INFO] - fit progress: (49, 246.04723298549652, {'accuracy': 0.4042677579655072}, 451.1207532300614)
[2024-09-12 12:39:32,165][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:39:32,687][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:39:32,688][flwr][INFO] - 
[2024-09-12 12:39:32,688][flwr][INFO] - [ROUND 50]
[2024-09-12 12:39:32,688][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:39:37,038][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:39:41,957][flwr][INFO] - fit progress: (50, 134.03990930318832, {'accuracy': 0.6541946799181526}, 460.913025542628)
[2024-09-12 12:39:41,957][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:39:42,388][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:39:42,388][flwr][INFO] - 
[2024-09-12 12:39:42,388][flwr][INFO] - [ROUND 51]
[2024-09-12 12:39:42,388][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:39:46,159][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:39:52,470][flwr][INFO] - fit progress: (51, 117.3607405424118, {'accuracy': 0.5732242034492838}, 471.4264315129258)
[2024-09-12 12:39:52,471][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:39:53,007][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:39:53,007][flwr][INFO] - 
[2024-09-12 12:39:53,007][flwr][INFO] - [ROUND 52]
[2024-09-12 12:39:53,007][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:39:55,725][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:00,745][flwr][INFO] - fit progress: (52, 140.65064615011215, {'accuracy': 0.5416544869921076}, 479.7011596886441)
[2024-09-12 12:40:00,745][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:01,127][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:01,127][flwr][INFO] - 
[2024-09-12 12:40:01,128][flwr][INFO] - [ROUND 53]
[2024-09-12 12:40:01,128][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:03,353][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:08,422][flwr][INFO] - fit progress: (53, 140.1360575556755, {'accuracy': 0.5624086524408067}, 487.3784920289181)
[2024-09-12 12:40:08,423][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:08,775][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:08,776][flwr][INFO] - 
[2024-09-12 12:40:08,776][flwr][INFO] - [ROUND 54]
[2024-09-12 12:40:08,777][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:12,526][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:17,414][flwr][INFO] - fit progress: (54, 230.5911066532135, {'accuracy': 0.3668517977199649}, 496.37035160465166)
[2024-09-12 12:40:17,415][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:17,966][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:17,966][flwr][INFO] - 
[2024-09-12 12:40:17,966][flwr][INFO] - [ROUND 55]
[2024-09-12 12:40:17,966][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:22,425][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:27,433][flwr][INFO] - fit progress: (55, 129.4466009736061, {'accuracy': 0.6080093539900614}, 506.38906905660406)
[2024-09-12 12:40:27,433][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:27,826][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:27,826][flwr][INFO] - 
[2024-09-12 12:40:27,826][flwr][INFO] - [ROUND 56]
[2024-09-12 12:40:27,826][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:32,156][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:37,861][flwr][INFO] - fit progress: (56, 139.17772042751312, {'accuracy': 0.4852382344343759}, 516.8171794828959)
[2024-09-12 12:40:37,861][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:38,368][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:38,369][flwr][INFO] - 
[2024-09-12 12:40:38,369][flwr][INFO] - [ROUND 57]
[2024-09-12 12:40:38,370][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:42,228][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:47,311][flwr][INFO] - fit progress: (57, 109.17649501562119, {'accuracy': 0.6474714995615317}, 526.2673981469125)
[2024-09-12 12:40:47,312][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:47,709][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:47,710][flwr][INFO] - 
[2024-09-12 12:40:47,710][flwr][INFO] - [ROUND 58]
[2024-09-12 12:40:47,710][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:50,285][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:40:55,203][flwr][INFO] - fit progress: (58, 141.68732237815857, {'accuracy': 0.5784858228588132}, 534.1590102040209)
[2024-09-12 12:40:55,203][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:40:55,661][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:40:55,662][flwr][INFO] - 
[2024-09-12 12:40:55,663][flwr][INFO] - [ROUND 59]
[2024-09-12 12:40:55,663][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:40:59,122][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:41:04,101][flwr][INFO] - fit progress: (59, 111.61268037557602, {'accuracy': 0.6416252557731658}, 543.0571839190088)
[2024-09-12 12:41:04,101][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:41:04,568][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:41:04,569][flwr][INFO] - 
[2024-09-12 12:41:04,569][flwr][INFO] - [ROUND 60]
[2024-09-12 12:41:04,569][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:41:06,996][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:41:06,997][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:41:10,514][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:41:15,256][flwr][INFO] - fit progress: (60, 106.09272861480713, {'accuracy': 0.6550716164864074}, 554.2122830110602)
[2024-09-12 12:41:15,257][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:41:15,617][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:41:15,618][flwr][INFO] - 
[2024-09-12 12:41:15,618][flwr][INFO] - [ROUND 61]
[2024-09-12 12:41:15,618][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:41:20,938][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:41:26,856][flwr][INFO] - fit progress: (61, 137.98078626394272, {'accuracy': 0.535223618824905}, 565.8118397979997)
[2024-09-12 12:41:26,856][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:41:27,316][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:41:27,317][flwr][INFO] - 
[2024-09-12 12:41:27,317][flwr][INFO] - [ROUND 62]
[2024-09-12 12:41:27,317][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:41:31,203][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:41:35,972][flwr][INFO] - fit progress: (62, 140.25659787654877, {'accuracy': 0.5521777258111663}, 574.9276203978807)
[2024-09-12 12:41:35,972][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:41:36,396][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:41:36,397][flwr][INFO] - 
[2024-09-12 12:41:36,397][flwr][INFO] - [ROUND 63]
[2024-09-12 12:41:36,398][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:41:36,498][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:41:36,501][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:41:39,728][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:41:45,738][flwr][INFO] - fit progress: (63, 265.23012340068817, {'accuracy': 0.3022508038585209}, 584.6937011140399)
[2024-09-12 12:41:45,738][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:41:46,042][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:41:46,043][flwr][INFO] - 
[2024-09-12 12:41:46,043][flwr][INFO] - [ROUND 64]
[2024-09-12 12:41:46,043][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:41:50,216][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:41:55,719][flwr][INFO] - fit progress: (64, 159.65151822566986, {'accuracy': 0.4644840689856767}, 594.6747283460572)
[2024-09-12 12:41:55,719][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:41:56,086][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:41:56,086][flwr][INFO] - 
[2024-09-12 12:41:56,086][flwr][INFO] - [ROUND 65]
[2024-09-12 12:41:56,086][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:41:59,620][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:04,694][flwr][INFO] - fit progress: (65, 155.75812304019928, {'accuracy': 0.44343759134755917}, 603.6498492108658)
[2024-09-12 12:42:04,694][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:05,162][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:42:05,163][flwr][INFO] - 
[2024-09-12 12:42:05,163][flwr][INFO] - [ROUND 66]
[2024-09-12 12:42:05,163][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:42:08,409][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:13,496][flwr][INFO] - fit progress: (66, 135.57189691066742, {'accuracy': 0.6384098216895645}, 612.4523330568336)
[2024-09-12 12:42:13,497][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:13,920][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:42:13,920][flwr][INFO] - 
[2024-09-12 12:42:13,921][flwr][INFO] - [ROUND 67]
[2024-09-12 12:42:13,921][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:42:18,111][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:23,043][flwr][INFO] - fit progress: (67, 118.42293870449066, {'accuracy': 0.6796258403975446}, 621.9988159588538)
[2024-09-12 12:42:23,043][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:23,534][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:42:23,535][flwr][INFO] - 
[2024-09-12 12:42:23,535][flwr][INFO] - [ROUND 68]
[2024-09-12 12:42:23,535][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:42:25,780][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:30,794][flwr][INFO] - fit progress: (68, 260.3655446767807, {'accuracy': 0.26951183864367145}, 629.7502062707208)
[2024-09-12 12:42:30,795][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:30,885][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:42:30,885][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:42:31,062][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-12 12:42:31,063][flwr][INFO] - 
[2024-09-12 12:42:31,063][flwr][INFO] - [ROUND 69]
[2024-09-12 12:42:31,063][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:42:33,909][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:38,617][flwr][INFO] - fit progress: (69, 134.11615598201752, {'accuracy': 0.5425314235603624}, 637.5733785037883)
[2024-09-12 12:42:38,618][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:39,050][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:42:39,051][flwr][INFO] - 
[2024-09-12 12:42:39,051][flwr][INFO] - [ROUND 70]
[2024-09-12 12:42:39,052][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:42:41,985][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:47,059][flwr][INFO] - fit progress: (70, 217.53636395931244, {'accuracy': 0.3978368897983046}, 646.0153271500021)
[2024-09-12 12:42:47,060][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:47,582][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:42:47,582][flwr][INFO] - 
[2024-09-12 12:42:47,582][flwr][INFO] - [ROUND 71]
[2024-09-12 12:42:47,582][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:42:50,343][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:42:55,239][flwr][INFO] - fit progress: (71, 195.44338047504425, {'accuracy': 0.5963168664133295}, 654.1950580147095)
[2024-09-12 12:42:55,239][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:42:55,648][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:42:55,649][flwr][INFO] - 
[2024-09-12 12:42:55,649][flwr][INFO] - [ROUND 72]
[2024-09-12 12:42:55,649][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:01,979][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:43:06,935][flwr][INFO] - fit progress: (72, 122.61441653966904, {'accuracy': 0.6772873428821982}, 665.8913960508071)
[2024-09-12 12:43:06,936][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:07,472][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:07,473][flwr][INFO] - 
[2024-09-12 12:43:07,473][flwr][INFO] - [ROUND 73]
[2024-09-12 12:43:07,474][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:09,882][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:43:14,679][flwr][INFO] - fit progress: (73, 103.41260766983032, {'accuracy': 0.6422098801520023}, 673.6355299958959)
[2024-09-12 12:43:14,680][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:15,074][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:15,074][flwr][INFO] - 
[2024-09-12 12:43:15,075][flwr][INFO] - [ROUND 74]
[2024-09-12 12:43:15,075][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:17,819][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:43:22,771][flwr][INFO] - fit progress: (74, 118.76614534854889, {'accuracy': 0.6156094709149371}, 681.7269508079626)
[2024-09-12 12:43:22,771][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:23,302][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:23,302][flwr][INFO] - 
[2024-09-12 12:43:23,302][flwr][INFO] - [ROUND 75]
[2024-09-12 12:43:23,302][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:26,163][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:43:30,929][flwr][INFO] - fit progress: (75, 130.09694522619247, {'accuracy': 0.5936860567085648}, 689.8854598640464)
[2024-09-12 12:43:30,930][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:31,403][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:31,404][flwr][INFO] - 
[2024-09-12 12:43:31,404][flwr][INFO] - [ROUND 76]
[2024-09-12 12:43:31,404][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:34,168][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:43:39,334][flwr][INFO] - fit progress: (76, 108.41445350646973, {'accuracy': 0.5840397544577609}, 698.2896099397913)
[2024-09-12 12:43:39,334][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:39,920][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:39,920][flwr][INFO] - 
[2024-09-12 12:43:39,920][flwr][INFO] - [ROUND 77]
[2024-09-12 12:43:39,920][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:39,986][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:43:39,987][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925948, ip=115.145.172.224, actor_id=6d33b01d773b92bcb867df8001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fba4c69d810>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:43:42,568][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:43:47,724][flwr][INFO] - fit progress: (77, 91.61978089809418, {'accuracy': 0.7588424437299035}, 706.6804448836483)
[2024-09-12 12:43:47,725][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:48,360][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:48,361][flwr][INFO] - 
[2024-09-12 12:43:48,361][flwr][INFO] - [ROUND 78]
[2024-09-12 12:43:48,361][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:43:53,479][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:43:58,252][flwr][INFO] - fit progress: (78, 108.0238745212555, {'accuracy': 0.6769950306927799}, 717.2080245367251)
[2024-09-12 12:43:58,252][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:43:58,623][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:43:58,624][flwr][INFO] - 
[2024-09-12 12:43:58,624][flwr][INFO] - [ROUND 79]
[2024-09-12 12:43:58,624][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:44:01,536][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:44:07,456][flwr][INFO] - fit progress: (79, 129.7868390083313, {'accuracy': 0.5580239695995323}, 726.4120635907166)
[2024-09-12 12:44:07,457][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:44:07,801][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:44:07,801][flwr][INFO] - 
[2024-09-12 12:44:07,801][flwr][INFO] - [ROUND 80]
[2024-09-12 12:44:07,801][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:44:11,354][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:44:17,028][flwr][INFO] - fit progress: (80, 136.5367540717125, {'accuracy': 0.5033615901783104}, 735.983692759648)
[2024-09-12 12:44:17,028][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:44:17,523][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:44:17,523][flwr][INFO] - 
[2024-09-12 12:44:17,523][flwr][INFO] - [ROUND 81]
[2024-09-12 12:44:17,523][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:44:20,534][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:44:25,453][flwr][INFO] - fit progress: (81, 128.2641777396202, {'accuracy': 0.6214557147033031}, 744.4087553247809)
[2024-09-12 12:44:25,453][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:44:25,839][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:44:25,840][flwr][INFO] - 
[2024-09-12 12:44:25,840][flwr][INFO] - [ROUND 82]
[2024-09-12 12:44:25,840][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:44:30,723][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:44:36,374][flwr][INFO] - fit progress: (82, 100.817018866539, {'accuracy': 0.7415960245542239}, 755.3296717209741)
[2024-09-12 12:44:36,374][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:44:36,676][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:44:36,677][flwr][INFO] - 
[2024-09-12 12:44:36,677][flwr][INFO] - [ROUND 83]
[2024-09-12 12:44:36,677][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:44:41,581][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:44:46,526][flwr][INFO] - fit progress: (83, 123.56397521495819, {'accuracy': 0.5787781350482315}, 765.4815407427959)
[2024-09-12 12:44:46,526][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:44:47,041][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:44:47,041][flwr][INFO] - 
[2024-09-12 12:44:47,041][flwr][INFO] - [ROUND 84]
[2024-09-12 12:44:47,041][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:44:51,021][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:44:55,799][flwr][INFO] - fit progress: (84, 134.3797391653061, {'accuracy': 0.5349313066354867}, 774.755174939055)
[2024-09-12 12:44:55,799][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:44:56,320][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:44:56,321][flwr][INFO] - 
[2024-09-12 12:44:56,321][flwr][INFO] - [ROUND 85]
[2024-09-12 12:44:56,321][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:45:01,897][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:45:06,791][flwr][INFO] - fit progress: (85, 105.34118646383286, {'accuracy': 0.7050570008769366}, 785.7469073468819)
[2024-09-12 12:45:06,791][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:45:07,217][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:45:07,217][flwr][INFO] - 
[2024-09-12 12:45:07,217][flwr][INFO] - [ROUND 86]
[2024-09-12 12:45:07,217][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:45:11,568][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:45:16,291][flwr][INFO] - fit progress: (86, 126.29498064517975, {'accuracy': 0.5784858228588132}, 795.2468830049038)
[2024-09-12 12:45:16,291][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:45:16,720][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:45:16,721][flwr][INFO] - 
[2024-09-12 12:45:16,721][flwr][INFO] - [ROUND 87]
[2024-09-12 12:45:16,721][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:45:20,611][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:45:25,522][flwr][INFO] - fit progress: (87, 89.96103626489639, {'accuracy': 0.8512130955860859}, 804.4776858338155)
[2024-09-12 12:45:25,522][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:45:26,073][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:45:26,073][flwr][INFO] - 
[2024-09-12 12:45:26,073][flwr][INFO] - [ROUND 88]
[2024-09-12 12:45:26,073][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:45:29,775][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:45:36,122][flwr][INFO] - fit progress: (88, 151.06427466869354, {'accuracy': 0.5057000876936568}, 815.078380508814)
[2024-09-12 12:45:36,123][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:45:36,572][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:45:36,572][flwr][INFO] - 
[2024-09-12 12:45:36,573][flwr][INFO] - [ROUND 89]
[2024-09-12 12:45:36,573][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:45:40,814][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:45:46,642][flwr][INFO] - fit progress: (89, 114.49658703804016, {'accuracy': 0.6015784858228588}, 825.5978370858356)
[2024-09-12 12:45:46,642][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:45:47,025][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:45:47,025][flwr][INFO] - 
[2024-09-12 12:45:47,026][flwr][INFO] - [ROUND 90]
[2024-09-12 12:45:47,026][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:45:47,113][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:45:47,114][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:45:48,952][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-12 12:45:53,909][flwr][INFO] - fit progress: (90, 162.88014024496078, {'accuracy': 0.5492546039169833}, 832.8651892640628)
[2024-09-12 12:45:53,910][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:45:54,313][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:45:54,313][flwr][INFO] - 
[2024-09-12 12:45:54,313][flwr][INFO] - [ROUND 91]
[2024-09-12 12:45:54,314][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:46:02,928][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:46:08,733][flwr][INFO] - fit progress: (91, 76.77149811387062, {'accuracy': 0.7676118094124526}, 847.6886509666219)
[2024-09-12 12:46:08,733][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:46:09,225][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:46:09,226][flwr][INFO] - 
[2024-09-12 12:46:09,226][flwr][INFO] - [ROUND 92]
[2024-09-12 12:46:09,226][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:46:14,159][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:46:19,971][flwr][INFO] - fit progress: (92, 127.63680821657181, {'accuracy': 0.6150248465361006}, 858.9271754189394)
[2024-09-12 12:46:19,972][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:46:20,381][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:46:20,381][flwr][INFO] - 
[2024-09-12 12:46:20,382][flwr][INFO] - [ROUND 93]
[2024-09-12 12:46:20,382][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:46:22,718][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:46:28,345][flwr][INFO] - fit progress: (93, 99.404760658741, {'accuracy': 0.6989184448991523}, 867.3008283879608)
[2024-09-12 12:46:28,345][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:46:28,662][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:46:28,662][flwr][INFO] - 
[2024-09-12 12:46:28,663][flwr][INFO] - [ROUND 94]
[2024-09-12 12:46:28,663][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:46:32,341][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:46:37,059][flwr][INFO] - fit progress: (94, 129.50546339154243, {'accuracy': 0.6828412744811458}, 876.015217971988)
[2024-09-12 12:46:37,059][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:46:37,444][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:46:37,444][flwr][INFO] - 
[2024-09-12 12:46:37,444][flwr][INFO] - [ROUND 95]
[2024-09-12 12:46:37,444][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:46:39,956][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:46:44,657][flwr][INFO] - fit progress: (95, 111.01611256599426, {'accuracy': 0.665302543116048}, 883.612778773997)
[2024-09-12 12:46:44,657][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:46:44,727][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-12 12:46:44,727][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet_poisoned/fedavg_mobilnet_poisoned/client.py", line 113, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=2925949, ip=115.145.172.224, actor_id=86b7b96307951cc39efd4bee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f9a14571840>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-12 12:46:45,060][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-12 12:46:45,061][flwr][INFO] - 
[2024-09-12 12:46:45,061][flwr][INFO] - [ROUND 96]
[2024-09-12 12:46:45,061][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:46:49,700][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:46:55,249][flwr][INFO] - fit progress: (96, 126.65654993057251, {'accuracy': 0.5451622332651271}, 894.2046775608324)
[2024-09-12 12:46:55,249][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:46:55,592][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:46:55,592][flwr][INFO] - 
[2024-09-12 12:46:55,592][flwr][INFO] - [ROUND 97]
[2024-09-12 12:46:55,592][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:47:00,649][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:47:05,353][flwr][INFO] - fit progress: (97, 100.30307388305664, {'accuracy': 0.7541654486992108}, 904.3090322520584)
[2024-09-12 12:47:05,353][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:47:05,764][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:47:05,765][flwr][INFO] - 
[2024-09-12 12:47:05,765][flwr][INFO] - [ROUND 98]
[2024-09-12 12:47:05,766][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:47:08,866][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:47:13,618][flwr][INFO] - fit progress: (98, 74.95013988018036, {'accuracy': 0.8129201987722888}, 912.573595804628)
[2024-09-12 12:47:13,618][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:47:14,187][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:47:14,187][flwr][INFO] - 
[2024-09-12 12:47:14,187][flwr][INFO] - [ROUND 99]
[2024-09-12 12:47:14,187][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:47:19,169][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:47:23,953][flwr][INFO] - fit progress: (99, 88.22627657651901, {'accuracy': 0.7766734872844198}, 922.9092648359947)
[2024-09-12 12:47:23,954][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:47:24,425][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:47:24,425][flwr][INFO] - 
[2024-09-12 12:47:24,425][flwr][INFO] - [ROUND 100]
[2024-09-12 12:47:24,425][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-12 12:47:27,860][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-12 12:47:33,481][flwr][INFO] - fit progress: (100, 152.77632439136505, {'accuracy': 0.4375913475591932}, 932.43756440375)
[2024-09-12 12:47:33,482][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-12 12:47:33,990][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-12 12:47:33,990][flwr][INFO] - 
[2024-09-12 12:47:33,991][flwr][INFO] - [SUMMARY]
[2024-09-12 12:47:33,991][flwr][INFO] - Run finished 100 round(s) in 932.95s
[2024-09-12 12:47:33,994][flwr][INFO] - 	History (loss, distributed):
[2024-09-12 12:47:33,995][flwr][INFO] - 		round 1: 2.3627322462738536
[2024-09-12 12:47:33,996][flwr][INFO] - 		round 2: 3.4346866607666016
[2024-09-12 12:47:33,997][flwr][INFO] - 		round 3: 2.2796814224936743
[2024-09-12 12:47:33,997][flwr][INFO] - 		round 4: 1.962205538382897
[2024-09-12 12:47:33,998][flwr][INFO] - 		round 5: 2.0592686721256803
[2024-09-12 12:47:33,998][flwr][INFO] - 		round 6: 0.9678859114646912
[2024-09-12 12:47:33,999][flwr][INFO] - 		round 7: 1.9290257536846658
[2024-09-12 12:47:33,999][flwr][INFO] - 		round 8: 0.8192219291414533
[2024-09-12 12:47:34,000][flwr][INFO] - 		round 9: 0.6444686830043793
[2024-09-12 12:47:34,000][flwr][INFO] - 		round 10: 1.6213391508374895
[2024-09-12 12:47:34,001][flwr][INFO] - 		round 11: 1.3643200859731557
[2024-09-12 12:47:34,002][flwr][INFO] - 		round 12: 4.75647767384847
[2024-09-12 12:47:34,002][flwr][INFO] - 		round 13: 3.7496244819075972
[2024-09-12 12:47:34,003][flwr][INFO] - 		round 14: 2.4009577594697475
[2024-09-12 12:47:34,003][flwr][INFO] - 		round 15: 2.168878138065338
[2024-09-12 12:47:34,004][flwr][INFO] - 		round 16: 1.2467549422691608
[2024-09-12 12:47:34,004][flwr][INFO] - 		round 17: 0.7477181502750941
[2024-09-12 12:47:34,005][flwr][INFO] - 		round 18: 2.1763197651931216
[2024-09-12 12:47:34,005][flwr][INFO] - 		round 19: 7.802425384521484
[2024-09-12 12:47:34,006][flwr][INFO] - 		round 20: 2.2572982907295227
[2024-09-12 12:47:34,007][flwr][INFO] - 		round 21: 1.1583704914365496
[2024-09-12 12:47:34,007][flwr][INFO] - 		round 22: 1.6524819334348042
[2024-09-12 12:47:34,008][flwr][INFO] - 		round 23: 1.0410433794770921
[2024-09-12 12:47:34,008][flwr][INFO] - 		round 24: 1.896959004578767
[2024-09-12 12:47:34,009][flwr][INFO] - 		round 25: 2.67791649500529
[2024-09-12 12:47:34,009][flwr][INFO] - 		round 26: 0.7350624203681946
[2024-09-12 12:47:34,010][flwr][INFO] - 		round 27: 1.265193053654262
[2024-09-12 12:47:34,010][flwr][INFO] - 		round 28: 1.522442102432251
[2024-09-12 12:47:34,011][flwr][INFO] - 		round 29: 1.104922424192014
[2024-09-12 12:47:34,012][flwr][INFO] - 		round 30: 1.3951659202575684
[2024-09-12 12:47:34,012][flwr][INFO] - 		round 31: 1.8738151093324025
[2024-09-12 12:47:34,013][flwr][INFO] - 		round 32: 0.8082999944686889
[2024-09-12 12:47:34,013][flwr][INFO] - 		round 33: 1.4217426240444184
[2024-09-12 12:47:34,014][flwr][INFO] - 		round 34: 2.1837893213544572
[2024-09-12 12:47:34,014][flwr][INFO] - 		round 35: 0.5574134637912115
[2024-09-12 12:47:34,015][flwr][INFO] - 		round 36: 2.2627378351548137
[2024-09-12 12:47:34,015][flwr][INFO] - 		round 37: 0.9008436441421509
[2024-09-12 12:47:34,016][flwr][INFO] - 		round 38: 1.2065148922113271
[2024-09-12 12:47:34,016][flwr][INFO] - 		round 39: 0.8890519467267123
[2024-09-12 12:47:34,017][flwr][INFO] - 		round 40: 0.2952136605978012
[2024-09-12 12:47:34,018][flwr][INFO] - 		round 41: 1.1108874082565308
[2024-09-12 12:47:34,018][flwr][INFO] - 		round 42: 0.8227617740631104
[2024-09-12 12:47:34,019][flwr][INFO] - 		round 43: 2.703660284771639
[2024-09-12 12:47:34,019][flwr][INFO] - 		round 44: 0.8667744696140289
[2024-09-12 12:47:34,020][flwr][INFO] - 		round 45: 1.3405187318199558
[2024-09-12 12:47:34,020][flwr][INFO] - 		round 46: 1.2941468108084895
[2024-09-12 12:47:34,021][flwr][INFO] - 		round 47: 1.8584789414154856
[2024-09-12 12:47:34,021][flwr][INFO] - 		round 48: 1.4763601254881098
[2024-09-12 12:47:34,021][flwr][INFO] - 		round 49: 0.5731590270996094
[2024-09-12 12:47:34,021][flwr][INFO] - 		round 50: 0.09735013875696394
[2024-09-12 12:47:34,021][flwr][INFO] - 		round 51: 2.1225577662972843
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 52: 2.2934053391218185
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 53: 0.521235853433609
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 54: 0.8989713834371509
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 55: 1.325435715563157
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 56: 0.6545998362261195
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 57: 0.5841345544044788
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 58: 0.3130427304169406
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 59: 0.8851622612245621
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 60: 0.650891109197228
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 61: 0.6787770539522171
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 62: 0.5432897618701381
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 63: 2.0247225111181084
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 64: 1.1857559572566638
[2024-09-12 12:47:34,022][flwr][INFO] - 		round 65: 0.8486821953352396
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 66: 0.871595333975095
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 67: 1.3669111813817705
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 68: 1.3934892416000366
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 69: 1.8448895699269063
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 70: 3.7509634678506036
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 71: 3.9892676174640656
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 72: 1.9850964931880726
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 73: 0.8641341320342488
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 74: 1.9181286418760144
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 75: 1.6146632556257576
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 76: 2.1910757049918175
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 77: 0.5667908583024536
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 78: 1.6847340485879354
[2024-09-12 12:47:34,023][flwr][INFO] - 		round 79: 0.21774974713722864
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 80: 0.7661312181448591
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 81: 1.4573008327160852
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 82: 3.3935327529907227
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 83: 0.6339615413120815
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 84: 1.7364426820011405
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 85: 0.49481105909628026
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 86: 1.2417192483941715
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 87: 1.1988799192688682
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 88: 0.15158003975044598
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 89: 0.17995616793632507
[2024-09-12 12:47:34,024][flwr][INFO] - 		round 90: 0.08144243483273488
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 91: 0.6675528786075648
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 92: 1.7906326154867809
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 93: 0.41785041775022236
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 94: 0.27559408424673854
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 95: 0.9443221688270569
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 96: 1.454802130830699
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 97: 0.3549842217872883
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 98: 0.7133274935185909
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 99: 0.6871325020436887
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 100: 1.825752766236015
[2024-09-12 12:47:34,025][flwr][INFO] - 	History (loss, centralized):
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 0: 224.4763035774231
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 1: 218.73634576797485
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 2: 214.38134014606476
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 3: 223.89596319198608
[2024-09-12 12:47:34,025][flwr][INFO] - 		round 4: 206.39018177986145
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 5: 191.75265038013458
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 6: 194.1141241788864
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 7: 159.81848740577698
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 8: 176.66063261032104
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 9: 176.88831615447998
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 10: 177.2875176668167
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 11: 208.2570571899414
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 12: 306.2243883609772
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 13: 271.39337491989136
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 14: 157.50979244709015
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 15: 254.55610156059265
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 16: 171.85407900810242
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 17: 156.52006256580353
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 18: 235.9917290210724
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 19: 521.2437977790833
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 20: 183.07517886161804
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 21: 161.4519603252411
[2024-09-12 12:47:34,026][flwr][INFO] - 		round 22: 125.29056358337402
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 23: 143.08278685808182
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 24: 173.47260415554047
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 25: 133.29799109697342
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 26: 140.69135808944702
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 27: 142.79382157325745
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 28: 147.7572784423828
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 29: 134.17205375432968
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 30: 148.52940702438354
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 31: 248.02169287204742
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 32: 143.41301548480988
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 33: 144.0656032562256
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 34: 125.13351809978485
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 35: 164.75990629196167
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 36: 172.55711483955383
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 37: 169.3026648759842
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 38: 155.1872662305832
[2024-09-12 12:47:34,027][flwr][INFO] - 		round 39: 144.7092308998108
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 40: 102.96461355686188
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 41: 113.50659114122391
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 42: 182.27149879932404
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 43: 232.7007645368576
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 44: 167.87448108196259
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 45: 137.67231440544128
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 46: 147.75232136249542
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 47: 146.86439102888107
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 48: 142.21672594547272
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 49: 246.04723298549652
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 50: 134.03990930318832
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 51: 117.3607405424118
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 52: 140.65064615011215
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 53: 140.1360575556755
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 54: 230.5911066532135
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 55: 129.4466009736061
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 56: 139.17772042751312
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 57: 109.17649501562119
[2024-09-12 12:47:34,028][flwr][INFO] - 		round 58: 141.68732237815857
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 59: 111.61268037557602
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 60: 106.09272861480713
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 61: 137.98078626394272
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 62: 140.25659787654877
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 63: 265.23012340068817
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 64: 159.65151822566986
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 65: 155.75812304019928
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 66: 135.57189691066742
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 67: 118.42293870449066
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 68: 260.3655446767807
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 69: 134.11615598201752
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 70: 217.53636395931244
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 71: 195.44338047504425
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 72: 122.61441653966904
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 73: 103.41260766983032
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 74: 118.76614534854889
[2024-09-12 12:47:34,029][flwr][INFO] - 		round 75: 130.09694522619247
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 76: 108.41445350646973
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 77: 91.61978089809418
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 78: 108.0238745212555
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 79: 129.7868390083313
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 80: 136.5367540717125
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 81: 128.2641777396202
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 82: 100.817018866539
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 83: 123.56397521495819
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 84: 134.3797391653061
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 85: 105.34118646383286
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 86: 126.29498064517975
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 87: 89.96103626489639
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 88: 151.06427466869354
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 89: 114.49658703804016
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 90: 162.88014024496078
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 91: 76.77149811387062
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 92: 127.63680821657181
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 93: 99.404760658741
[2024-09-12 12:47:34,030][flwr][INFO] - 		round 94: 129.50546339154243
[2024-09-12 12:47:34,031][flwr][INFO] - 		round 95: 111.01611256599426
[2024-09-12 12:47:34,031][flwr][INFO] - 		round 96: 126.65654993057251
[2024-09-12 12:47:34,031][flwr][INFO] - 		round 97: 100.30307388305664
[2024-09-12 12:47:34,031][flwr][INFO] - 		round 98: 74.95013988018036
[2024-09-12 12:47:34,031][flwr][INFO] - 		round 99: 88.22627657651901
[2024-09-12 12:47:34,031][flwr][INFO] - 		round 100: 152.77632439136505
[2024-09-12 12:47:34,031][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-09-12 12:47:34,031][flwr][INFO] - 	{'accuracy': [(1, 0.0),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (2, 0.14583333333333334),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (3, 0.0),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (4, 0.0),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (5, 0.05714285714285714),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (6, 0.875),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (7, 0.17391304347826086),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (8, 0.8),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (9, 1.0),
[2024-09-12 12:47:34,031][flwr][INFO] - 	              (10, 0.5178571428571429),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (11, 0.673469387755102),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (12, 0.0),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (13, 0.037037037037037035),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (14, 0.03125),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (15, 0.12121212121212122),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (16, 0.6551724137931034),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (17, 0.6),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (18, 0.19642857142857142),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (19, 0.0),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (20, 0.0),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (21, 0.7285714285714285),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (22, 0.3125),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (23, 0.75),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (24, 0.037037037037037035),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (25, 0.4),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (26, 0.75),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (27, 0.5714285714285714),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (28, 0.2978723404255319),
[2024-09-12 12:47:34,032][flwr][INFO] - 	              (29, 0.8695652173913043),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (30, 0.5833333333333334),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (31, 0.43333333333333335),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (32, 0.9666666666666667),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (33, 0.45),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (34, 0.0),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (35, 0.9722222222222222),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (36, 0.0392156862745098),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (37, 0.7428571428571429),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (38, 0.7076923076923077),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (39, 0.7424242424242424),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (40, 0.975),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (41, 0.75),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (42, 0.6666666666666666),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (43, 0.35294117647058826),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (44, 0.8333333333333334),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (45, 0.7368421052631579),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (46, 0.7741935483870968),
[2024-09-12 12:47:34,033][flwr][INFO] - 	              (47, 0.3684210526315789),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (48, 0.5168539325842697),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (49, 0.9),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (50, 1.0),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (51, 0.058823529411764705),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (52, 0.25),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (53, 0.9),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (54, 0.7682926829268293),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (55, 0.7647058823529411),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (56, 0.7674418604651163),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (57, 0.8153846153846154),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (58, 0.8695652173913043),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (59, 0.7096774193548387),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (60, 0.7777777777777778),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (61, 0.8333333333333334),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (62, 0.8225806451612904),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (63, 0.45454545454545453),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (64, 0.6363636363636364),
[2024-09-12 12:47:34,034][flwr][INFO] - 	              (65, 0.8051948051948052),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (66, 0.9038461538461539),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (67, 0.5892857142857143),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (68, 0.6),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (69, 0.1891891891891892),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (70, 0.1590909090909091),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (71, 0.1),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (72, 0.7745098039215687),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (73, 0.8333333333333334),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (74, 0.21621621621621623),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (75, 0.2586206896551724),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (76, 0.4140625),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (77, 0.9595959595959596),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (78, 0.21428571428571427),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (79, 1.0),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (80, 0.7536231884057971),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (81, 0.5423728813559322),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (82, 0.0),
[2024-09-12 12:47:34,035][flwr][INFO] - 	              (83, 0.7714285714285715),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (84, 0.8321678321678322),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (85, 0.9411764705882353),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (86, 0.5208333333333334),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (87, 0.7272727272727273),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (88, 0.9545454545454546),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (89, 0.9583333333333334),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (90, 1.0),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (91, 0.835820895522388),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (92, 0.3125),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (93, 0.8571428571428571),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (94, 0.8918918918918919),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (95, 0.6666666666666666),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (96, 0.4482758620689655),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (97, 0.9310344827586207),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (98, 0.8194444444444444),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (99, 0.8518518518518519),
[2024-09-12 12:47:34,036][flwr][INFO] - 	              (100, 0.391304347826087)]}
[2024-09-12 12:47:34,036][flwr][INFO] - 	History (metrics, centralized):
[2024-09-12 12:47:34,037][flwr][INFO] - 	{'accuracy': [(0, 0.10435545162233265),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (1, 0.24963460976322713),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (2, 0.2297573808827828),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (3, 0.17217187956737795),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (4, 0.1370944168371821),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (5, 0.34258988599824614),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (6, 0.49780765857936277),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (7, 0.40748319204910843),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (8, 0.34112832505115465),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (9, 0.3893598363051739),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (10, 0.4191756796258404),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (11, 0.388482899736919),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (12, 0.33528208126278863),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (13, 0.31102016954106987),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (14, 0.6170710318620286),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (15, 0.35135925168079507),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (16, 0.4717918737211342),
[2024-09-12 12:47:34,037][flwr][INFO] - 	              (17, 0.35282081262788656),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (18, 0.36451330020461853),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (19, 0.16924875767319497),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (20, 0.3440514469453376),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (21, 0.5299619994153756),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (22, 0.6199941537562116),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (23, 0.5849166910260157),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (24, 0.3925752703887752),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (25, 0.5483776673487284),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (26, 0.6296404560070155),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (27, 0.6059631686641332),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (28, 0.4539608301666179),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (29, 0.664425606547793),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (30, 0.4633148202280035),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (31, 0.2727272727272727),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (32, 0.6480561239403683),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (33, 0.5434083601286174),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (34, 0.5703010815551008),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (35, 0.3686056708564747),
[2024-09-12 12:47:34,038][flwr][INFO] - 	              (36, 0.3545746857643964),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (37, 0.4180064308681672),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (38, 0.48085355159310145),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (39, 0.5469161064016369),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (40, 0.6650102309266296),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (41, 0.6796258403975446),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (42, 0.47471499561531716),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (43, 0.36071324174218067),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (44, 0.3648056123940368),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (45, 0.7018415667933353),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (46, 0.5790704472376498),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (47, 0.5358082432037415),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (48, 0.552762350190003),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (49, 0.4042677579655072),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (50, 0.6541946799181526),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (51, 0.5732242034492838),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (52, 0.5416544869921076),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (53, 0.5624086524408067),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (54, 0.3668517977199649),
[2024-09-12 12:47:34,039][flwr][INFO] - 	              (55, 0.6080093539900614),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (56, 0.4852382344343759),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (57, 0.6474714995615317),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (58, 0.5784858228588132),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (59, 0.6416252557731658),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (60, 0.6550716164864074),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (61, 0.535223618824905),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (62, 0.5521777258111663),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (63, 0.3022508038585209),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (64, 0.4644840689856767),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (65, 0.44343759134755917),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (66, 0.6384098216895645),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (67, 0.6796258403975446),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (68, 0.26951183864367145),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (69, 0.5425314235603624),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (70, 0.3978368897983046),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (71, 0.5963168664133295),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (72, 0.6772873428821982),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (73, 0.6422098801520023),
[2024-09-12 12:47:34,040][flwr][INFO] - 	              (74, 0.6156094709149371),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (75, 0.5936860567085648),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (76, 0.5840397544577609),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (77, 0.7588424437299035),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (78, 0.6769950306927799),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (79, 0.5580239695995323),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (80, 0.5033615901783104),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (81, 0.6214557147033031),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (82, 0.7415960245542239),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (83, 0.5787781350482315),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (84, 0.5349313066354867),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (85, 0.7050570008769366),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (86, 0.5784858228588132),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (87, 0.8512130955860859),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (88, 0.5057000876936568),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (89, 0.6015784858228588),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (90, 0.5492546039169833),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (91, 0.7676118094124526),
[2024-09-12 12:47:34,041][flwr][INFO] - 	              (92, 0.6150248465361006),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (93, 0.6989184448991523),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (94, 0.6828412744811458),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (95, 0.665302543116048),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (96, 0.5451622332651271),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (97, 0.7541654486992108),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (98, 0.8129201987722888),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (99, 0.7766734872844198),
[2024-09-12 12:47:34,042][flwr][INFO] - 	              (100, 0.4375913475591932)]}
[2024-09-12 12:47:34,042][flwr][INFO] - 
