[2024-10-10 04:30:37,375][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-10-10 04:30:41,753][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'object_store_memory': 72579330048.0, 'node:115.145.172.224': 1.0, 'GPU': 1.0, 'accelerator_type:G': 1.0, 'memory': 159351770112.0, 'CPU': 256.0}
[2024-10-10 04:30:41,753][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-10-10 04:30:41,753][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 64, 'num_gpus': 0.1}
[2024-10-10 04:30:41,765][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 4 actors
[2024-10-10 04:30:41,765][flwr][INFO] - [INIT]
[2024-10-10 04:30:41,765][flwr][INFO] - Requesting initial parameters from one random client
[2024-10-10 04:30:46,202][flwr][INFO] - Received initial parameters from one random client
[2024-10-10 04:30:46,202][flwr][INFO] - Evaluating initial global parameters
[2024-10-10 04:30:54,106][flwr][INFO] - initial parameters (loss, other metrics): 225.64976382255554, {'accuracy': 0.059923998830751245}
[2024-10-10 04:30:54,107][flwr][INFO] - 
[2024-10-10 04:30:54,107][flwr][INFO] - [ROUND 1]
[2024-10-10 04:30:54,108][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:31:01,039][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:31:01,242][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-10-10 04:31:08,623][flwr][INFO] - fit progress: (1, 221.38774847984314, {'accuracy': 0.15024846536100556}, 14.51656630821526)
[2024-10-10 04:31:08,624][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:31:09,090][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:31:09,090][flwr][INFO] - 
[2024-10-10 04:31:09,090][flwr][INFO] - [ROUND 2]
[2024-10-10 04:31:09,090][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:31:11,371][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:31:19,190][flwr][INFO] - fit progress: (2, 224.09595382213593, {'accuracy': 0.09090909090909091}, 25.08341874089092)
[2024-10-10 04:31:19,191][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:31:19,813][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:31:19,813][flwr][INFO] - 
[2024-10-10 04:31:19,814][flwr][INFO] - [ROUND 3]
[2024-10-10 04:31:19,814][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:31:23,254][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:31:30,066][flwr][INFO] - fit progress: (3, 224.2349841594696, {'accuracy': 0.0914937152879275}, 35.9590501813218)
[2024-10-10 04:31:30,067][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:31:30,666][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:31:30,666][flwr][INFO] - 
[2024-10-10 04:31:30,666][flwr][INFO] - [ROUND 4]
[2024-10-10 04:31:30,666][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:31:35,298][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:31:42,326][flwr][INFO] - fit progress: (4, 220.91396236419678, {'accuracy': 0.1826951183864367}, 48.21890760399401)
[2024-10-10 04:31:42,326][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:31:42,787][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:31:42,787][flwr][INFO] - 
[2024-10-10 04:31:42,787][flwr][INFO] - [ROUND 5]
[2024-10-10 04:31:42,787][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:31:46,994][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:31:53,960][flwr][INFO] - fit progress: (5, 228.9679594039917, {'accuracy': 0.1824028061970184}, 59.853169853799045)
[2024-10-10 04:31:53,960][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:31:54,354][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:31:54,355][flwr][INFO] - 
[2024-10-10 04:31:54,355][flwr][INFO] - [ROUND 6]
[2024-10-10 04:31:54,355][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:31:59,332][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:32:06,189][flwr][INFO] - fit progress: (6, 211.9612329006195, {'accuracy': 0.2779888921368021}, 72.08199575450271)
[2024-10-10 04:32:06,190][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:32:06,282][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:32:06,283][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:32:06,466][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-10 04:32:06,467][flwr][INFO] - 
[2024-10-10 04:32:06,467][flwr][INFO] - [ROUND 7]
[2024-10-10 04:32:06,467][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:32:08,370][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:32:13,966][flwr][INFO] - fit progress: (7, 211.9305750131607, {'accuracy': 0.28383513592516807}, 79.8591777132824)
[2024-10-10 04:32:13,966][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:32:14,401][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:32:14,402][flwr][INFO] - 
[2024-10-10 04:32:14,402][flwr][INFO] - [ROUND 8]
[2024-10-10 04:32:14,402][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:32:18,194][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:32:24,100][flwr][INFO] - fit progress: (8, 213.15884268283844, {'accuracy': 0.2630809704764689}, 89.99271084275097)
[2024-10-10 04:32:24,100][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:32:24,427][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:32:24,428][flwr][INFO] - 
[2024-10-10 04:32:24,428][flwr][INFO] - [ROUND 9]
[2024-10-10 04:32:24,428][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:32:28,302][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:32:34,700][flwr][INFO] - fit progress: (9, 209.10144114494324, {'accuracy': 0.29026600409237063}, 100.5929887779057)
[2024-10-10 04:32:34,700][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:32:35,042][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:32:35,043][flwr][INFO] - 
[2024-10-10 04:32:35,043][flwr][INFO] - [ROUND 10]
[2024-10-10 04:32:35,043][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:32:37,226][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:32:44,214][flwr][INFO] - fit progress: (10, 210.8305037021637, {'accuracy': 0.2569424144986846}, 110.10659475810826)
[2024-10-10 04:32:44,215][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:32:44,834][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:32:44,835][flwr][INFO] - 
[2024-10-10 04:32:44,835][flwr][INFO] - [ROUND 11]
[2024-10-10 04:32:44,835][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:32:48,658][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:32:54,892][flwr][INFO] - fit progress: (11, 211.955104470253, {'accuracy': 0.25109617071031864}, 120.7847614036873)
[2024-10-10 04:32:54,893][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:32:55,396][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:32:55,397][flwr][INFO] - 
[2024-10-10 04:32:55,397][flwr][INFO] - [ROUND 12]
[2024-10-10 04:32:55,397][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:33:00,814][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:33:07,063][flwr][INFO] - fit progress: (12, 203.68472301959991, {'accuracy': 0.2569424144986846}, 132.95618352945894)
[2024-10-10 04:33:07,064][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:33:07,433][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:33:07,434][flwr][INFO] - 
[2024-10-10 04:33:07,434][flwr][INFO] - [ROUND 13]
[2024-10-10 04:33:07,434][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:33:16,360][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:33:22,668][flwr][INFO] - fit progress: (13, 203.70863008499146, {'accuracy': 0.24846536100555394}, 148.5615652287379)
[2024-10-10 04:33:22,669][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:33:23,075][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:33:23,075][flwr][INFO] - 
[2024-10-10 04:33:23,075][flwr][INFO] - [ROUND 14]
[2024-10-10 04:33:23,075][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:33:32,508][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:33:38,556][flwr][INFO] - fit progress: (14, 203.218292593956, {'accuracy': 0.26074247296112246}, 164.44939960632473)
[2024-10-10 04:33:38,557][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:33:39,120][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:33:39,121][flwr][INFO] - 
[2024-10-10 04:33:39,121][flwr][INFO] - [ROUND 15]
[2024-10-10 04:33:39,121][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:33:45,005][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:33:51,839][flwr][INFO] - fit progress: (15, 199.56224989891052, {'accuracy': 0.31598947676118094}, 177.73173138778657)
[2024-10-10 04:33:51,840][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:33:52,399][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:33:52,399][flwr][INFO] - 
[2024-10-10 04:33:52,399][flwr][INFO] - [ROUND 16]
[2024-10-10 04:33:52,399][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:34:02,179][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:34:08,645][flwr][INFO] - fit progress: (16, 193.11184179782867, {'accuracy': 0.32212803273896523}, 194.5378950033337)
[2024-10-10 04:34:08,645][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:34:09,020][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:34:09,020][flwr][INFO] - 
[2024-10-10 04:34:09,020][flwr][INFO] - [ROUND 17]
[2024-10-10 04:34:09,020][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:34:14,991][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:34:20,925][flwr][INFO] - fit progress: (17, 187.72225081920624, {'accuracy': 0.35866705641625257}, 206.81820266321301)
[2024-10-10 04:34:20,926][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:34:21,324][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:34:21,324][flwr][INFO] - 
[2024-10-10 04:34:21,324][flwr][INFO] - [ROUND 18]
[2024-10-10 04:34:21,325][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:34:25,938][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:34:31,946][flwr][INFO] - fit progress: (18, 190.45965158939362, {'accuracy': 0.29961999415375623}, 217.83938429597765)
[2024-10-10 04:34:31,947][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:34:32,420][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:34:32,420][flwr][INFO] - 
[2024-10-10 04:34:32,420][flwr][INFO] - [ROUND 19]
[2024-10-10 04:34:32,420][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:34:34,237][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:34:39,173][flwr][INFO] - fit progress: (19, 193.20762133598328, {'accuracy': 0.38702133878982753}, 225.0665597356856)
[2024-10-10 04:34:39,174][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:34:39,252][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:34:39,253][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:34:39,473][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-10 04:34:39,473][flwr][INFO] - 
[2024-10-10 04:34:39,473][flwr][INFO] - [ROUND 20]
[2024-10-10 04:34:39,473][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:34:43,752][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:34:49,687][flwr][INFO] - fit progress: (20, 194.2982918024063, {'accuracy': 0.287635194387606}, 235.58019511029124)
[2024-10-10 04:34:49,687][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:34:50,056][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:34:50,056][flwr][INFO] - 
[2024-10-10 04:34:50,056][flwr][INFO] - [ROUND 21]
[2024-10-10 04:34:50,056][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:34:55,939][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:35:01,617][flwr][INFO] - fit progress: (21, 179.30823075771332, {'accuracy': 0.3937445191464484}, 247.510264380835)
[2024-10-10 04:35:01,618][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:35:02,065][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:35:02,065][flwr][INFO] - 
[2024-10-10 04:35:02,065][flwr][INFO] - [ROUND 22]
[2024-10-10 04:35:02,065][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:35:02,156][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:35:02,156][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:35:05,031][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:35:10,830][flwr][INFO] - fit progress: (22, 181.60002028942108, {'accuracy': 0.4650686933645133}, 256.72268266696483)
[2024-10-10 04:35:10,830][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:35:11,207][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:35:11,208][flwr][INFO] - 
[2024-10-10 04:35:11,208][flwr][INFO] - [ROUND 23]
[2024-10-10 04:35:11,208][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:35:18,449][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:35:24,234][flwr][INFO] - fit progress: (23, 180.44283366203308, {'accuracy': 0.42852966968722594}, 270.12729637883604)
[2024-10-10 04:35:24,235][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:35:24,657][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:35:24,658][flwr][INFO] - 
[2024-10-10 04:35:24,658][flwr][INFO] - [ROUND 24]
[2024-10-10 04:35:24,658][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:35:24,747][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:35:24,748][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:35:27,565][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:35:33,138][flwr][INFO] - fit progress: (24, 179.37760365009308, {'accuracy': 0.3639286758257819}, 279.0311645967886)
[2024-10-10 04:35:33,138][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:35:33,592][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:35:33,592][flwr][INFO] - 
[2024-10-10 04:35:33,592][flwr][INFO] - [ROUND 25]
[2024-10-10 04:35:33,592][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:35:35,501][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:35:41,308][flwr][INFO] - fit progress: (25, 172.21817004680634, {'accuracy': 0.33966676410406316}, 287.2014605756849)
[2024-10-10 04:35:41,309][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:35:41,713][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:35:41,713][flwr][INFO] - 
[2024-10-10 04:35:41,713][flwr][INFO] - [ROUND 26]
[2024-10-10 04:35:41,713][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:35:45,276][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:35:50,848][flwr][INFO] - fit progress: (26, 169.89711916446686, {'accuracy': 0.5647471499561532}, 296.74062663689256)
[2024-10-10 04:35:50,848][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:35:50,937][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:35:50,937][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:35:51,161][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-10 04:35:51,162][flwr][INFO] - 
[2024-10-10 04:35:51,162][flwr][INFO] - [ROUND 27]
[2024-10-10 04:35:51,162][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:35:56,083][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:36:01,667][flwr][INFO] - fit progress: (27, 178.03484201431274, {'accuracy': 0.4805612394036831}, 307.56051799003035)
[2024-10-10 04:36:01,668][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:36:02,149][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:36:02,149][flwr][INFO] - 
[2024-10-10 04:36:02,149][flwr][INFO] - [ROUND 28]
[2024-10-10 04:36:02,150][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:36:03,868][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:36:09,215][flwr][INFO] - fit progress: (28, 188.33064544200897, {'accuracy': 0.4472376498099971}, 315.10848551336676)
[2024-10-10 04:36:09,216][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:36:09,619][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:36:09,620][flwr][INFO] - 
[2024-10-10 04:36:09,620][flwr][INFO] - [ROUND 29]
[2024-10-10 04:36:09,620][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:36:12,329][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:36:17,880][flwr][INFO] - fit progress: (29, 185.25322270393372, {'accuracy': 0.433498976907337}, 323.7728871963918)
[2024-10-10 04:36:17,880][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:36:18,248][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:36:18,248][flwr][INFO] - 
[2024-10-10 04:36:18,248][flwr][INFO] - [ROUND 30]
[2024-10-10 04:36:18,248][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:36:21,369][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:36:26,869][flwr][INFO] - fit progress: (30, 165.7203871011734, {'accuracy': 0.5065770242619118}, 332.76181709673256)
[2024-10-10 04:36:26,870][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:36:27,360][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:36:27,361][flwr][INFO] - 
[2024-10-10 04:36:27,361][flwr][INFO] - [ROUND 31]
[2024-10-10 04:36:27,361][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:36:31,467][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:36:38,076][flwr][INFO] - fit progress: (31, 173.44935178756714, {'accuracy': 0.33177433498976905}, 343.968772476539)
[2024-10-10 04:36:38,076][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:36:38,613][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:36:38,614][flwr][INFO] - 
[2024-10-10 04:36:38,614][flwr][INFO] - [ROUND 32]
[2024-10-10 04:36:38,615][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:36:47,656][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:36:54,727][flwr][INFO] - fit progress: (32, 179.71224415302277, {'accuracy': 0.31482022800350773}, 360.62047934904695)
[2024-10-10 04:36:54,728][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:36:55,267][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:36:55,268][flwr][INFO] - 
[2024-10-10 04:36:55,268][flwr][INFO] - [ROUND 33]
[2024-10-10 04:36:55,268][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:36:59,406][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:37:06,237][flwr][INFO] - fit progress: (33, 169.57053589820862, {'accuracy': 0.5375621163402514}, 372.12968414183706)
[2024-10-10 04:37:06,237][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:37:06,577][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:37:06,578][flwr][INFO] - 
[2024-10-10 04:37:06,578][flwr][INFO] - [ROUND 34]
[2024-10-10 04:37:06,578][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:37:13,772][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:37:20,554][flwr][INFO] - fit progress: (34, 173.1951493024826, {'accuracy': 0.29260450160771706}, 386.44716403912753)
[2024-10-10 04:37:20,555][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:37:21,042][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:37:21,042][flwr][INFO] - 
[2024-10-10 04:37:21,043][flwr][INFO] - [ROUND 35]
[2024-10-10 04:37:21,043][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:37:21,156][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:37:21,156][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:37:26,844][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:37:33,779][flwr][INFO] - fit progress: (35, 168.74802136421204, {'accuracy': 0.5054077755042385}, 399.67165602743626)
[2024-10-10 04:37:33,779][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:37:34,316][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:37:34,317][flwr][INFO] - 
[2024-10-10 04:37:34,317][flwr][INFO] - [ROUND 36]
[2024-10-10 04:37:34,317][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:37:38,050][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:37:44,955][flwr][INFO] - fit progress: (36, 173.518514752388, {'accuracy': 0.35983630517392573}, 410.8482924224809)
[2024-10-10 04:37:44,956][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:37:45,403][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:37:45,404][flwr][INFO] - 
[2024-10-10 04:37:45,404][flwr][INFO] - [ROUND 37]
[2024-10-10 04:37:45,404][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:37:51,937][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:37:58,707][flwr][INFO] - fit progress: (37, 175.00915658473969, {'accuracy': 0.4171294942999123}, 424.6003284053877)
[2024-10-10 04:37:58,708][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:37:59,165][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:37:59,167][flwr][INFO] - 
[2024-10-10 04:37:59,167][flwr][INFO] - [ROUND 38]
[2024-10-10 04:37:59,167][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:03,577][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:38:08,364][flwr][INFO] - fit progress: (38, 160.75060188770294, {'accuracy': 0.3966676410406314}, 434.2574278814718)
[2024-10-10 04:38:08,365][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:38:08,735][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:38:08,736][flwr][INFO] - 
[2024-10-10 04:38:08,737][flwr][INFO] - [ROUND 39]
[2024-10-10 04:38:08,737][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:11,948][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:38:17,593][flwr][INFO] - fit progress: (39, 155.72544038295746, {'accuracy': 0.5176848874598071}, 443.48642991669476)
[2024-10-10 04:38:17,595][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:38:17,969][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:38:17,969][flwr][INFO] - 
[2024-10-10 04:38:17,969][flwr][INFO] - [ROUND 40]
[2024-10-10 04:38:17,969][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:19,982][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:38:25,510][flwr][INFO] - fit progress: (40, 156.80748200416565, {'accuracy': 0.5115463314820228}, 451.40296128671616)
[2024-10-10 04:38:25,510][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:38:26,019][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:38:26,019][flwr][INFO] - 
[2024-10-10 04:38:26,019][flwr][INFO] - [ROUND 41]
[2024-10-10 04:38:26,019][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:30,736][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:38:35,408][flwr][INFO] - fit progress: (41, 147.12931632995605, {'accuracy': 0.5439929845074539}, 461.3015971761197)
[2024-10-10 04:38:35,409][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:38:35,845][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:38:35,845][flwr][INFO] - 
[2024-10-10 04:38:35,845][flwr][INFO] - [ROUND 42]
[2024-10-10 04:38:35,845][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:38,737][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:38:43,719][flwr][INFO] - fit progress: (42, 147.07235288619995, {'accuracy': 0.45308389359836304}, 469.61248884443194)
[2024-10-10 04:38:43,720][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:38:44,061][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:38:44,061][flwr][INFO] - 
[2024-10-10 04:38:44,061][flwr][INFO] - [ROUND 43]
[2024-10-10 04:38:44,062][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:44,184][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:38:44,184][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:38:45,987][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:38:51,492][flwr][INFO] - fit progress: (43, 173.0761011838913, {'accuracy': 0.3060508623209588}, 477.38469725940377)
[2024-10-10 04:38:51,492][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:38:51,931][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:38:51,931][flwr][INFO] - 
[2024-10-10 04:38:51,931][flwr][INFO] - [ROUND 44]
[2024-10-10 04:38:51,931][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:38:54,409][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:38:59,990][flwr][INFO] - fit progress: (44, 167.10890674591064, {'accuracy': 0.3294358374744227}, 485.8829791024327)
[2024-10-10 04:38:59,990][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:00,369][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:00,370][flwr][INFO] - 
[2024-10-10 04:39:00,370][flwr][INFO] - [ROUND 45]
[2024-10-10 04:39:00,370][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:39:00,481][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:39:00,482][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:39:02,669][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:39:08,247][flwr][INFO] - fit progress: (45, 156.07323586940765, {'accuracy': 0.5665010230926629}, 494.1399729019031)
[2024-10-10 04:39:08,248][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:08,719][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:08,720][flwr][INFO] - 
[2024-10-10 04:39:08,720][flwr][INFO] - [ROUND 46]
[2024-10-10 04:39:08,720][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:39:13,647][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:39:20,103][flwr][INFO] - fit progress: (46, 157.77891659736633, {'accuracy': 0.5325928091201403}, 505.99619682785124)
[2024-10-10 04:39:20,104][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:20,595][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:20,596][flwr][INFO] - 
[2024-10-10 04:39:20,596][flwr][INFO] - [ROUND 47]
[2024-10-10 04:39:20,596][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:39:25,088][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:39:30,755][flwr][INFO] - fit progress: (47, 151.25443375110626, {'accuracy': 0.5299619994153756}, 516.6483630239964)
[2024-10-10 04:39:30,756][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:31,154][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:31,154][flwr][INFO] - 
[2024-10-10 04:39:31,154][flwr][INFO] - [ROUND 48]
[2024-10-10 04:39:31,154][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:39:34,552][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:39:40,163][flwr][INFO] - fit progress: (48, 154.28739166259766, {'accuracy': 0.6293481438175972}, 526.0557665061206)
[2024-10-10 04:39:40,163][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:40,649][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:40,650][flwr][INFO] - 
[2024-10-10 04:39:40,651][flwr][INFO] - [ROUND 49]
[2024-10-10 04:39:40,651][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:39:44,368][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:39:49,976][flwr][INFO] - fit progress: (49, 156.24224865436554, {'accuracy': 0.3320666471791874}, 535.8688684431836)
[2024-10-10 04:39:49,977][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:50,368][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:50,369][flwr][INFO] - 
[2024-10-10 04:39:50,369][flwr][INFO] - [ROUND 50]
[2024-10-10 04:39:50,369][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:39:54,760][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:39:59,492][flwr][INFO] - fit progress: (50, 149.83221054077148, {'accuracy': 0.4159602455422391}, 545.3851314689964)
[2024-10-10 04:39:59,493][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:39:59,838][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:39:59,838][flwr][INFO] - 
[2024-10-10 04:39:59,838][flwr][INFO] - [ROUND 51]
[2024-10-10 04:39:59,838][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:40:03,876][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:40:09,502][flwr][INFO] - fit progress: (51, 147.50796902179718, {'accuracy': 0.38146740719087985}, 555.394706341438)
[2024-10-10 04:40:09,502][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:40:09,891][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:40:09,891][flwr][INFO] - 
[2024-10-10 04:40:09,891][flwr][INFO] - [ROUND 52]
[2024-10-10 04:40:09,891][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:40:13,671][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:40:19,818][flwr][INFO] - fit progress: (52, 140.60653603076935, {'accuracy': 0.5627009646302251}, 565.7113114409149)
[2024-10-10 04:40:19,819][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:40:20,391][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:40:20,392][flwr][INFO] - 
[2024-10-10 04:40:20,392][flwr][INFO] - [ROUND 53]
[2024-10-10 04:40:20,393][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:40:23,050][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:40:29,278][flwr][INFO] - fit progress: (53, 140.5427565574646, {'accuracy': 0.6112247880736627}, 575.1710128430277)
[2024-10-10 04:40:29,278][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:40:29,632][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:40:29,632][flwr][INFO] - 
[2024-10-10 04:40:29,632][flwr][INFO] - [ROUND 54]
[2024-10-10 04:40:29,632][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:40:32,752][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:40:38,726][flwr][INFO] - fit progress: (54, 142.54316973686218, {'accuracy': 0.5422391113709442}, 584.6186946686357)
[2024-10-10 04:40:38,726][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:40:39,288][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:40:39,288][flwr][INFO] - 
[2024-10-10 04:40:39,288][flwr][INFO] - [ROUND 55]
[2024-10-10 04:40:39,288][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:40:45,018][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:40:51,272][flwr][INFO] - fit progress: (55, 142.98137843608856, {'accuracy': 0.6843028354282373}, 597.165432353504)
[2024-10-10 04:40:51,273][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:40:51,698][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:40:51,699][flwr][INFO] - 
[2024-10-10 04:40:51,699][flwr][INFO] - [ROUND 56]
[2024-10-10 04:40:51,699][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:40:56,529][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:41:02,538][flwr][INFO] - fit progress: (56, 141.6712373495102, {'accuracy': 0.4866997953814674}, 608.430956216529)
[2024-10-10 04:41:02,539][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:41:02,996][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:41:02,997][flwr][INFO] - 
[2024-10-10 04:41:02,997][flwr][INFO] - [ROUND 57]
[2024-10-10 04:41:02,997][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:41:09,196][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:41:15,015][flwr][INFO] - fit progress: (57, 129.6907061934471, {'accuracy': 0.5662087109032446}, 620.9075673921034)
[2024-10-10 04:41:15,016][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:41:15,464][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:41:15,466][flwr][INFO] - 
[2024-10-10 04:41:15,466][flwr][INFO] - [ROUND 58]
[2024-10-10 04:41:15,467][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:41:18,371][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:41:24,959][flwr][INFO] - fit progress: (58, 142.36639761924744, {'accuracy': 0.49780765857936277}, 630.8522039875388)
[2024-10-10 04:41:24,960][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:41:25,350][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:41:25,350][flwr][INFO] - 
[2024-10-10 04:41:25,350][flwr][INFO] - [ROUND 59]
[2024-10-10 04:41:25,350][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:41:29,107][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:41:35,257][flwr][INFO] - fit progress: (59, 138.53001987934113, {'accuracy': 0.6577024261911721}, 641.1501045692712)
[2024-10-10 04:41:35,257][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:41:35,685][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:41:35,685][flwr][INFO] - 
[2024-10-10 04:41:35,685][flwr][INFO] - [ROUND 60]
[2024-10-10 04:41:35,686][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:41:35,840][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:41:35,840][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105519, ip=115.145.172.224, actor_id=52be96fec1d87a283f8cdb5d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fa54478da50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:41:42,965][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:41:49,146][flwr][INFO] - fit progress: (60, 134.5088672041893, {'accuracy': 0.5282081262788658}, 655.0392542863265)
[2024-10-10 04:41:49,147][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:41:49,812][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:41:49,812][flwr][INFO] - 
[2024-10-10 04:41:49,812][flwr][INFO] - [ROUND 61]
[2024-10-10 04:41:49,812][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:41:57,466][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:42:02,189][flwr][INFO] - fit progress: (61, 127.52428483963013, {'accuracy': 0.6685179771996492}, 668.081834603101)
[2024-10-10 04:42:02,189][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:42:02,529][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:42:02,529][flwr][INFO] - 
[2024-10-10 04:42:02,529][flwr][INFO] - [ROUND 62]
[2024-10-10 04:42:02,529][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:42:05,793][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:42:11,320][flwr][INFO] - fit progress: (62, 127.10929983854294, {'accuracy': 0.5901783104355451}, 677.2131823506206)
[2024-10-10 04:42:11,320][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:42:11,794][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:42:11,794][flwr][INFO] - 
[2024-10-10 04:42:11,795][flwr][INFO] - [ROUND 63]
[2024-10-10 04:42:11,795][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:42:11,867][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:42:11,867][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:42:14,442][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:42:20,167][flwr][INFO] - fit progress: (63, 142.99193477630615, {'accuracy': 0.602747734580532}, 686.0602834038436)
[2024-10-10 04:42:20,168][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:42:20,492][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:42:20,493][flwr][INFO] - 
[2024-10-10 04:42:20,493][flwr][INFO] - [ROUND 64]
[2024-10-10 04:42:20,493][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:42:26,748][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:42:32,729][flwr][INFO] - fit progress: (64, 121.63679152727127, {'accuracy': 0.6217480268927215}, 698.6222380809486)
[2024-10-10 04:42:32,730][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:42:33,077][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:42:33,077][flwr][INFO] - 
[2024-10-10 04:42:33,077][flwr][INFO] - [ROUND 65]
[2024-10-10 04:42:33,077][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:42:36,239][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:42:41,154][flwr][INFO] - fit progress: (65, 133.51891040802002, {'accuracy': 0.64776381175095}, 707.0472188768908)
[2024-10-10 04:42:41,154][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:42:41,716][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:42:41,716][flwr][INFO] - 
[2024-10-10 04:42:41,716][flwr][INFO] - [ROUND 66]
[2024-10-10 04:42:41,717][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:42:43,869][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:42:49,616][flwr][INFO] - fit progress: (66, 147.01972377300262, {'accuracy': 0.5931014323297281}, 715.5090868268162)
[2024-10-10 04:42:49,616][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:42:50,124][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:42:50,124][flwr][INFO] - 
[2024-10-10 04:42:50,124][flwr][INFO] - [ROUND 67]
[2024-10-10 04:42:50,124][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:42:54,863][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:00,437][flwr][INFO] - fit progress: (67, 122.82430678606033, {'accuracy': 0.6886875182695118}, 726.3306011166424)
[2024-10-10 04:43:00,438][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:00,941][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:43:00,941][flwr][INFO] - 
[2024-10-10 04:43:00,941][flwr][INFO] - [ROUND 68]
[2024-10-10 04:43:00,941][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:02,713][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:08,490][flwr][INFO] - fit progress: (68, 138.21577310562134, {'accuracy': 0.5290850628471208}, 734.3831007461995)
[2024-10-10 04:43:08,490][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:08,578][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:43:08,579][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:43:08,767][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-10 04:43:08,767][flwr][INFO] - 
[2024-10-10 04:43:08,768][flwr][INFO] - [ROUND 69]
[2024-10-10 04:43:08,768][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:12,360][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:17,902][flwr][INFO] - fit progress: (69, 136.81850910186768, {'accuracy': 0.5720549546916106}, 743.7955713104457)
[2024-10-10 04:43:17,903][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:18,381][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:43:18,382][flwr][INFO] - 
[2024-10-10 04:43:18,382][flwr][INFO] - [ROUND 70]
[2024-10-10 04:43:18,382][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:22,258][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:27,258][flwr][INFO] - fit progress: (70, 167.88732171058655, {'accuracy': 0.4162525577316574}, 753.1510459659621)
[2024-10-10 04:43:27,258][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:27,644][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:43:27,644][flwr][INFO] - 
[2024-10-10 04:43:27,644][flwr][INFO] - [ROUND 71]
[2024-10-10 04:43:27,645][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:29,751][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:35,503][flwr][INFO] - fit progress: (71, 159.73706316947937, {'accuracy': 0.4013446360713242}, 761.3964386573061)
[2024-10-10 04:43:35,504][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:35,965][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:43:35,966][flwr][INFO] - 
[2024-10-10 04:43:35,966][flwr][INFO] - [ROUND 72]
[2024-10-10 04:43:35,966][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:41,801][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:47,615][flwr][INFO] - fit progress: (72, 144.5987685918808, {'accuracy': 0.578193510669395}, 773.5076120384037)
[2024-10-10 04:43:47,615][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:48,386][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:43:48,387][flwr][INFO] - 
[2024-10-10 04:43:48,387][flwr][INFO] - [ROUND 73]
[2024-10-10 04:43:48,387][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:50,527][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:43:56,116][flwr][INFO] - fit progress: (73, 127.89634376764297, {'accuracy': 0.6471791873721134}, 782.0092087658122)
[2024-10-10 04:43:56,117][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:43:56,527][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:43:56,527][flwr][INFO] - 
[2024-10-10 04:43:56,528][flwr][INFO] - [ROUND 74]
[2024-10-10 04:43:56,528][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:43:59,556][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:44:05,207][flwr][INFO] - fit progress: (74, 132.58400070667267, {'accuracy': 0.6091786027477346}, 791.0997954411432)
[2024-10-10 04:44:05,207][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:44:05,542][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:44:05,543][flwr][INFO] - 
[2024-10-10 04:44:05,543][flwr][INFO] - [ROUND 75]
[2024-10-10 04:44:05,543][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:44:08,218][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:44:13,529][flwr][INFO] - fit progress: (75, 130.99194771051407, {'accuracy': 0.6246711487869044}, 799.4223518632352)
[2024-10-10 04:44:13,530][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:44:14,029][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:44:14,030][flwr][INFO] - 
[2024-10-10 04:44:14,030][flwr][INFO] - [ROUND 76]
[2024-10-10 04:44:14,030][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:44:17,147][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:44:23,643][flwr][INFO] - fit progress: (76, 122.94271314144135, {'accuracy': 0.6726103478515054}, 809.5358554413542)
[2024-10-10 04:44:23,644][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:44:24,361][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:44:24,362][flwr][INFO] - 
[2024-10-10 04:44:24,363][flwr][INFO] - [ROUND 77]
[2024-10-10 04:44:24,363][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:44:24,455][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:44:24,455][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105518, ip=115.145.172.224, actor_id=fabe15d03e5325d0339b899001000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fb390541a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:44:27,421][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:44:33,799][flwr][INFO] - fit progress: (77, 147.22079372406006, {'accuracy': 0.5422391113709442}, 819.6919360421598)
[2024-10-10 04:44:33,799][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:44:34,523][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:44:34,524][flwr][INFO] - 
[2024-10-10 04:44:34,524][flwr][INFO] - [ROUND 78]
[2024-10-10 04:44:34,524][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:44:43,393][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:44:50,202][flwr][INFO] - fit progress: (78, 122.48021697998047, {'accuracy': 0.6717334112832505}, 836.0952464314178)
[2024-10-10 04:44:50,203][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:44:50,696][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:44:50,697][flwr][INFO] - 
[2024-10-10 04:44:50,697][flwr][INFO] - [ROUND 79]
[2024-10-10 04:44:50,698][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:44:54,751][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:45:01,111][flwr][INFO] - fit progress: (79, 122.31975603103638, {'accuracy': 0.6410406313943291}, 847.0044728619978)
[2024-10-10 04:45:01,112][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:45:01,494][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:45:01,495][flwr][INFO] - 
[2024-10-10 04:45:01,495][flwr][INFO] - [ROUND 80]
[2024-10-10 04:45:01,496][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:45:06,755][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:45:12,899][flwr][INFO] - fit progress: (80, 134.23312610387802, {'accuracy': 0.5618240280619702}, 858.7918732073158)
[2024-10-10 04:45:12,900][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:45:13,357][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:45:13,358][flwr][INFO] - 
[2024-10-10 04:45:13,358][flwr][INFO] - [ROUND 81]
[2024-10-10 04:45:13,358][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:45:17,765][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:45:24,001][flwr][INFO] - fit progress: (81, 137.90279799699783, {'accuracy': 0.5881321251096171}, 869.8940353598446)
[2024-10-10 04:45:24,002][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:45:24,506][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:45:24,507][flwr][INFO] - 
[2024-10-10 04:45:24,508][flwr][INFO] - [ROUND 82]
[2024-10-10 04:45:24,508][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:45:31,367][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:45:37,638][flwr][INFO] - fit progress: (82, 117.41236674785614, {'accuracy': 0.6667641040631395}, 883.5308257965371)
[2024-10-10 04:45:37,639][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:45:37,995][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:45:37,996][flwr][INFO] - 
[2024-10-10 04:45:37,996][flwr][INFO] - [ROUND 83]
[2024-10-10 04:45:37,996][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:45:43,356][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:45:49,583][flwr][INFO] - fit progress: (83, 112.09464228153229, {'accuracy': 0.6582870505700088}, 895.4765507951379)
[2024-10-10 04:45:49,584][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:45:50,142][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:45:50,142][flwr][INFO] - 
[2024-10-10 04:45:50,142][flwr][INFO] - [ROUND 84]
[2024-10-10 04:45:50,142][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:45:55,255][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:46:00,829][flwr][INFO] - fit progress: (84, 108.88794308900833, {'accuracy': 0.6886875182695118}, 906.7221190780401)
[2024-10-10 04:46:00,829][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:01,335][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:01,336][flwr][INFO] - 
[2024-10-10 04:46:01,336][flwr][INFO] - [ROUND 85]
[2024-10-10 04:46:01,336][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:46:08,122][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:46:13,520][flwr][INFO] - fit progress: (85, 131.6049863100052, {'accuracy': 0.631102016954107}, 919.4128197925165)
[2024-10-10 04:46:13,520][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:14,019][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:14,019][flwr][INFO] - 
[2024-10-10 04:46:14,019][flwr][INFO] - [ROUND 86]
[2024-10-10 04:46:14,020][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:46:16,834][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:46:22,398][flwr][INFO] - fit progress: (86, 113.20124697685242, {'accuracy': 0.662379421221865}, 928.2912751007825)
[2024-10-10 04:46:22,399][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:22,843][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:22,843][flwr][INFO] - 
[2024-10-10 04:46:22,843][flwr][INFO] - [ROUND 87]
[2024-10-10 04:46:22,843][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:46:26,138][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:46:31,393][flwr][INFO] - fit progress: (87, 124.13009715080261, {'accuracy': 0.5936860567085648}, 937.2860041186213)
[2024-10-10 04:46:31,394][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:31,798][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:31,799][flwr][INFO] - 
[2024-10-10 04:46:31,799][flwr][INFO] - [ROUND 88]
[2024-10-10 04:46:31,799][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:46:36,116][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:46:41,733][flwr][INFO] - fit progress: (88, 105.20638400316238, {'accuracy': 0.6764104063139433}, 947.6258828872815)
[2024-10-10 04:46:41,733][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:42,112][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:42,113][flwr][INFO] - 
[2024-10-10 04:46:42,113][flwr][INFO] - [ROUND 89]
[2024-10-10 04:46:42,113][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:46:45,936][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:46:51,311][flwr][INFO] - fit progress: (89, 101.35397982597351, {'accuracy': 0.7100263080970477}, 957.2043902315199)
[2024-10-10 04:46:51,312][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:51,705][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:51,705][flwr][INFO] - 
[2024-10-10 04:46:51,705][flwr][INFO] - [ROUND 90]
[2024-10-10 04:46:51,705][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:46:51,773][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:46:51,773][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105520, ip=115.145.172.224, actor_id=2a83a87af76fce29aa859e5401000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f07dc391990>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:46:53,228][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-10 04:46:57,929][flwr][INFO] - fit progress: (90, 110.03945428133011, {'accuracy': 0.6360713241742181}, 963.8223817413673)
[2024-10-10 04:46:57,930][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:46:58,321][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:46:58,321][flwr][INFO] - 
[2024-10-10 04:46:58,321][flwr][INFO] - [ROUND 91]
[2024-10-10 04:46:58,321][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:05,674][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:47:10,533][flwr][INFO] - fit progress: (91, 132.3262870311737, {'accuracy': 0.5931014323297281}, 976.4257181826979)
[2024-10-10 04:47:10,533][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:47:11,069][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:47:11,070][flwr][INFO] - 
[2024-10-10 04:47:11,070][flwr][INFO] - [ROUND 92]
[2024-10-10 04:47:11,070][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:14,028][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:47:18,688][flwr][INFO] - fit progress: (92, 131.00009083747864, {'accuracy': 0.6156094709149371}, 984.5806789575145)
[2024-10-10 04:47:18,688][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:47:19,119][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:47:19,120][flwr][INFO] - 
[2024-10-10 04:47:19,120][flwr][INFO] - [ROUND 93]
[2024-10-10 04:47:19,120][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:20,972][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:47:26,527][flwr][INFO] - fit progress: (93, 114.69516783952713, {'accuracy': 0.6816720257234726}, 992.4197835922241)
[2024-10-10 04:47:26,527][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:47:26,860][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:47:26,861][flwr][INFO] - 
[2024-10-10 04:47:26,861][flwr][INFO] - [ROUND 94]
[2024-10-10 04:47:26,861][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:30,494][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:47:35,200][flwr][INFO] - fit progress: (94, 121.87960529327393, {'accuracy': 0.5466237942122186}, 1001.0927328299731)
[2024-10-10 04:47:35,200][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:47:35,571][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:47:35,571][flwr][INFO] - 
[2024-10-10 04:47:35,571][flwr][INFO] - [ROUND 95]
[2024-10-10 04:47:35,571][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:37,270][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:47:42,816][flwr][INFO] - fit progress: (95, 120.42400825023651, {'accuracy': 0.6495176848874598}, 1008.7092427974567)
[2024-10-10 04:47:42,817][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:47:42,897][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-10 04:47:42,898][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_mobilnet_poisoned/fednova_mobilnet_poisoned/client.py", line 139, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3105517, ip=115.145.172.224, actor_id=47965104a2463905ab2a92ee01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f1230371ab0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-10 04:47:43,096][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-10 04:47:43,096][flwr][INFO] - 
[2024-10-10 04:47:43,096][flwr][INFO] - [ROUND 96]
[2024-10-10 04:47:43,096][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:47,282][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:47:53,033][flwr][INFO] - fit progress: (96, 136.868008852005, {'accuracy': 0.6077170418006431}, 1018.9262906378135)
[2024-10-10 04:47:53,034][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:47:53,427][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:47:53,427][flwr][INFO] - 
[2024-10-10 04:47:53,427][flwr][INFO] - [ROUND 97]
[2024-10-10 04:47:53,428][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:47:59,365][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:48:05,476][flwr][INFO] - fit progress: (97, 115.66237354278564, {'accuracy': 0.667348728441976}, 1031.369407539256)
[2024-10-10 04:48:05,477][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:48:05,807][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:48:05,807][flwr][INFO] - 
[2024-10-10 04:48:05,807][flwr][INFO] - [ROUND 98]
[2024-10-10 04:48:05,807][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:48:08,606][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:48:14,450][flwr][INFO] - fit progress: (98, 109.79083263874054, {'accuracy': 0.724057293189126}, 1040.343548883684)
[2024-10-10 04:48:14,451][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:48:14,960][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:48:14,961][flwr][INFO] - 
[2024-10-10 04:48:14,961][flwr][INFO] - [ROUND 99]
[2024-10-10 04:48:14,961][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:48:20,879][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:48:27,006][flwr][INFO] - fit progress: (99, 130.07182383537292, {'accuracy': 0.5963168664133295}, 1052.8995698224753)
[2024-10-10 04:48:27,007][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:48:27,469][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:48:27,470][flwr][INFO] - 
[2024-10-10 04:48:27,470][flwr][INFO] - [ROUND 100]
[2024-10-10 04:48:27,470][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-10 04:48:30,724][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-10 04:48:35,517][flwr][INFO] - fit progress: (100, 137.54256570339203, {'accuracy': 0.5513007892429115}, 1061.4105404932052)
[2024-10-10 04:48:35,518][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-10 04:48:35,947][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-10 04:48:35,950][flwr][INFO] - 
[2024-10-10 04:48:35,950][flwr][INFO] - [SUMMARY]
[2024-10-10 04:48:35,950][flwr][INFO] - Run finished 100 round(s) in 1061.84s
[2024-10-10 04:48:35,953][flwr][INFO] - 	History (loss, distributed):
[2024-10-10 04:48:35,954][flwr][INFO] - 		round 1: 2.2535891650152986
[2024-10-10 04:48:35,954][flwr][INFO] - 		round 2: 3.5449518337845802
[2024-10-10 04:48:35,954][flwr][INFO] - 		round 3: 1.8067853938449512
[2024-10-10 04:48:35,954][flwr][INFO] - 		round 4: 1.9892396009885347
[2024-10-10 04:48:35,954][flwr][INFO] - 		round 5: 2.4791223866598946
[2024-10-10 04:48:35,954][flwr][INFO] - 		round 6: 1.5495848655700684
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 7: 2.280389622501705
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 8: 1.779713818005153
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 9: 1.650984764099121
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 10: 1.937288795198713
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 11: 1.6886275082218403
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 12: 2.59859832127889
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 13: 2.2647615803612604
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 14: 2.4461557008326054
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 15: 1.7429468740116467
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 16: 1.2920270294978702
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 17: 1.1653972898210798
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 18: 1.9117941558361053
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 19: 2.959304094314575
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 20: 2.326650929450989
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 21: 1.584816929272243
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 22: 2.2192187309265137
[2024-10-10 04:48:35,955][flwr][INFO] - 		round 23: 1.7142491255487715
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 24: 1.1794851885901556
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 25: 2.235318132241567
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 26: 1.0415834188461304
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 27: 1.5623702151434762
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 28: 1.6964674503245252
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 29: 1.7591556362483813
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 30: 1.6925338208675385
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 31: 1.3627307057380675
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 32: 1.1709674338499705
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 33: 1.489955371618271
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 34: 1.9678314753941126
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 35: 1.100391490591897
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 36: 2.2168399446150837
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 37: 1.1382502385548183
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 38: 1.7267277121543885
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 39: 1.4467129707336426
[2024-10-10 04:48:35,956][flwr][INFO] - 		round 40: 1.0591944366693498
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 41: 1.2797695608700024
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 42: 1.055445170402527
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 43: 1.653180059264688
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 44: 0.5652652233839035
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 45: 1.7624388180280988
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 46: 1.054156280332996
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 47: 1.6124077972612882
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 48: 1.5477430606156253
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 49: 0.8981488466262817
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 50: 0.8292496535513136
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 51: 1.7892808773938347
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 52: 1.8487639129161835
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 53: 1.6966303944587708
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 54: 1.1780315623050783
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 55: 1.5586877009447884
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 56: 1.0114159958307134
[2024-10-10 04:48:35,957][flwr][INFO] - 		round 57: 1.1339895816949697
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 58: 0.7577706782714181
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 59: 1.43763219541119
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 60: 1.4102435950879697
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 61: 1.1963167786598206
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 62: 0.8757148625389222
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 63: 0.9773823889819059
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 64: 0.8775605613535101
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 65: 0.9926430110807543
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 66: 1.1161690681026533
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 67: 1.1199955429349626
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 68: 1.1668115854263306
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 69: 1.526874294152131
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 70: 2.3019476106221024
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 71: 2.391511559486389
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 72: 3.010261795100044
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 73: 1.1312614050176408
[2024-10-10 04:48:35,958][flwr][INFO] - 		round 74: 1.819546821955088
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 75: 2.1370508383060325
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 76: 2.083382301032543
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 77: 1.911158071623908
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 78: 1.7138362399169378
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 79: 0.3961017777522405
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 80: 0.763287415539009
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 81: 1.5847588636107364
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 82: 2.7934240102767944
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 83: 0.8541890570095607
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 84: 0.9129586928374284
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 85: 1.1000692963600158
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 86: 0.9691451191902161
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 87: 0.9784753322601318
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 88: 0.27423039078712463
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 89: 0.37578519992530346
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 90: 0.38067732442100094
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 91: 1.5910702730292705
[2024-10-10 04:48:35,959][flwr][INFO] - 		round 92: 1.3454269940654437
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 93: 0.7214612364768982
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 94: 0.8204535970816741
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 95: 0.6819278597831726
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 96: 1.1844906478092587
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 97: 0.5342746150904688
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 98: 1.0363728404045105
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 99: 1.2180475305627894
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 100: 1.131707409153814
[2024-10-10 04:48:35,960][flwr][INFO] - 	History (loss, centralized):
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 0: 225.64976382255554
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 1: 221.38774847984314
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 2: 224.09595382213593
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 3: 224.2349841594696
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 4: 220.91396236419678
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 5: 228.9679594039917
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 6: 211.9612329006195
[2024-10-10 04:48:35,960][flwr][INFO] - 		round 7: 211.9305750131607
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 8: 213.15884268283844
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 9: 209.10144114494324
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 10: 210.8305037021637
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 11: 211.955104470253
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 12: 203.68472301959991
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 13: 203.70863008499146
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 14: 203.218292593956
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 15: 199.56224989891052
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 16: 193.11184179782867
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 17: 187.72225081920624
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 18: 190.45965158939362
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 19: 193.20762133598328
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 20: 194.2982918024063
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 21: 179.30823075771332
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 22: 181.60002028942108
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 23: 180.44283366203308
[2024-10-10 04:48:35,961][flwr][INFO] - 		round 24: 179.37760365009308
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 25: 172.21817004680634
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 26: 169.89711916446686
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 27: 178.03484201431274
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 28: 188.33064544200897
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 29: 185.25322270393372
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 30: 165.7203871011734
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 31: 173.44935178756714
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 32: 179.71224415302277
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 33: 169.57053589820862
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 34: 173.1951493024826
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 35: 168.74802136421204
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 36: 173.518514752388
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 37: 175.00915658473969
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 38: 160.75060188770294
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 39: 155.72544038295746
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 40: 156.80748200416565
[2024-10-10 04:48:35,962][flwr][INFO] - 		round 41: 147.12931632995605
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 42: 147.07235288619995
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 43: 173.0761011838913
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 44: 167.10890674591064
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 45: 156.07323586940765
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 46: 157.77891659736633
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 47: 151.25443375110626
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 48: 154.28739166259766
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 49: 156.24224865436554
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 50: 149.83221054077148
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 51: 147.50796902179718
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 52: 140.60653603076935
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 53: 140.5427565574646
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 54: 142.54316973686218
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 55: 142.98137843608856
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 56: 141.6712373495102
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 57: 129.6907061934471
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 58: 142.36639761924744
[2024-10-10 04:48:35,963][flwr][INFO] - 		round 59: 138.53001987934113
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 60: 134.5088672041893
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 61: 127.52428483963013
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 62: 127.10929983854294
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 63: 142.99193477630615
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 64: 121.63679152727127
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 65: 133.51891040802002
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 66: 147.01972377300262
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 67: 122.82430678606033
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 68: 138.21577310562134
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 69: 136.81850910186768
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 70: 167.88732171058655
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 71: 159.73706316947937
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 72: 144.5987685918808
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 73: 127.89634376764297
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 74: 132.58400070667267
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 75: 130.99194771051407
[2024-10-10 04:48:35,964][flwr][INFO] - 		round 76: 122.94271314144135
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 77: 147.22079372406006
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 78: 122.48021697998047
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 79: 122.31975603103638
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 80: 134.23312610387802
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 81: 137.90279799699783
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 82: 117.41236674785614
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 83: 112.09464228153229
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 84: 108.88794308900833
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 85: 131.6049863100052
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 86: 113.20124697685242
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 87: 124.13009715080261
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 88: 105.20638400316238
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 89: 101.35397982597351
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 90: 110.03945428133011
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 91: 132.3262870311737
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 92: 131.00009083747864
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 93: 114.69516783952713
[2024-10-10 04:48:35,965][flwr][INFO] - 		round 94: 121.87960529327393
[2024-10-10 04:48:35,966][flwr][INFO] - 		round 95: 120.42400825023651
[2024-10-10 04:48:35,966][flwr][INFO] - 		round 96: 136.868008852005
[2024-10-10 04:48:35,966][flwr][INFO] - 		round 97: 115.66237354278564
[2024-10-10 04:48:35,966][flwr][INFO] - 		round 98: 109.79083263874054
[2024-10-10 04:48:35,966][flwr][INFO] - 		round 99: 130.07182383537292
[2024-10-10 04:48:35,966][flwr][INFO] - 		round 100: 137.54256570339203
[2024-10-10 04:48:35,966][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-10-10 04:48:35,966][flwr][INFO] - 	{'accuracy': [(1, 0.01639344262295082),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (2, 0.0),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (3, 0.09090909090909091),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (4, 0.15384615384615385),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (5, 0.0),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (6, 0.75),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (7, 0.10869565217391304),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (8, 0.5714285714285714),
[2024-10-10 04:48:35,966][flwr][INFO] - 	              (9, 0.8),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (10, 0.35714285714285715),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (11, 0.4489795918367347),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (12, 0.0),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (13, 0.037037037037037035),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (14, 0.09375),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (15, 0.030303030303030304),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (16, 0.6551724137931034),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (17, 0.6285714285714286),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (18, 0.10714285714285714),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (19, 0.0),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (20, 0.0),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (21, 0.5714285714285714),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (22, 0.20833333333333334),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (23, 0.30357142857142855),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (24, 0.8518518518518519),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (25, 0.13333333333333333),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (26, 0.75),
[2024-10-10 04:48:35,967][flwr][INFO] - 	              (27, 0.5714285714285714),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (28, 0.574468085106383),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (29, 0.32608695652173914),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (30, 0.3333333333333333),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (31, 0.45),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (32, 0.5333333333333333),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (33, 0.7),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (34, 0.0),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (35, 0.8888888888888888),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (36, 0.0784313725490196),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (37, 0.7714285714285715),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (38, 0.27692307692307694),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (39, 0.5303030303030303),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (40, 0.85),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (41, 0.6029411764705882),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (42, 0.5333333333333333),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (43, 0.35294117647058826),
[2024-10-10 04:48:35,968][flwr][INFO] - 	              (44, 1.0),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (45, 0.3333333333333333),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (46, 0.7096774193548387),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (47, 0.4912280701754387),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (48, 0.5617977528089888),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (49, 0.7),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (50, 0.6666666666666666),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (51, 0.03529411764705882),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (52, 0.25),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (53, 0.4),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (54, 0.7804878048780488),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (55, 0.5294117647058824),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (56, 0.6046511627906976),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (57, 0.6615384615384615),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (58, 0.8695652173913043),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (59, 0.5483870967741935),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (60, 0.35185185185185186),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (61, 0.6666666666666666),
[2024-10-10 04:48:35,969][flwr][INFO] - 	              (62, 0.6935483870967742),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (63, 0.6363636363636364),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (64, 0.6363636363636364),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (65, 0.7922077922077922),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (66, 0.7403846153846154),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (67, 0.7857142857142857),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (68, 0.8),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (69, 0.43243243243243246),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (70, 0.13636363636363635),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (71, 0.05),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (72, 0.46078431372549017),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (73, 0.6388888888888888),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (74, 0.32432432432432434),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (75, 0.034482758620689655),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (76, 0.671875),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (77, 0.8787878787878788),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (78, 0.25),
[2024-10-10 04:48:35,970][flwr][INFO] - 	              (79, 1.0),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (80, 0.8115942028985508),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (81, 0.4915254237288136),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (82, 0.0),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (83, 0.7571428571428571),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (84, 0.9370629370629371),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (85, 0.6235294117647059),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (86, 0.8333333333333334),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (87, 0.9242424242424242),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (88, 0.9545454545454546),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (89, 0.9166666666666666),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (90, 0.9622641509433962),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (91, 0.4626865671641791),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (92, 0.4791666666666667),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (93, 0.8571428571428571),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (94, 0.6756756756756757),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (95, 1.0),
[2024-10-10 04:48:35,971][flwr][INFO] - 	              (96, 0.6551724137931034),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (97, 0.896551724137931),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (98, 0.75),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (99, 0.6666666666666666),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (100, 0.6304347826086957)]}
[2024-10-10 04:48:35,972][flwr][INFO] - 	History (metrics, centralized):
[2024-10-10 04:48:35,972][flwr][INFO] - 	{'accuracy': [(0, 0.059923998830751245),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (1, 0.15024846536100556),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (2, 0.09090909090909091),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (3, 0.0914937152879275),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (4, 0.1826951183864367),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (5, 0.1824028061970184),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (6, 0.2779888921368021),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (7, 0.28383513592516807),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (8, 0.2630809704764689),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (9, 0.29026600409237063),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (10, 0.2569424144986846),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (11, 0.25109617071031864),
[2024-10-10 04:48:35,972][flwr][INFO] - 	              (12, 0.2569424144986846),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (13, 0.24846536100555394),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (14, 0.26074247296112246),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (15, 0.31598947676118094),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (16, 0.32212803273896523),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (17, 0.35866705641625257),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (18, 0.29961999415375623),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (19, 0.38702133878982753),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (20, 0.287635194387606),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (21, 0.3937445191464484),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (22, 0.4650686933645133),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (23, 0.42852966968722594),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (24, 0.3639286758257819),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (25, 0.33966676410406316),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (26, 0.5647471499561532),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (27, 0.4805612394036831),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (28, 0.4472376498099971),
[2024-10-10 04:48:35,973][flwr][INFO] - 	              (29, 0.433498976907337),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (30, 0.5065770242619118),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (31, 0.33177433498976905),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (32, 0.31482022800350773),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (33, 0.5375621163402514),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (34, 0.29260450160771706),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (35, 0.5054077755042385),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (36, 0.35983630517392573),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (37, 0.4171294942999123),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (38, 0.3966676410406314),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (39, 0.5176848874598071),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (40, 0.5115463314820228),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (41, 0.5439929845074539),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (42, 0.45308389359836304),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (43, 0.3060508623209588),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (44, 0.3294358374744227),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (45, 0.5665010230926629),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (46, 0.5325928091201403),
[2024-10-10 04:48:35,974][flwr][INFO] - 	              (47, 0.5299619994153756),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (48, 0.6293481438175972),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (49, 0.3320666471791874),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (50, 0.4159602455422391),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (51, 0.38146740719087985),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (52, 0.5627009646302251),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (53, 0.6112247880736627),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (54, 0.5422391113709442),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (55, 0.6843028354282373),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (56, 0.4866997953814674),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (57, 0.5662087109032446),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (58, 0.49780765857936277),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (59, 0.6577024261911721),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (60, 0.5282081262788658),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (61, 0.6685179771996492),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (62, 0.5901783104355451),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (63, 0.602747734580532),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (64, 0.6217480268927215),
[2024-10-10 04:48:35,975][flwr][INFO] - 	              (65, 0.64776381175095),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (66, 0.5931014323297281),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (67, 0.6886875182695118),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (68, 0.5290850628471208),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (69, 0.5720549546916106),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (70, 0.4162525577316574),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (71, 0.4013446360713242),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (72, 0.578193510669395),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (73, 0.6471791873721134),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (74, 0.6091786027477346),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (75, 0.6246711487869044),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (76, 0.6726103478515054),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (77, 0.5422391113709442),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (78, 0.6717334112832505),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (79, 0.6410406313943291),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (80, 0.5618240280619702),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (81, 0.5881321251096171),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (82, 0.6667641040631395),
[2024-10-10 04:48:35,976][flwr][INFO] - 	              (83, 0.6582870505700088),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (84, 0.6886875182695118),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (85, 0.631102016954107),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (86, 0.662379421221865),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (87, 0.5936860567085648),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (88, 0.6764104063139433),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (89, 0.7100263080970477),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (90, 0.6360713241742181),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (91, 0.5931014323297281),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (92, 0.6156094709149371),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (93, 0.6816720257234726),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (94, 0.5466237942122186),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (95, 0.6495176848874598),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (96, 0.6077170418006431),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (97, 0.667348728441976),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (98, 0.724057293189126),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (99, 0.5963168664133295),
[2024-10-10 04:48:35,977][flwr][INFO] - 	              (100, 0.5513007892429115)]}
[2024-10-10 04:48:35,978][flwr][INFO] - 
