[2024-10-08 07:13:33,878][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-10-08 07:13:37,733][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'memory': 155088659456.0, 'object_store_memory': 70752282624.0, 'node:115.145.172.224': 1.0, 'CPU': 256.0, 'GPU': 5.0, 'accelerator_type:G': 1.0}
[2024-10-08 07:13:37,734][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-10-08 07:13:37,734][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 128, 'num_gpus': 0.1}
[2024-10-08 07:13:37,745][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2024-10-08 07:13:37,745][flwr][INFO] - [INIT]
[2024-10-08 07:13:37,745][flwr][INFO] - Requesting initial parameters from one random client
[2024-10-08 07:13:43,224][flwr][INFO] - Received initial parameters from one random client
[2024-10-08 07:13:43,224][flwr][INFO] - Evaluating initial global parameters
[2024-10-08 07:13:53,657][flwr][INFO] - initial parameters (loss, other metrics): 233.19008803367615, {'accuracy': 0.06664717918737212}
[2024-10-08 07:13:53,657][flwr][INFO] - 
[2024-10-08 07:13:53,657][flwr][INFO] - [ROUND 1]
[2024-10-08 07:13:53,657][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:14:08,039][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:14:08,775][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-10-08 07:14:18,809][flwr][INFO] - fit progress: (1, 411.0157964229584, {'accuracy': 0.0912014030985092}, 25.151704819872975)
[2024-10-08 07:14:18,810][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:14:20,467][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:14:20,468][flwr][INFO] - 
[2024-10-08 07:14:20,468][flwr][INFO] - [ROUND 2]
[2024-10-08 07:14:20,468][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:14:28,393][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:14:38,891][flwr][INFO] - fit progress: (2, 474.1421434879303, {'accuracy': 0.09090909090909091}, 45.23416151292622)
[2024-10-08 07:14:38,892][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:14:40,939][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:14:40,940][flwr][INFO] - 
[2024-10-08 07:14:40,940][flwr][INFO] - [ROUND 3]
[2024-10-08 07:14:40,940][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:14:48,845][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:15:00,683][flwr][INFO] - fit progress: (3, 243.3247720003128, {'accuracy': 0.17041800643086816}, 67.02564985956997)
[2024-10-08 07:15:00,684][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:15:02,554][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:15:02,554][flwr][INFO] - 
[2024-10-08 07:15:02,555][flwr][INFO] - [ROUND 4]
[2024-10-08 07:15:02,555][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:15:14,109][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:15:25,156][flwr][INFO] - fit progress: (4, 218.2811257839203, {'accuracy': 0.1824028061970184}, 91.49846476875246)
[2024-10-08 07:15:25,157][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:15:26,988][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:15:26,989][flwr][INFO] - 
[2024-10-08 07:15:26,989][flwr][INFO] - [ROUND 5]
[2024-10-08 07:15:26,989][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:15:36,711][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:15:46,973][flwr][INFO] - fit progress: (5, 211.60870611667633, {'accuracy': 0.2356036246711488}, 113.31586631760001)
[2024-10-08 07:15:46,974][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:15:48,536][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:15:48,536][flwr][INFO] - 
[2024-10-08 07:15:48,536][flwr][INFO] - [ROUND 6]
[2024-10-08 07:15:48,537][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:15:58,903][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:16:09,188][flwr][INFO] - fit progress: (6, 237.47075581550598, {'accuracy': 0.21543408360128619}, 135.53113334719092)
[2024-10-08 07:16:09,189][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:16:09,735][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:16:09,736][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:16:10,497][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-08 07:16:10,498][flwr][INFO] - 
[2024-10-08 07:16:10,498][flwr][INFO] - [ROUND 7]
[2024-10-08 07:16:10,498][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:16:22,608][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:16:33,955][flwr][INFO] - fit progress: (7, 235.10992670059204, {'accuracy': 0.25109617071031864}, 160.29769452288747)
[2024-10-08 07:16:33,956][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:16:35,473][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:16:35,474][flwr][INFO] - 
[2024-10-08 07:16:35,475][flwr][INFO] - [ROUND 8]
[2024-10-08 07:16:35,475][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:16:47,789][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:17:00,708][flwr][INFO] - fit progress: (8, 216.43549740314484, {'accuracy': 0.23677287342882197}, 187.05102105624974)
[2024-10-08 07:17:00,709][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:17:02,399][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:17:02,399][flwr][INFO] - 
[2024-10-08 07:17:02,399][flwr][INFO] - [ROUND 9]
[2024-10-08 07:17:02,399][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:17:11,559][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:17:23,644][flwr][INFO] - fit progress: (9, 217.994495511055, {'accuracy': 0.3256357790119848}, 209.98644159641117)
[2024-10-08 07:17:23,644][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:17:25,380][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:17:25,380][flwr][INFO] - 
[2024-10-08 07:17:25,380][flwr][INFO] - [ROUND 10]
[2024-10-08 07:17:25,380][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:17:35,136][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:17:46,708][flwr][INFO] - fit progress: (10, 230.22286522388458, {'accuracy': 0.19789535223618826}, 233.05050762649626)
[2024-10-08 07:17:46,708][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:17:48,754][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:17:48,754][flwr][INFO] - 
[2024-10-08 07:17:48,754][flwr][INFO] - [ROUND 11]
[2024-10-08 07:17:48,755][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:18:02,894][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:18:13,109][flwr][INFO] - fit progress: (11, 258.5099241733551, {'accuracy': 0.24349605378544284}, 259.4520954769105)
[2024-10-08 07:18:13,110][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:18:14,981][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:18:14,981][flwr][INFO] - 
[2024-10-08 07:18:14,981][flwr][INFO] - [ROUND 12]
[2024-10-08 07:18:14,982][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:18:26,470][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:18:37,087][flwr][INFO] - fit progress: (12, 548.1587145328522, {'accuracy': 0.3346974568839521}, 283.42977453023195)
[2024-10-08 07:18:37,088][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:18:38,533][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:18:38,533][flwr][INFO] - 
[2024-10-08 07:18:38,534][flwr][INFO] - [ROUND 13]
[2024-10-08 07:18:38,534][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:18:57,806][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:19:08,794][flwr][INFO] - fit progress: (13, 307.7113616466522, {'accuracy': 0.16983338205203158}, 315.1368605736643)
[2024-10-08 07:19:08,795][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:19:10,539][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:19:10,539][flwr][INFO] - 
[2024-10-08 07:19:10,539][flwr][INFO] - [ROUND 14]
[2024-10-08 07:19:10,539][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:19:27,085][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:19:37,661][flwr][INFO] - fit progress: (14, 212.33438658714294, {'accuracy': 0.2589885998246127}, 344.0039876019582)
[2024-10-08 07:19:37,662][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:19:39,269][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:19:39,269][flwr][INFO] - 
[2024-10-08 07:19:39,269][flwr][INFO] - [ROUND 15]
[2024-10-08 07:19:39,270][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:19:52,724][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:20:02,868][flwr][INFO] - fit progress: (15, 320.460476398468, {'accuracy': 0.33557439345220696}, 369.21089142467827)
[2024-10-08 07:20:02,869][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:20:04,525][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:20:04,526][flwr][INFO] - 
[2024-10-08 07:20:04,526][flwr][INFO] - [ROUND 16]
[2024-10-08 07:20:04,526][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:20:26,120][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:20:36,411][flwr][INFO] - fit progress: (16, 186.6889237165451, {'accuracy': 0.30838935983630517}, 402.75348282419145)
[2024-10-08 07:20:36,411][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:20:38,025][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:20:38,025][flwr][INFO] - 
[2024-10-08 07:20:38,025][flwr][INFO] - [ROUND 17]
[2024-10-08 07:20:38,026][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:20:53,374][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:21:03,309][flwr][INFO] - fit progress: (17, 206.57500159740448, {'accuracy': 0.3668517977199649}, 429.65180631913245)
[2024-10-08 07:21:03,310][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:21:05,060][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:21:05,060][flwr][INFO] - 
[2024-10-08 07:21:05,060][flwr][INFO] - [ROUND 18]
[2024-10-08 07:21:05,060][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:21:17,967][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:21:28,680][flwr][INFO] - fit progress: (18, 207.8744134902954, {'accuracy': 0.35632855890090614}, 455.02314668148756)
[2024-10-08 07:21:28,681][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:21:30,431][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:21:30,431][flwr][INFO] - 
[2024-10-08 07:21:30,432][flwr][INFO] - [ROUND 19]
[2024-10-08 07:21:30,433][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:21:40,409][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:21:50,590][flwr][INFO] - fit progress: (19, 255.94065475463867, {'accuracy': 0.07775504238526747}, 476.93275414872915)
[2024-10-08 07:21:50,590][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:21:50,893][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:21:50,893][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:21:51,857][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-08 07:21:51,857][flwr][INFO] - 
[2024-10-08 07:21:51,857][flwr][INFO] - [ROUND 20]
[2024-10-08 07:21:51,857][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:22:05,750][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:22:15,841][flwr][INFO] - fit progress: (20, 219.3297656774521, {'accuracy': 0.2776965799473838}, 502.18406025879085)
[2024-10-08 07:22:15,842][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:22:17,414][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:22:17,414][flwr][INFO] - 
[2024-10-08 07:22:17,415][flwr][INFO] - [ROUND 21]
[2024-10-08 07:22:17,416][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:22:39,215][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:22:49,574][flwr][INFO] - fit progress: (21, 215.59824883937836, {'accuracy': 0.24086524408067816}, 535.9173131389543)
[2024-10-08 07:22:49,575][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:22:51,495][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:22:51,495][flwr][INFO] - 
[2024-10-08 07:22:51,495][flwr][INFO] - [ROUND 22]
[2024-10-08 07:22:51,495][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:22:56,260][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:22:56,260][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:23:01,262][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:23:10,842][flwr][INFO] - fit progress: (22, 173.17717373371124, {'accuracy': 0.47149956153171585}, 557.184622737579)
[2024-10-08 07:23:10,842][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:23:12,379][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:23:12,379][flwr][INFO] - 
[2024-10-08 07:23:12,379][flwr][INFO] - [ROUND 23]
[2024-10-08 07:23:12,379][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:23:35,231][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:23:46,246][flwr][INFO] - fit progress: (23, 201.3682802915573, {'accuracy': 0.29552762350190004}, 592.5884342947975)
[2024-10-08 07:23:46,246][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:23:48,032][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:23:48,032][flwr][INFO] - 
[2024-10-08 07:23:48,032][flwr][INFO] - [ROUND 24]
[2024-10-08 07:23:48,033][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:23:53,754][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:23:53,754][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:23:59,486][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:24:11,392][flwr][INFO] - fit progress: (24, 297.80133068561554, {'accuracy': 0.3051739257527039}, 617.7343810666353)
[2024-10-08 07:24:11,392][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:24:12,949][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:24:12,950][flwr][INFO] - 
[2024-10-08 07:24:12,950][flwr][INFO] - [ROUND 25]
[2024-10-08 07:24:12,950][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:24:24,053][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:24:34,582][flwr][INFO] - fit progress: (25, 172.873042345047, {'accuracy': 0.38965214849459223}, 640.9247700814158)
[2024-10-08 07:24:34,583][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:24:36,028][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:24:36,028][flwr][INFO] - 
[2024-10-08 07:24:36,028][flwr][INFO] - [ROUND 26]
[2024-10-08 07:24:36,028][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:24:55,500][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:25:05,693][flwr][INFO] - fit progress: (26, 215.62482798099518, {'accuracy': 0.1400175387313651}, 672.0356645649299)
[2024-10-08 07:25:05,693][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:25:06,041][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:25:06,042][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:25:06,747][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-08 07:25:06,747][flwr][INFO] - 
[2024-10-08 07:25:06,748][flwr][INFO] - [ROUND 27]
[2024-10-08 07:25:06,748][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:25:21,466][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:25:32,639][flwr][INFO] - fit progress: (27, 208.19599390029907, {'accuracy': 0.27097339959076294}, 698.981378255412)
[2024-10-08 07:25:32,639][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:25:34,043][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:25:34,044][flwr][INFO] - 
[2024-10-08 07:25:34,044][flwr][INFO] - [ROUND 28]
[2024-10-08 07:25:34,044][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:25:41,320][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:25:51,509][flwr][INFO] - fit progress: (28, 234.11587631702423, {'accuracy': 0.09704764688687519}, 717.8515584077686)
[2024-10-08 07:25:51,509][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:25:53,084][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:25:53,084][flwr][INFO] - 
[2024-10-08 07:25:53,084][flwr][INFO] - [ROUND 29]
[2024-10-08 07:25:53,084][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:26:03,151][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:26:12,963][flwr][INFO] - fit progress: (29, 202.25590753555298, {'accuracy': 0.31715872551885416}, 739.3057252401486)
[2024-10-08 07:26:12,964][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:26:14,785][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:26:14,785][flwr][INFO] - 
[2024-10-08 07:26:14,786][flwr][INFO] - [ROUND 30]
[2024-10-08 07:26:14,786][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:26:30,828][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:26:41,020][flwr][INFO] - fit progress: (30, 180.54515886306763, {'accuracy': 0.3028354282373575}, 767.3630095059052)
[2024-10-08 07:26:41,021][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:26:42,572][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:26:42,572][flwr][INFO] - 
[2024-10-08 07:26:42,572][flwr][INFO] - [ROUND 31]
[2024-10-08 07:26:42,572][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:26:54,115][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:27:04,370][flwr][INFO] - fit progress: (31, 337.69500756263733, {'accuracy': 0.2092955276235019}, 790.7128374269232)
[2024-10-08 07:27:04,371][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:27:05,911][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:27:05,912][flwr][INFO] - 
[2024-10-08 07:27:05,912][flwr][INFO] - [ROUND 32]
[2024-10-08 07:27:05,912][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:27:20,366][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:27:30,766][flwr][INFO] - fit progress: (32, 185.32347345352173, {'accuracy': 0.3981292019877229}, 817.1089903023094)
[2024-10-08 07:27:30,767][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:27:32,434][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:27:32,434][flwr][INFO] - 
[2024-10-08 07:27:32,434][flwr][INFO] - [ROUND 33]
[2024-10-08 07:27:32,434][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:27:42,874][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:27:53,188][flwr][INFO] - fit progress: (33, 194.389493227005, {'accuracy': 0.22449576147325342}, 839.5310839051381)
[2024-10-08 07:27:53,189][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:27:54,937][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:27:54,938][flwr][INFO] - 
[2024-10-08 07:27:54,938][flwr][INFO] - [ROUND 34]
[2024-10-08 07:27:54,938][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:28:12,541][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:28:22,482][flwr][INFO] - fit progress: (34, 186.27762496471405, {'accuracy': 0.4016369482607425}, 868.8252820791677)
[2024-10-08 07:28:22,483][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:28:23,811][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:28:23,811][flwr][INFO] - 
[2024-10-08 07:28:23,811][flwr][INFO] - [ROUND 35]
[2024-10-08 07:28:23,812][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:28:28,902][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:28:28,903][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:28:34,075][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:28:44,376][flwr][INFO] - fit progress: (35, 210.85348737239838, {'accuracy': 0.22011107863197896}, 890.7185295149684)
[2024-10-08 07:28:44,376][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:28:45,900][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:28:45,900][flwr][INFO] - 
[2024-10-08 07:28:45,900][flwr][INFO] - [ROUND 36]
[2024-10-08 07:28:45,900][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:28:55,359][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:29:05,443][flwr][INFO] - fit progress: (36, 215.84871411323547, {'accuracy': 0.20637240572931892}, 911.7859506057575)
[2024-10-08 07:29:05,444][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:29:06,834][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:29:06,834][flwr][INFO] - 
[2024-10-08 07:29:06,834][flwr][INFO] - [ROUND 37]
[2024-10-08 07:29:06,834][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:29:23,268][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:29:33,931][flwr][INFO] - fit progress: (37, 291.5173964500427, {'accuracy': 0.20228003507746273}, 940.2739715026692)
[2024-10-08 07:29:33,932][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:29:35,386][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:29:35,386][flwr][INFO] - 
[2024-10-08 07:29:35,386][flwr][INFO] - [ROUND 38]
[2024-10-08 07:29:35,386][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:29:47,580][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:29:58,182][flwr][INFO] - fit progress: (38, 204.0523053407669, {'accuracy': 0.25051154633148204}, 964.5248567303643)
[2024-10-08 07:29:58,183][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:29:59,832][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:29:59,833][flwr][INFO] - 
[2024-10-08 07:29:59,833][flwr][INFO] - [ROUND 39]
[2024-10-08 07:29:59,833][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:30:12,368][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:30:22,331][flwr][INFO] - fit progress: (39, 210.67329514026642, {'accuracy': 0.22946506869336453}, 988.6733742766082)
[2024-10-08 07:30:22,331][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:30:24,075][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:30:24,076][flwr][INFO] - 
[2024-10-08 07:30:24,076][flwr][INFO] - [ROUND 40]
[2024-10-08 07:30:24,076][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:30:34,823][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:30:45,222][flwr][INFO] - fit progress: (40, 193.0704047679901, {'accuracy': 0.34726688102893893}, 1011.5643361387774)
[2024-10-08 07:30:45,222][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:30:46,682][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:30:46,682][flwr][INFO] - 
[2024-10-08 07:30:46,683][flwr][INFO] - [ROUND 41]
[2024-10-08 07:30:46,683][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:31:03,493][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:31:14,053][flwr][INFO] - fit progress: (41, 180.00271809101105, {'accuracy': 0.33586670564162524}, 1040.3961032461375)
[2024-10-08 07:31:14,054][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:31:15,954][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:31:15,954][flwr][INFO] - 
[2024-10-08 07:31:15,955][flwr][INFO] - [ROUND 42]
[2024-10-08 07:31:15,955][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:31:26,575][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:31:36,997][flwr][INFO] - fit progress: (42, 191.90782856941223, {'accuracy': 0.4191756796258404}, 1063.3402683669701)
[2024-10-08 07:31:36,998][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:31:38,706][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:31:38,706][flwr][INFO] - 
[2024-10-08 07:31:38,706][flwr][INFO] - [ROUND 43]
[2024-10-08 07:31:38,707][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:31:41,224][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:31:41,225][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:31:50,037][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:32:00,891][flwr][INFO] - fit progress: (43, 205.9418717622757, {'accuracy': 0.3525285004384683}, 1087.2334281988442)
[2024-10-08 07:32:00,891][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:32:02,375][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:32:02,375][flwr][INFO] - 
[2024-10-08 07:32:02,376][flwr][INFO] - [ROUND 44]
[2024-10-08 07:32:02,376][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:32:16,262][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:32:26,886][flwr][INFO] - fit progress: (44, 179.0502725839615, {'accuracy': 0.3566208710903245}, 1113.2283732984215)
[2024-10-08 07:32:26,886][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:32:28,267][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:32:28,267][flwr][INFO] - 
[2024-10-08 07:32:28,267][flwr][INFO] - [ROUND 45]
[2024-10-08 07:32:28,268][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:32:32,688][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:32:32,689][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:32:34,478][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:32:44,048][flwr][INFO] - fit progress: (45, 200.88563859462738, {'accuracy': 0.35632855890090614}, 1130.3906212560833)
[2024-10-08 07:32:44,049][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:32:45,684][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:32:45,685][flwr][INFO] - 
[2024-10-08 07:32:45,686][flwr][INFO] - [ROUND 46]
[2024-10-08 07:32:45,686][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:32:59,136][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:33:09,226][flwr][INFO] - fit progress: (46, 201.44655096530914, {'accuracy': 0.3121894182987431}, 1155.5688069825992)
[2024-10-08 07:33:09,226][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:33:10,759][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:33:10,759][flwr][INFO] - 
[2024-10-08 07:33:10,759][flwr][INFO] - [ROUND 47]
[2024-10-08 07:33:10,759][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:33:27,818][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:33:38,042][flwr][INFO] - fit progress: (47, 168.60728979110718, {'accuracy': 0.33820520315697167}, 1184.3845485690981)
[2024-10-08 07:33:38,042][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:33:39,564][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:33:39,565][flwr][INFO] - 
[2024-10-08 07:33:39,565][flwr][INFO] - [ROUND 48]
[2024-10-08 07:33:39,565][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:33:49,696][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:34:00,485][flwr][INFO] - fit progress: (48, 182.5887041091919, {'accuracy': 0.43379128909675535}, 1206.827618171461)
[2024-10-08 07:34:00,485][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:34:02,207][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:34:02,207][flwr][INFO] - 
[2024-10-08 07:34:02,207][flwr][INFO] - [ROUND 49]
[2024-10-08 07:34:02,207][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:34:11,587][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:34:22,282][flwr][INFO] - fit progress: (49, 502.69821763038635, {'accuracy': 0.2850043846828413}, 1228.6252252524719)
[2024-10-08 07:34:22,283][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:34:23,786][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:34:23,786][flwr][INFO] - 
[2024-10-08 07:34:23,787][flwr][INFO] - [ROUND 50]
[2024-10-08 07:34:23,787][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:34:38,927][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:34:49,078][flwr][INFO] - fit progress: (50, 170.68620491027832, {'accuracy': 0.5036539023677288}, 1255.4204132175073)
[2024-10-08 07:34:49,078][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:34:50,666][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:34:50,666][flwr][INFO] - 
[2024-10-08 07:34:50,666][flwr][INFO] - [ROUND 51]
[2024-10-08 07:34:50,666][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:35:02,430][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:35:12,352][flwr][INFO] - fit progress: (51, 194.9308898448944, {'accuracy': 0.388482899736919}, 1278.6946676867083)
[2024-10-08 07:35:12,352][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:35:14,317][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:35:14,318][flwr][INFO] - 
[2024-10-08 07:35:14,318][flwr][INFO] - [ROUND 52]
[2024-10-08 07:35:14,318][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:35:24,337][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:35:34,467][flwr][INFO] - fit progress: (52, 202.84993958473206, {'accuracy': 0.3925752703887752}, 1300.8097626678646)
[2024-10-08 07:35:34,468][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:35:35,887][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:35:35,888][flwr][INFO] - 
[2024-10-08 07:35:35,888][flwr][INFO] - [ROUND 53]
[2024-10-08 07:35:35,888][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:35:43,563][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:35:53,731][flwr][INFO] - fit progress: (53, 202.16950845718384, {'accuracy': 0.2554808535515931}, 1320.0738441981375)
[2024-10-08 07:35:53,731][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:35:55,150][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:35:55,150][flwr][INFO] - 
[2024-10-08 07:35:55,150][flwr][INFO] - [ROUND 54]
[2024-10-08 07:35:55,150][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:36:05,039][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:36:15,313][flwr][INFO] - fit progress: (54, 344.9373936653137, {'accuracy': 0.3291435252850044}, 1341.6555503122509)
[2024-10-08 07:36:15,314][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:36:17,232][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:36:17,233][flwr][INFO] - 
[2024-10-08 07:36:17,233][flwr][INFO] - [ROUND 55]
[2024-10-08 07:36:17,233][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:36:30,610][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:36:40,992][flwr][INFO] - fit progress: (55, 219.88135087490082, {'accuracy': 0.2619117217187957}, 1367.3348092967644)
[2024-10-08 07:36:40,992][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:36:42,490][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:36:42,491][flwr][INFO] - 
[2024-10-08 07:36:42,491][flwr][INFO] - [ROUND 56]
[2024-10-08 07:36:42,491][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:36:55,727][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:37:05,390][flwr][INFO] - fit progress: (56, 226.15913677215576, {'accuracy': 0.31335866705641624}, 1391.7327487999573)
[2024-10-08 07:37:05,390][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:37:07,060][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:37:07,060][flwr][INFO] - 
[2024-10-08 07:37:07,060][flwr][INFO] - [ROUND 57]
[2024-10-08 07:37:07,060][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:37:19,295][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:37:29,602][flwr][INFO] - fit progress: (57, 175.70326709747314, {'accuracy': 0.3466822566501023}, 1415.945093434304)
[2024-10-08 07:37:29,603][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:37:31,313][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:37:31,313][flwr][INFO] - 
[2024-10-08 07:37:31,313][flwr][INFO] - [ROUND 58]
[2024-10-08 07:37:31,313][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:37:40,172][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:37:50,421][flwr][INFO] - fit progress: (58, 197.66745495796204, {'accuracy': 0.4329143525285004}, 1436.7643505511805)
[2024-10-08 07:37:50,422][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:37:51,931][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:37:51,932][flwr][INFO] - 
[2024-10-08 07:37:51,932][flwr][INFO] - [ROUND 59]
[2024-10-08 07:37:51,932][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:38:03,634][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:38:13,369][flwr][INFO] - fit progress: (59, 227.7663698196411, {'accuracy': 0.22712657117801813}, 1459.711390959099)
[2024-10-08 07:38:13,369][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:38:14,872][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:38:14,872][flwr][INFO] - 
[2024-10-08 07:38:14,872][flwr][INFO] - [ROUND 60]
[2024-10-08 07:38:14,873][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:38:22,490][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:38:22,490][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:38:31,667][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:38:41,485][flwr][INFO] - fit progress: (60, 152.42790293693542, {'accuracy': 0.49722303420052616}, 1487.827876523137)
[2024-10-08 07:38:41,486][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:38:42,990][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:38:42,990][flwr][INFO] - 
[2024-10-08 07:38:42,990][flwr][INFO] - [ROUND 61]
[2024-10-08 07:38:42,990][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:38:59,977][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:39:09,570][flwr][INFO] - fit progress: (61, 193.7183976173401, {'accuracy': 0.34726688102893893}, 1515.9124952508137)
[2024-10-08 07:39:09,570][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:39:10,961][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:39:10,961][flwr][INFO] - 
[2024-10-08 07:39:10,961][flwr][INFO] - [ROUND 62]
[2024-10-08 07:39:10,961][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:39:23,215][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:39:33,553][flwr][INFO] - fit progress: (62, 175.20003056526184, {'accuracy': 0.36100555393159894}, 1539.895392684266)
[2024-10-08 07:39:33,554][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:39:35,369][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:39:35,370][flwr][INFO] - 
[2024-10-08 07:39:35,371][flwr][INFO] - [ROUND 63]
[2024-10-08 07:39:35,371][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:39:35,767][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:39:35,767][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:39:46,128][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:39:56,168][flwr][INFO] - fit progress: (63, 230.11346077919006, {'accuracy': 0.21543408360128619}, 1562.510377747938)
[2024-10-08 07:39:56,168][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:39:57,435][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:39:57,435][flwr][INFO] - 
[2024-10-08 07:39:57,436][flwr][INFO] - [ROUND 64]
[2024-10-08 07:39:57,436][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:40:12,341][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:40:23,004][flwr][INFO] - fit progress: (64, 199.64166796207428, {'accuracy': 0.40192926045016075}, 1589.3470181897283)
[2024-10-08 07:40:23,005][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:40:24,304][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:40:24,305][flwr][INFO] - 
[2024-10-08 07:40:24,305][flwr][INFO] - [ROUND 65]
[2024-10-08 07:40:24,305][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:40:36,738][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:40:47,084][flwr][INFO] - fit progress: (65, 225.71219110488892, {'accuracy': 0.3259280912014031}, 1613.4272443018854)
[2024-10-08 07:40:47,085][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:40:48,802][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:40:48,802][flwr][INFO] - 
[2024-10-08 07:40:48,802][flwr][INFO] - [ROUND 66]
[2024-10-08 07:40:48,802][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:41:01,127][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:41:11,803][flwr][INFO] - fit progress: (66, 201.5156533718109, {'accuracy': 0.35983630517392573}, 1638.145844342187)
[2024-10-08 07:41:11,803][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:41:13,730][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:41:13,731][flwr][INFO] - 
[2024-10-08 07:41:13,731][flwr][INFO] - [ROUND 67]
[2024-10-08 07:41:13,731][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:41:26,472][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:41:36,476][flwr][INFO] - fit progress: (67, 178.68467378616333, {'accuracy': 0.40397544577608885}, 1662.8192560197785)
[2024-10-08 07:41:36,477][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:41:37,849][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:41:37,850][flwr][INFO] - 
[2024-10-08 07:41:37,850][flwr][INFO] - [ROUND 68]
[2024-10-08 07:41:37,850][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:41:46,235][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:41:56,243][flwr][INFO] - fit progress: (68, 482.5349431037903, {'accuracy': 0.22712657117801813}, 1682.5857935976237)
[2024-10-08 07:41:56,243][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:41:56,628][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:41:56,628][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:41:57,304][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-08 07:41:57,304][flwr][INFO] - 
[2024-10-08 07:41:57,304][flwr][INFO] - [ROUND 69]
[2024-10-08 07:41:57,305][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:42:07,187][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:42:17,328][flwr][INFO] - fit progress: (69, 166.46935415267944, {'accuracy': 0.39637532885121307}, 1703.671276238747)
[2024-10-08 07:42:17,329][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:42:18,829][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:42:18,830][flwr][INFO] - 
[2024-10-08 07:42:18,830][flwr][INFO] - [ROUND 70]
[2024-10-08 07:42:18,830][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:42:27,843][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:42:39,085][flwr][INFO] - fit progress: (70, 319.14126420021057, {'accuracy': 0.3665594855305466}, 1725.4282261915505)
[2024-10-08 07:42:39,086][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:42:40,446][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:42:40,446][flwr][INFO] - 
[2024-10-08 07:42:40,446][flwr][INFO] - [ROUND 71]
[2024-10-08 07:42:40,446][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:42:49,370][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:42:59,906][flwr][INFO] - fit progress: (71, 241.59485483169556, {'accuracy': 0.5390236772873429}, 1746.2491221958771)
[2024-10-08 07:42:59,907][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:43:01,540][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:43:01,541][flwr][INFO] - 
[2024-10-08 07:43:01,541][flwr][INFO] - [ROUND 72]
[2024-10-08 07:43:01,541][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:43:22,999][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:43:33,089][flwr][INFO] - fit progress: (72, 193.74092876911163, {'accuracy': 0.2972814966384098}, 1779.4315013838932)
[2024-10-08 07:43:33,089][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:43:34,924][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:43:34,924][flwr][INFO] - 
[2024-10-08 07:43:34,925][flwr][INFO] - [ROUND 73]
[2024-10-08 07:43:34,925][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:43:42,308][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:43:52,546][flwr][INFO] - fit progress: (73, 154.2864362001419, {'accuracy': 0.5442852966968723}, 1798.8887714939192)
[2024-10-08 07:43:52,547][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:43:54,048][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:43:54,048][flwr][INFO] - 
[2024-10-08 07:43:54,048][flwr][INFO] - [ROUND 74]
[2024-10-08 07:43:54,049][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:44:02,357][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:44:12,410][flwr][INFO] - fit progress: (74, 157.92352676391602, {'accuracy': 0.44606840105232387}, 1818.7527859201655)
[2024-10-08 07:44:12,410][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:44:14,120][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:44:14,120][flwr][INFO] - 
[2024-10-08 07:44:14,120][flwr][INFO] - [ROUND 75]
[2024-10-08 07:44:14,120][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:44:23,266][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:44:33,539][flwr][INFO] - fit progress: (75, 193.75431966781616, {'accuracy': 0.3668517977199649}, 1839.8819876555353)
[2024-10-08 07:44:33,540][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:44:35,038][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:44:35,038][flwr][INFO] - 
[2024-10-08 07:44:35,038][flwr][INFO] - [ROUND 76]
[2024-10-08 07:44:35,038][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:44:44,951][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:44:55,293][flwr][INFO] - fit progress: (76, 185.12351644039154, {'accuracy': 0.4370067231803566}, 1861.6360743818805)
[2024-10-08 07:44:55,294][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:44:57,027][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:44:57,028][flwr][INFO] - 
[2024-10-08 07:44:57,028][flwr][INFO] - [ROUND 77]
[2024-10-08 07:44:57,028][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:44:57,407][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:44:57,407][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:45:05,483][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:45:15,630][flwr][INFO] - fit progress: (77, 187.90618526935577, {'accuracy': 0.467699503069278}, 1881.973037738353)
[2024-10-08 07:45:15,631][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:45:17,389][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:45:17,389][flwr][INFO] - 
[2024-10-08 07:45:17,390][flwr][INFO] - [ROUND 78]
[2024-10-08 07:45:17,390][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:45:34,173][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:45:44,315][flwr][INFO] - fit progress: (78, 147.83130145072937, {'accuracy': 0.5048231511254019}, 1910.657453443855)
[2024-10-08 07:45:44,316][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:45:45,986][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:45:45,986][flwr][INFO] - 
[2024-10-08 07:45:45,987][flwr][INFO] - [ROUND 79]
[2024-10-08 07:45:45,987][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:45:55,234][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:46:05,324][flwr][INFO] - fit progress: (79, 157.95090174674988, {'accuracy': 0.5141771411867875}, 1931.667297991924)
[2024-10-08 07:46:05,325][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:46:06,830][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:46:06,830][flwr][INFO] - 
[2024-10-08 07:46:06,830][flwr][INFO] - [ROUND 80]
[2024-10-08 07:46:06,831][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:46:19,539][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:46:29,621][flwr][INFO] - fit progress: (80, 179.0729079246521, {'accuracy': 0.5211926337328266}, 1955.9643358094618)
[2024-10-08 07:46:29,622][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:46:31,386][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:46:31,386][flwr][INFO] - 
[2024-10-08 07:46:31,386][flwr][INFO] - [ROUND 81]
[2024-10-08 07:46:31,386][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:46:40,899][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:46:51,473][flwr][INFO] - fit progress: (81, 177.16704607009888, {'accuracy': 0.4717918737211342}, 1977.8154469244182)
[2024-10-08 07:46:51,474][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:46:53,165][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:46:53,165][flwr][INFO] - 
[2024-10-08 07:46:53,165][flwr][INFO] - [ROUND 82]
[2024-10-08 07:46:53,165][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:47:09,299][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:47:19,474][flwr][INFO] - fit progress: (82, 163.0197932124138, {'accuracy': 0.5390236772873429}, 2005.8170238984749)
[2024-10-08 07:47:19,475][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:47:21,011][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:47:21,012][flwr][INFO] - 
[2024-10-08 07:47:21,012][flwr][INFO] - [ROUND 83]
[2024-10-08 07:47:21,012][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:47:36,348][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:47:46,604][flwr][INFO] - fit progress: (83, 148.8639082312584, {'accuracy': 0.4644840689856767}, 2032.9471492357552)
[2024-10-08 07:47:46,605][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:47:48,100][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:47:48,101][flwr][INFO] - 
[2024-10-08 07:47:48,101][flwr][INFO] - [ROUND 84]
[2024-10-08 07:47:48,101][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:48:02,233][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:48:12,556][flwr][INFO] - fit progress: (84, 195.29176437854767, {'accuracy': 0.2320958783981292}, 2058.899219756946)
[2024-10-08 07:48:12,557][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:48:14,513][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:48:14,513][flwr][INFO] - 
[2024-10-08 07:48:14,513][flwr][INFO] - [ROUND 85]
[2024-10-08 07:48:14,514][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:48:35,912][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:48:45,963][flwr][INFO] - fit progress: (85, 148.98852372169495, {'accuracy': 0.5007307804735458}, 2092.3059622719884)
[2024-10-08 07:48:45,964][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:48:47,696][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:48:47,696][flwr][INFO] - 
[2024-10-08 07:48:47,696][flwr][INFO] - [ROUND 86]
[2024-10-08 07:48:47,696][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:49:01,604][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:49:12,055][flwr][INFO] - fit progress: (86, 160.87465274333954, {'accuracy': 0.40543700672318034}, 2118.3981963051483)
[2024-10-08 07:49:12,056][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:49:13,584][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:49:13,585][flwr][INFO] - 
[2024-10-08 07:49:13,585][flwr][INFO] - [ROUND 87]
[2024-10-08 07:49:13,585][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:49:26,103][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:49:36,617][flwr][INFO] - fit progress: (87, 145.6399712562561, {'accuracy': 0.5273311897106109}, 2142.9599102688953)
[2024-10-08 07:49:36,618][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:49:38,081][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:49:38,081][flwr][INFO] - 
[2024-10-08 07:49:38,081][flwr][INFO] - [ROUND 88]
[2024-10-08 07:49:38,082][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:49:48,299][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:49:58,994][flwr][INFO] - fit progress: (88, 263.08507919311523, {'accuracy': 0.3572054954691611}, 2165.3363596182317)
[2024-10-08 07:49:58,994][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:50:00,462][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:50:00,462][flwr][INFO] - 
[2024-10-08 07:50:00,463][flwr][INFO] - [ROUND 89]
[2024-10-08 07:50:00,463][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:50:14,067][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:50:23,975][flwr][INFO] - fit progress: (89, 147.65157169103622, {'accuracy': 0.4758842443729904}, 2190.317681306973)
[2024-10-08 07:50:23,975][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:50:25,568][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:50:25,569][flwr][INFO] - 
[2024-10-08 07:50:25,569][flwr][INFO] - [ROUND 90]
[2024-10-08 07:50:25,570][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:50:25,890][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:50:25,891][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551279, ip=115.145.172.224, actor_id=b2bcacd16087267524c91fa601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0c68675a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:50:32,464][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-08 07:50:42,601][flwr][INFO] - fit progress: (90, 178.26862013339996, {'accuracy': 0.41011400175387314}, 2208.9437930593267)
[2024-10-08 07:50:42,601][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:50:44,211][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:50:44,211][flwr][INFO] - 
[2024-10-08 07:50:44,211][flwr][INFO] - [ROUND 91]
[2024-10-08 07:50:44,211][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:51:13,256][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:51:23,157][flwr][INFO] - fit progress: (91, 134.89477860927582, {'accuracy': 0.529377375036539}, 2249.4997454034165)
[2024-10-08 07:51:23,158][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:51:25,049][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:51:25,049][flwr][INFO] - 
[2024-10-08 07:51:25,049][flwr][INFO] - [ROUND 92]
[2024-10-08 07:51:25,050][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:51:41,264][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:51:51,407][flwr][INFO] - fit progress: (92, 170.6914176940918, {'accuracy': 0.3683133586670564}, 2277.7497668899596)
[2024-10-08 07:51:51,407][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:51:52,943][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:51:52,943][flwr][INFO] - 
[2024-10-08 07:51:52,943][flwr][INFO] - [ROUND 93]
[2024-10-08 07:51:52,944][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:52:02,312][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:52:12,005][flwr][INFO] - fit progress: (93, 150.86507630348206, {'accuracy': 0.4884536685179772}, 2298.3478321079165)
[2024-10-08 07:52:12,005][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:52:13,437][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:52:13,438][flwr][INFO] - 
[2024-10-08 07:52:13,438][flwr][INFO] - [ROUND 94]
[2024-10-08 07:52:13,438][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:52:25,453][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:52:35,710][flwr][INFO] - fit progress: (94, 163.85608732700348, {'accuracy': 0.5913475591932184}, 2322.0529200639576)
[2024-10-08 07:52:35,711][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:52:37,207][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:52:37,207][flwr][INFO] - 
[2024-10-08 07:52:37,208][flwr][INFO] - [ROUND 95]
[2024-10-08 07:52:37,208][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:52:46,994][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:52:57,361][flwr][INFO] - fit progress: (95, 223.52735781669617, {'accuracy': 0.278865828705057}, 2343.7043421771377)
[2024-10-08 07:52:57,362][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:52:57,707][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-08 07:52:57,707][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_resnet101_poisoned/fedavg_resnet101_poisoned/client.py", line 117, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=1551280, ip=115.145.172.224, actor_id=3ae6e8a02276b20b3e7437e201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f417077d9f0>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-08 07:52:58,826][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-08 07:52:58,827][flwr][INFO] - 
[2024-10-08 07:52:58,827][flwr][INFO] - [ROUND 96]
[2024-10-08 07:52:58,828][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:53:14,144][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:53:24,473][flwr][INFO] - fit progress: (96, 193.33541190624237, {'accuracy': 0.34726688102893893}, 2370.815798313357)
[2024-10-08 07:53:24,474][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:53:26,207][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:53:26,208][flwr][INFO] - 
[2024-10-08 07:53:26,208][flwr][INFO] - [ROUND 97]
[2024-10-08 07:53:26,208][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:53:43,426][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:53:53,727][flwr][INFO] - fit progress: (97, 142.98028898239136, {'accuracy': 0.5162233265127156}, 2400.069644984789)
[2024-10-08 07:53:53,727][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:53:55,235][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:53:55,236][flwr][INFO] - 
[2024-10-08 07:53:55,236][flwr][INFO] - [ROUND 98]
[2024-10-08 07:53:55,236][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:54:07,263][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:54:17,560][flwr][INFO] - fit progress: (98, 111.64086282253265, {'accuracy': 0.5726395790704473}, 2423.903079792857)
[2024-10-08 07:54:17,561][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:54:19,026][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:54:19,027][flwr][INFO] - 
[2024-10-08 07:54:19,027][flwr][INFO] - [ROUND 99]
[2024-10-08 07:54:19,027][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:54:35,504][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:54:45,651][flwr][INFO] - fit progress: (99, 168.52499568462372, {'accuracy': 0.5828705057000877}, 2451.994047647342)
[2024-10-08 07:54:45,652][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:54:47,394][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:54:47,395][flwr][INFO] - 
[2024-10-08 07:54:47,395][flwr][INFO] - [ROUND 100]
[2024-10-08 07:54:47,395][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-08 07:55:00,999][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-08 07:55:11,126][flwr][INFO] - fit progress: (100, 181.8194831609726, {'accuracy': 0.3762057877813505}, 2477.4690960124135)
[2024-10-08 07:55:11,127][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-08 07:55:12,739][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-08 07:55:12,745][flwr][INFO] - 
[2024-10-08 07:55:12,745][flwr][INFO] - [SUMMARY]
[2024-10-08 07:55:12,745][flwr][INFO] - Run finished 100 round(s) in 2479.08s
[2024-10-08 07:55:12,749][flwr][INFO] - 	History (loss, distributed):
[2024-10-08 07:55:12,749][flwr][INFO] - 		round 1: 5.75896204104189
[2024-10-08 07:55:12,749][flwr][INFO] - 		round 2: 8.185931265354156
[2024-10-08 07:55:12,749][flwr][INFO] - 		round 3: 1.1638733582063154
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 4: 2.2067475135509786
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 5: 2.080625445502145
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 6: 1.4848703145980835
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 7: 2.8926579395066137
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 8: 1.8953646421432495
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 9: 1.8497030973434447
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 10: 2.0127701929637363
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 11: 2.168596987821618
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 12: 8.45272445678711
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 13: 4.139789934511538
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 14: 2.256446536630392
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 15: 2.748850556937131
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 16: 1.384730154070361
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 17: 1.6075836420059204
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 18: 2.179727239268167
[2024-10-08 07:55:12,750][flwr][INFO] - 		round 19: 6.1929030418396
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 20: 2.5012394309043886
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 21: 1.9616938284465244
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 22: 2.184348081549009
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 23: 1.8760896921157837
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 24: 2.5601350466410318
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 25: 2.550696516036987
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 26: 1.4931432008743286
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 27: 1.9670411518641882
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 28: 2.0762072877681
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 29: 1.932643895563872
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 30: 2.0493741035461426
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 31: 2.1752357363700865
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 32: 1.5229934314886728
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 33: 1.5162272691726684
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 34: 2.299500976290022
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 35: 1.357025020652347
[2024-10-08 07:55:12,751][flwr][INFO] - 		round 36: 2.2383554262273453
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 37: 1.8721004690442766
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 38: 1.7529205285585843
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 39: 1.2917400273409756
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 40: 1.4032885879278183
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 41: 1.7823895005618824
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 42: 0.9848059594631196
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 43: 2.5431472553926358
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 44: 1.1448371410369873
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 45: 2.037876712648492
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 46: 1.952775397608357
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 47: 2.3521660503588224
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 48: 1.624833101636908
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 49: 1.57160325050354
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 50: 0.5485060347451104
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 51: 1.9687100480584536
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 52: 2.341526135802269
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 53: 1.3573364615440369
[2024-10-08 07:55:12,752][flwr][INFO] - 		round 54: 0.899897369442553
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 55: 2.0128080003401814
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 56: 1.2808630175368731
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 57: 1.3635377627152663
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 58: 0.47820611881173175
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 59: 1.8676806111489572
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 60: 1.0948202764546429
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 61: 1.1522898972034454
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 62: 0.8157711625099182
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 63: 1.5036690343510022
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 64: 1.5264658602801235
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 65: 1.7552371117975805
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 66: 1.8925058853167753
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 67: 1.0840011153902327
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 68: 6.582734107971191
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 69: 2.085990126068528
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 70: 4.486934511498972
[2024-10-08 07:55:12,753][flwr][INFO] - 		round 71: 5.986764848232269
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 72: 4.013088359552271
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 73: 1.4895541336801317
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 74: 2.0200610772983447
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 75: 1.9047014117240906
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 76: 4.400998065248132
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 77: 3.3401019452798244
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 78: 1.6606075295380183
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 79: 0.22554928809404373
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 80: 1.1765694212222444
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 81: 1.6506611613904016
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 82: 3.7786182165145874
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 83: 0.7548846193722316
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 84: 2.8685151371922526
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 85: 1.0504538087283863
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 86: 1.2122539430856705
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 87: 1.666920082135634
[2024-10-08 07:55:12,754][flwr][INFO] - 		round 88: 0.5288084068081595
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 89: 0.2969711534678936
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 90: 0.26347485887554456
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 91: 1.1532350992088887
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 92: 1.9499684696396191
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 93: 0.7946847336632865
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 94: 1.0634729850131113
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 95: 1.6195591688156128
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 96: 1.94196329034608
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 97: 0.6306401532271813
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 98: 1.000662736594677
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 99: 1.6996868775214677
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 100: 1.8771303840305493
[2024-10-08 07:55:12,755][flwr][INFO] - 	History (loss, centralized):
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 0: 233.19008803367615
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 1: 411.0157964229584
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 2: 474.1421434879303
[2024-10-08 07:55:12,755][flwr][INFO] - 		round 3: 243.3247720003128
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 4: 218.2811257839203
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 5: 211.60870611667633
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 6: 237.47075581550598
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 7: 235.10992670059204
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 8: 216.43549740314484
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 9: 217.994495511055
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 10: 230.22286522388458
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 11: 258.5099241733551
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 12: 548.1587145328522
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 13: 307.7113616466522
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 14: 212.33438658714294
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 15: 320.460476398468
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 16: 186.6889237165451
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 17: 206.57500159740448
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 18: 207.8744134902954
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 19: 255.94065475463867
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 20: 219.3297656774521
[2024-10-08 07:55:12,756][flwr][INFO] - 		round 21: 215.59824883937836
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 22: 173.17717373371124
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 23: 201.3682802915573
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 24: 297.80133068561554
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 25: 172.873042345047
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 26: 215.62482798099518
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 27: 208.19599390029907
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 28: 234.11587631702423
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 29: 202.25590753555298
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 30: 180.54515886306763
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 31: 337.69500756263733
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 32: 185.32347345352173
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 33: 194.389493227005
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 34: 186.27762496471405
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 35: 210.85348737239838
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 36: 215.84871411323547
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 37: 291.5173964500427
[2024-10-08 07:55:12,757][flwr][INFO] - 		round 38: 204.0523053407669
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 39: 210.67329514026642
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 40: 193.0704047679901
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 41: 180.00271809101105
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 42: 191.90782856941223
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 43: 205.9418717622757
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 44: 179.0502725839615
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 45: 200.88563859462738
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 46: 201.44655096530914
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 47: 168.60728979110718
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 48: 182.5887041091919
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 49: 502.69821763038635
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 50: 170.68620491027832
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 51: 194.9308898448944
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 52: 202.84993958473206
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 53: 202.16950845718384
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 54: 344.9373936653137
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 55: 219.88135087490082
[2024-10-08 07:55:12,758][flwr][INFO] - 		round 56: 226.15913677215576
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 57: 175.70326709747314
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 58: 197.66745495796204
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 59: 227.7663698196411
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 60: 152.42790293693542
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 61: 193.7183976173401
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 62: 175.20003056526184
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 63: 230.11346077919006
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 64: 199.64166796207428
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 65: 225.71219110488892
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 66: 201.5156533718109
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 67: 178.68467378616333
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 68: 482.5349431037903
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 69: 166.46935415267944
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 70: 319.14126420021057
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 71: 241.59485483169556
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 72: 193.74092876911163
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 73: 154.2864362001419
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 74: 157.92352676391602
[2024-10-08 07:55:12,759][flwr][INFO] - 		round 75: 193.75431966781616
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 76: 185.12351644039154
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 77: 187.90618526935577
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 78: 147.83130145072937
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 79: 157.95090174674988
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 80: 179.0729079246521
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 81: 177.16704607009888
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 82: 163.0197932124138
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 83: 148.8639082312584
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 84: 195.29176437854767
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 85: 148.98852372169495
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 86: 160.87465274333954
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 87: 145.6399712562561
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 88: 263.08507919311523
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 89: 147.65157169103622
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 90: 178.26862013339996
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 91: 134.89477860927582
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 92: 170.6914176940918
[2024-10-08 07:55:12,760][flwr][INFO] - 		round 93: 150.86507630348206
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 94: 163.85608732700348
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 95: 223.52735781669617
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 96: 193.33541190624237
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 97: 142.98028898239136
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 98: 111.64086282253265
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 99: 168.52499568462372
[2024-10-08 07:55:12,761][flwr][INFO] - 		round 100: 181.8194831609726
[2024-10-08 07:55:12,761][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-10-08 07:55:12,761][flwr][INFO] - 	{'accuracy': [(1, 0.0),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (2, 0.0),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (3, 0.9090909090909091),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (4, 0.15384615384615385),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (5, 0.0),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (6, 0.5),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (7, 0.13043478260869565),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (8, 0.7428571428571429),
[2024-10-08 07:55:12,761][flwr][INFO] - 	              (9, 0.8),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (10, 0.2857142857142857),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (11, 0.3469387755102041),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (12, 0.0),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (13, 0.037037037037037035),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (14, 0.0),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (15, 0.07575757575757576),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (16, 0.3793103448275862),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (17, 0.5714285714285714),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (18, 0.21428571428571427),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (19, 0.0),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (20, 0.0),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (21, 0.4142857142857143),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (22, 0.2916666666666667),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (23, 0.3392857142857143),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (24, 0.0),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (25, 0.0),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (26, 0.625),
[2024-10-08 07:55:12,762][flwr][INFO] - 	              (27, 0.19047619047619047),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (28, 0.02127659574468085),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (29, 0.2391304347826087),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (30, 0.027777777777777776),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (31, 0.35),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (32, 0.5666666666666667),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (33, 0.25),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (34, 0.0),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (35, 0.8055555555555557),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (36, 0.0196078431372549),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (37, 0.6),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (38, 0.2),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (39, 0.5151515151515151),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (40, 0.675),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (41, 0.10294117647058823),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (42, 0.6666666666666666),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (43, 0.35294117647058826),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (44, 0.8333333333333334),
[2024-10-08 07:55:12,763][flwr][INFO] - 	              (45, 0.017543859649122806),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (46, 0.5268817204301075),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (47, 0.0),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (48, 0.43820224719101125),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (49, 0.65),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (50, 0.7777777777777778),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (51, 0.12941176470588237),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (52, 0.25),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (53, 0.7),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (54, 0.7682926829268293),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (55, 0.5294117647058824),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (56, 0.5813953488372093),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (57, 0.5846153846153846),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (58, 0.8695652173913043),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (59, 0.41935483870967744),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (60, 0.6111111111111112),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (61, 0.8333333333333334),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (62, 0.6129032258064516),
[2024-10-08 07:55:12,764][flwr][INFO] - 	              (63, 0.36363636363636365),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (64, 0.45454545454545453),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (65, 0.8051948051948052),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (66, 0.5865384615384616),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (67, 0.7142857142857143),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (68, 0.2),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (69, 0.10810810810810811),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (70, 0.11363636363636363),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (71, 0.05),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (72, 0.058823529411764705),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (73, 0.6388888888888888),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (74, 0.0),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (75, 0.0),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (76, 0.234375),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (77, 0.7171717171717171),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (78, 0.21428571428571427),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (79, 1.0),
[2024-10-08 07:55:12,765][flwr][INFO] - 	              (80, 0.7391304347826086),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (81, 0.5423728813559322),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (82, 0.0),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (83, 0.7142857142857143),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (84, 0.2937062937062937),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (85, 0.6470588235294118),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (86, 0.625),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (87, 0.07575757575757576),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (88, 0.8863636363636364),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (89, 0.8541666666666666),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (90, 1.0),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (91, 0.7313432835820896),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (92, 0.020833333333333332),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (93, 0.8571428571428571),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (94, 0.8378378378378378),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (95, 0.5),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (96, 0.2413793103448276),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (97, 0.7931034482758621),
[2024-10-08 07:55:12,766][flwr][INFO] - 	              (98, 0.7777777777777778),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (99, 0.4691358024691358),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (100, 0.1956521739130435)]}
[2024-10-08 07:55:12,767][flwr][INFO] - 	History (metrics, centralized):
[2024-10-08 07:55:12,767][flwr][INFO] - 	{'accuracy': [(0, 0.06664717918737212),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (1, 0.0912014030985092),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (2, 0.09090909090909091),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (3, 0.17041800643086816),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (4, 0.1824028061970184),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (5, 0.2356036246711488),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (6, 0.21543408360128619),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (7, 0.25109617071031864),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (8, 0.23677287342882197),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (9, 0.3256357790119848),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (10, 0.19789535223618826),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (11, 0.24349605378544284),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (12, 0.3346974568839521),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (13, 0.16983338205203158),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (14, 0.2589885998246127),
[2024-10-08 07:55:12,767][flwr][INFO] - 	              (15, 0.33557439345220696),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (16, 0.30838935983630517),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (17, 0.3668517977199649),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (18, 0.35632855890090614),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (19, 0.07775504238526747),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (20, 0.2776965799473838),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (21, 0.24086524408067816),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (22, 0.47149956153171585),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (23, 0.29552762350190004),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (24, 0.3051739257527039),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (25, 0.38965214849459223),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (26, 0.1400175387313651),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (27, 0.27097339959076294),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (28, 0.09704764688687519),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (29, 0.31715872551885416),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (30, 0.3028354282373575),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (31, 0.2092955276235019),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (32, 0.3981292019877229),
[2024-10-08 07:55:12,768][flwr][INFO] - 	              (33, 0.22449576147325342),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (34, 0.4016369482607425),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (35, 0.22011107863197896),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (36, 0.20637240572931892),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (37, 0.20228003507746273),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (38, 0.25051154633148204),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (39, 0.22946506869336453),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (40, 0.34726688102893893),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (41, 0.33586670564162524),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (42, 0.4191756796258404),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (43, 0.3525285004384683),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (44, 0.3566208710903245),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (45, 0.35632855890090614),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (46, 0.3121894182987431),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (47, 0.33820520315697167),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (48, 0.43379128909675535),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (49, 0.2850043846828413),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (50, 0.5036539023677288),
[2024-10-08 07:55:12,769][flwr][INFO] - 	              (51, 0.388482899736919),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (52, 0.3925752703887752),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (53, 0.2554808535515931),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (54, 0.3291435252850044),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (55, 0.2619117217187957),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (56, 0.31335866705641624),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (57, 0.3466822566501023),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (58, 0.4329143525285004),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (59, 0.22712657117801813),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (60, 0.49722303420052616),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (61, 0.34726688102893893),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (62, 0.36100555393159894),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (63, 0.21543408360128619),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (64, 0.40192926045016075),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (65, 0.3259280912014031),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (66, 0.35983630517392573),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (67, 0.40397544577608885),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (68, 0.22712657117801813),
[2024-10-08 07:55:12,770][flwr][INFO] - 	              (69, 0.39637532885121307),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (70, 0.3665594855305466),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (71, 0.5390236772873429),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (72, 0.2972814966384098),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (73, 0.5442852966968723),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (74, 0.44606840105232387),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (75, 0.3668517977199649),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (76, 0.4370067231803566),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (77, 0.467699503069278),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (78, 0.5048231511254019),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (79, 0.5141771411867875),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (80, 0.5211926337328266),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (81, 0.4717918737211342),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (82, 0.5390236772873429),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (83, 0.4644840689856767),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (84, 0.2320958783981292),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (85, 0.5007307804735458),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (86, 0.40543700672318034),
[2024-10-08 07:55:12,771][flwr][INFO] - 	              (87, 0.5273311897106109),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (88, 0.3572054954691611),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (89, 0.4758842443729904),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (90, 0.41011400175387314),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (91, 0.529377375036539),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (92, 0.3683133586670564),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (93, 0.4884536685179772),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (94, 0.5913475591932184),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (95, 0.278865828705057),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (96, 0.34726688102893893),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (97, 0.5162233265127156),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (98, 0.5726395790704473),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (99, 0.5828705057000877),
[2024-10-08 07:55:12,772][flwr][INFO] - 	              (100, 0.3762057877813505)]}
[2024-10-08 07:55:12,772][flwr][INFO] - 
