[2024-10-05 06:00:02,088][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-10-05 06:00:05,297][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 256.0, 'memory': 157706410189.0, 'node:115.145.172.224': 1.0, 'object_store_memory': 71874175795.0, 'node:__internal_head__': 1.0, 'GPU': 5.0, 'accelerator_type:G': 1.0}
[2024-10-05 06:00:05,297][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-10-05 06:00:05,297][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 64, 'num_gpus': 0.125}
[2024-10-05 06:00:05,312][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 4 actors
[2024-10-05 06:00:05,312][flwr][INFO] - [INIT]
[2024-10-05 06:00:05,312][flwr][INFO] - Requesting initial parameters from one random client
[2024-10-05 06:00:10,539][flwr][INFO] - Received initial parameters from one random client
[2024-10-05 06:00:10,539][flwr][INFO] - Evaluating initial global parameters
[2024-10-05 06:00:21,128][flwr][INFO] - initial parameters (loss, other metrics): 236.33138155937195, {'accuracy': 0.10377082724349605}
[2024-10-05 06:00:21,129][flwr][INFO] - 
[2024-10-05 06:00:21,129][flwr][INFO] - [ROUND 1]
[2024-10-05 06:00:21,129][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:00:24,582][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:00:24,583][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:00:28,863][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:00:29,584][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-10-05 06:00:38,492][flwr][INFO] - fit progress: (1, 240.13710713386536, {'accuracy': 0.07132417421806489}, 17.362718003802)
[2024-10-05 06:00:38,492][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:00:39,785][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:00:39,785][flwr][INFO] - 
[2024-10-05 06:00:39,785][flwr][INFO] - [ROUND 2]
[2024-10-05 06:00:39,786][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:00:46,126][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:00:55,967][flwr][INFO] - fit progress: (2, 229.49417304992676, {'accuracy': 0.08389359836305174}, 34.83859493304044)
[2024-10-05 06:00:55,968][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:00:57,498][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:00:57,499][flwr][INFO] - 
[2024-10-05 06:00:57,499][flwr][INFO] - [ROUND 3]
[2024-10-05 06:00:57,499][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:01:11,545][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:01:20,822][flwr][INFO] - fit progress: (3, 240.28608441352844, {'accuracy': 0.19467991815258695}, 59.69337256718427)
[2024-10-05 06:01:20,824][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:01:22,260][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:01:22,260][flwr][INFO] - 
[2024-10-05 06:01:22,260][flwr][INFO] - [ROUND 4]
[2024-10-05 06:01:22,261][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:01:25,481][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:01:25,481][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:01:30,451][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:01:39,378][flwr][INFO] - fit progress: (4, 238.58692264556885, {'accuracy': 0.16924875767319497}, 78.24960198998451)
[2024-10-05 06:01:39,379][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:01:41,119][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:01:41,120][flwr][INFO] - 
[2024-10-05 06:01:41,120][flwr][INFO] - [ROUND 5]
[2024-10-05 06:01:41,120][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:01:53,769][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:02:02,763][flwr][INFO] - fit progress: (5, 223.55761849880219, {'accuracy': 0.1864951768488746}, 101.63447939231992)
[2024-10-05 06:02:02,764][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:02:04,248][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:02:04,248][flwr][INFO] - 
[2024-10-05 06:02:04,248][flwr][INFO] - [ROUND 6]
[2024-10-05 06:02:04,248][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:02:13,981][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:02:23,300][flwr][INFO] - fit progress: (6, 221.4792342185974, {'accuracy': 0.18035662087109033}, 122.1715670498088)
[2024-10-05 06:02:23,301][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:02:24,533][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:02:24,533][flwr][INFO] - 
[2024-10-05 06:02:24,533][flwr][INFO] - [ROUND 7]
[2024-10-05 06:02:24,534][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:02:37,186][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:02:46,314][flwr][INFO] - fit progress: (7, 225.10154855251312, {'accuracy': 0.11254019292604502}, 145.18505258206278)
[2024-10-05 06:02:46,314][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:02:47,566][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:02:47,567][flwr][INFO] - 
[2024-10-05 06:02:47,567][flwr][INFO] - [ROUND 8]
[2024-10-05 06:02:47,567][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:02:58,427][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:03:07,536][flwr][INFO] - fit progress: (8, 210.6286243200302, {'accuracy': 0.24291142940660626}, 166.40711352042854)
[2024-10-05 06:03:07,536][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:03:08,862][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:03:08,862][flwr][INFO] - 
[2024-10-05 06:03:08,862][flwr][INFO] - [ROUND 9]
[2024-10-05 06:03:08,862][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:03:24,496][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:03:33,593][flwr][INFO] - fit progress: (9, 203.32578802108765, {'accuracy': 0.19701841566793335}, 192.46390543319285)
[2024-10-05 06:03:33,593][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:03:35,048][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:03:35,049][flwr][INFO] - 
[2024-10-05 06:03:35,049][flwr][INFO] - [ROUND 10]
[2024-10-05 06:03:35,049][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:03:47,973][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:03:57,076][flwr][INFO] - fit progress: (10, 193.9426153898239, {'accuracy': 0.28792750657702426}, 215.94685878325254)
[2024-10-05 06:03:57,076][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:03:58,153][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:03:58,153][flwr][INFO] - 
[2024-10-05 06:03:58,154][flwr][INFO] - [ROUND 11]
[2024-10-05 06:03:58,154][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:04:19,112][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:04:28,903][flwr][INFO] - fit progress: (11, 175.88834619522095, {'accuracy': 0.4361297866121017}, 247.77368961367756)
[2024-10-05 06:04:28,903][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:04:29,499][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:04:29,500][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:04:29,925][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:04:29,925][flwr][INFO] - 
[2024-10-05 06:04:29,925][flwr][INFO] - [ROUND 12]
[2024-10-05 06:04:29,926][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:04:44,719][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:04:54,240][flwr][INFO] - fit progress: (12, 159.3783745765686, {'accuracy': 0.43028354282373577}, 273.1110989553854)
[2024-10-05 06:04:54,241][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:04:54,668][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:04:54,668][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:04:55,442][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:04:55,442][flwr][INFO] - 
[2024-10-05 06:04:55,442][flwr][INFO] - [ROUND 13]
[2024-10-05 06:04:55,443][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:05:03,566][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:05:13,684][flwr][INFO] - fit progress: (13, 154.00937366485596, {'accuracy': 0.48640748319204913}, 292.55538774840534)
[2024-10-05 06:05:13,685][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:05:14,198][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:05:14,198][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:05:15,021][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:05:15,022][flwr][INFO] - 
[2024-10-05 06:05:15,022][flwr][INFO] - [ROUND 14]
[2024-10-05 06:05:15,022][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:05:23,962][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:05:33,465][flwr][INFO] - fit progress: (14, 171.70036458969116, {'accuracy': 0.38059047062262497}, 312.33607827778906)
[2024-10-05 06:05:33,466][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:05:34,944][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:05:34,944][flwr][INFO] - 
[2024-10-05 06:05:34,944][flwr][INFO] - [ROUND 15]
[2024-10-05 06:05:34,945][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:05:45,421][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:05:54,372][flwr][INFO] - fit progress: (15, 136.1799882054329, {'accuracy': 0.5334697456883952}, 333.24277985002846)
[2024-10-05 06:05:54,372][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:05:54,880][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:05:54,880][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:05:55,523][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:05:55,524][flwr][INFO] - 
[2024-10-05 06:05:55,524][flwr][INFO] - [ROUND 16]
[2024-10-05 06:05:55,524][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:06:08,696][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:06:17,782][flwr][INFO] - fit progress: (16, 174.08753561973572, {'accuracy': 0.3387898275358082}, 356.65289776492864)
[2024-10-05 06:06:17,782][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:06:19,005][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:06:19,006][flwr][INFO] - 
[2024-10-05 06:06:19,006][flwr][INFO] - [ROUND 17]
[2024-10-05 06:06:19,006][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:06:32,582][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:06:41,621][flwr][INFO] - fit progress: (17, 141.0701196193695, {'accuracy': 0.5258696287635194}, 380.4925939068198)
[2024-10-05 06:06:41,622][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:06:43,194][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:06:43,194][flwr][INFO] - 
[2024-10-05 06:06:43,195][flwr][INFO] - [ROUND 18]
[2024-10-05 06:06:43,195][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:06:50,457][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:06:59,401][flwr][INFO] - fit progress: (18, 160.43848651647568, {'accuracy': 0.45308389359836304}, 398.2718858476728)
[2024-10-05 06:06:59,401][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:07:00,628][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:07:00,628][flwr][INFO] - 
[2024-10-05 06:07:00,628][flwr][INFO] - [ROUND 19]
[2024-10-05 06:07:00,628][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:07:05,844][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:07:14,976][flwr][INFO] - fit progress: (19, 145.90934896469116, {'accuracy': 0.4644840689856767}, 413.8466801196337)
[2024-10-05 06:07:14,976][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:07:16,153][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:07:16,153][flwr][INFO] - 
[2024-10-05 06:07:16,153][flwr][INFO] - [ROUND 20]
[2024-10-05 06:07:16,153][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:07:31,483][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:07:40,964][flwr][INFO] - fit progress: (20, 115.82511478662491, {'accuracy': 0.617363344051447}, 439.8355721468106)
[2024-10-05 06:07:40,965][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:07:42,425][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:07:42,425][flwr][INFO] - 
[2024-10-05 06:07:42,425][flwr][INFO] - [ROUND 21]
[2024-10-05 06:07:42,425][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:07:54,982][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:08:03,876][flwr][INFO] - fit progress: (21, 123.15398263931274, {'accuracy': 0.5825781935106694}, 462.74736929964274)
[2024-10-05 06:08:03,877][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:08:05,208][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:08:05,209][flwr][INFO] - 
[2024-10-05 06:08:05,209][flwr][INFO] - [ROUND 22]
[2024-10-05 06:08:05,209][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:08:24,640][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:08:33,537][flwr][INFO] - fit progress: (22, 123.42946928739548, {'accuracy': 0.6226249634609763}, 492.40827516280115)
[2024-10-05 06:08:33,538][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:08:35,094][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:08:35,095][flwr][INFO] - 
[2024-10-05 06:08:35,095][flwr][INFO] - [ROUND 23]
[2024-10-05 06:08:35,095][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:08:40,448][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:08:49,189][flwr][INFO] - fit progress: (23, 129.53362292051315, {'accuracy': 0.5814089447529962}, 508.06039861030877)
[2024-10-05 06:08:49,190][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:08:50,300][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:08:50,300][flwr][INFO] - 
[2024-10-05 06:08:50,301][flwr][INFO] - [ROUND 24]
[2024-10-05 06:08:50,301][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:09:02,278][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:09:11,149][flwr][INFO] - fit progress: (24, 101.48256474733353, {'accuracy': 0.6533177433498977}, 530.0198920890689)
[2024-10-05 06:09:11,149][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:09:12,731][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:09:12,732][flwr][INFO] - 
[2024-10-05 06:09:12,732][flwr][INFO] - [ROUND 25]
[2024-10-05 06:09:12,732][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:09:29,822][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:09:38,749][flwr][INFO] - fit progress: (25, 84.6849856376648, {'accuracy': 0.7497807658579363}, 557.6204859046265)
[2024-10-05 06:09:38,750][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:09:40,245][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:09:40,245][flwr][INFO] - 
[2024-10-05 06:09:40,245][flwr][INFO] - [ROUND 26]
[2024-10-05 06:09:40,245][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:09:50,438][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:09:59,125][flwr][INFO] - fit progress: (26, 93.70872691273689, {'accuracy': 0.7331189710610932}, 577.9961819360033)
[2024-10-05 06:09:59,125][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:10:00,621][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:10:00,622][flwr][INFO] - 
[2024-10-05 06:10:00,622][flwr][INFO] - [ROUND 27]
[2024-10-05 06:10:00,622][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:10:08,563][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:10:17,445][flwr][INFO] - fit progress: (27, 141.74823319911957, {'accuracy': 0.4837766734872844}, 596.3165661497042)
[2024-10-05 06:10:17,446][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:10:18,552][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:10:18,552][flwr][INFO] - 
[2024-10-05 06:10:18,552][flwr][INFO] - [ROUND 28]
[2024-10-05 06:10:18,552][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:10:35,645][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:10:44,373][flwr][INFO] - fit progress: (28, 84.67833137512207, {'accuracy': 0.707395498392283}, 623.2443876033649)
[2024-10-05 06:10:44,374][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:10:45,666][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:10:45,666][flwr][INFO] - 
[2024-10-05 06:10:45,666][flwr][INFO] - [ROUND 29]
[2024-10-05 06:10:45,666][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:10:54,870][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:11:03,698][flwr][INFO] - fit progress: (29, 100.36049664020538, {'accuracy': 0.6387021338789828}, 642.5692360401154)
[2024-10-05 06:11:03,698][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:11:05,243][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:11:05,243][flwr][INFO] - 
[2024-10-05 06:11:05,243][flwr][INFO] - [ROUND 30]
[2024-10-05 06:11:05,244][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:11:20,874][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:11:29,709][flwr][INFO] - fit progress: (30, 107.96695601940155, {'accuracy': 0.623209587839813}, 668.5805725315586)
[2024-10-05 06:11:29,710][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:11:31,017][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:11:31,017][flwr][INFO] - 
[2024-10-05 06:11:31,017][flwr][INFO] - [ROUND 31]
[2024-10-05 06:11:31,018][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:11:43,428][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:11:52,314][flwr][INFO] - fit progress: (31, 88.70108416676521, {'accuracy': 0.7003800058462438}, 691.1854709135368)
[2024-10-05 06:11:52,315][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:11:53,442][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:11:53,442][flwr][INFO] - 
[2024-10-05 06:11:53,442][flwr][INFO] - [ROUND 32]
[2024-10-05 06:11:53,442][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:12:11,666][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:12:20,986][flwr][INFO] - fit progress: (32, 76.72184532880783, {'accuracy': 0.7354574685764397}, 719.8575379149988)
[2024-10-05 06:12:20,987][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:12:22,355][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:12:22,356][flwr][INFO] - 
[2024-10-05 06:12:22,356][flwr][INFO] - [ROUND 33]
[2024-10-05 06:12:22,356][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:12:32,078][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:12:40,995][flwr][INFO] - fit progress: (33, 79.7410495877266, {'accuracy': 0.7439345220695703}, 739.8659013230354)
[2024-10-05 06:12:40,995][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:12:42,562][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:12:42,562][flwr][INFO] - 
[2024-10-05 06:12:42,562][flwr][INFO] - [ROUND 34]
[2024-10-05 06:12:42,563][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:12:47,868][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:12:56,661][flwr][INFO] - fit progress: (34, 83.22388049960136, {'accuracy': 0.746565331774335}, 755.5324345519766)
[2024-10-05 06:12:56,662][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:12:57,936][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:12:57,937][flwr][INFO] - 
[2024-10-05 06:12:57,937][flwr][INFO] - [ROUND 35]
[2024-10-05 06:12:57,937][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:13:05,137][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:13:14,045][flwr][INFO] - fit progress: (35, 84.50949341058731, {'accuracy': 0.7141186787489038}, 772.91667714715)
[2024-10-05 06:13:14,046][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:13:15,484][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:13:15,484][flwr][INFO] - 
[2024-10-05 06:13:15,484][flwr][INFO] - [ROUND 36]
[2024-10-05 06:13:15,484][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:13:24,965][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:13:34,514][flwr][INFO] - fit progress: (36, 151.26749420166016, {'accuracy': 0.5542239111370945}, 793.3852952169254)
[2024-10-05 06:13:34,514][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:13:35,828][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:13:35,828][flwr][INFO] - 
[2024-10-05 06:13:35,828][flwr][INFO] - [ROUND 37]
[2024-10-05 06:13:35,828][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:13:39,969][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:13:39,969][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:13:45,847][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:13:54,442][flwr][INFO] - fit progress: (37, 115.35078549385071, {'accuracy': 0.6366559485530546}, 813.313161527738)
[2024-10-05 06:13:54,442][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:13:54,867][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:13:54,867][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172883, ip=115.145.172.224, actor_id=623f14b40e7a65c46492d53d01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd618789a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:13:55,486][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:13:55,487][flwr][INFO] - 
[2024-10-05 06:13:55,487][flwr][INFO] - [ROUND 38]
[2024-10-05 06:13:55,487][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:14:08,211][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:14:17,157][flwr][INFO] - fit progress: (38, 86.5917598605156, {'accuracy': 0.69073370359544}, 836.0286557888612)
[2024-10-05 06:14:17,158][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:14:18,530][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:14:18,531][flwr][INFO] - 
[2024-10-05 06:14:18,531][flwr][INFO] - [ROUND 39]
[2024-10-05 06:14:18,531][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:14:33,168][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:14:42,332][flwr][INFO] - fit progress: (39, 69.33680498600006, {'accuracy': 0.7702426191172171}, 861.2030145768076)
[2024-10-05 06:14:42,332][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:14:43,656][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:14:43,657][flwr][INFO] - 
[2024-10-05 06:14:43,657][flwr][INFO] - [ROUND 40]
[2024-10-05 06:14:43,657][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:14:48,651][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:14:57,486][flwr][INFO] - fit progress: (40, 85.85072594881058, {'accuracy': 0.7307804735457468}, 876.3576364526525)
[2024-10-05 06:14:57,487][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:14:59,016][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:14:59,016][flwr][INFO] - 
[2024-10-05 06:14:59,016][flwr][INFO] - [ROUND 41]
[2024-10-05 06:14:59,017][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:15:04,973][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:15:13,938][flwr][INFO] - fit progress: (41, 103.50084364414215, {'accuracy': 0.6360713241742181}, 892.8090613642707)
[2024-10-05 06:15:13,939][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:15:15,143][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:15:15,144][flwr][INFO] - 
[2024-10-05 06:15:15,144][flwr][INFO] - [ROUND 42]
[2024-10-05 06:15:15,144][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:15:32,844][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:15:42,291][flwr][INFO] - fit progress: (42, 73.80736404657364, {'accuracy': 0.7652733118971061}, 921.1622225707397)
[2024-10-05 06:15:42,291][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:15:43,511][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:15:43,512][flwr][INFO] - 
[2024-10-05 06:15:43,512][flwr][INFO] - [ROUND 43]
[2024-10-05 06:15:43,512][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:16:04,294][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:16:13,256][flwr][INFO] - fit progress: (43, 79.77280139923096, {'accuracy': 0.7404267757965507}, 952.127189268358)
[2024-10-05 06:16:13,256][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:16:14,528][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:16:14,528][flwr][INFO] - 
[2024-10-05 06:16:14,528][flwr][INFO] - [ROUND 44]
[2024-10-05 06:16:14,528][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:16:22,386][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:16:31,286][flwr][INFO] - fit progress: (44, 88.64577507972717, {'accuracy': 0.7208418591055247}, 970.156695432961)
[2024-10-05 06:16:31,286][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:16:32,424][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:16:32,424][flwr][INFO] - 
[2024-10-05 06:16:32,424][flwr][INFO] - [ROUND 45]
[2024-10-05 06:16:32,424][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:16:43,797][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:16:52,624][flwr][INFO] - fit progress: (45, 81.27155995368958, {'accuracy': 0.7231803566208711}, 991.4955693501979)
[2024-10-05 06:16:52,625][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:16:53,817][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:16:53,817][flwr][INFO] - 
[2024-10-05 06:16:53,817][flwr][INFO] - [ROUND 46]
[2024-10-05 06:16:53,817][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:17:07,918][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:17:16,864][flwr][INFO] - fit progress: (46, 68.92230534553528, {'accuracy': 0.7708272434960538}, 1015.7350237090141)
[2024-10-05 06:17:16,864][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:17:18,131][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:17:18,132][flwr][INFO] - 
[2024-10-05 06:17:18,132][flwr][INFO] - [ROUND 47]
[2024-10-05 06:17:18,132][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:17:26,692][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:17:35,550][flwr][INFO] - fit progress: (47, 68.2544752061367, {'accuracy': 0.7766734872844198}, 1034.4209133489057)
[2024-10-05 06:17:35,550][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:17:36,822][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:17:36,822][flwr][INFO] - 
[2024-10-05 06:17:36,822][flwr][INFO] - [ROUND 48]
[2024-10-05 06:17:36,822][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:17:42,713][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:17:51,704][flwr][INFO] - fit progress: (48, 63.726152032613754, {'accuracy': 0.7825197310727857}, 1050.5751502374187)
[2024-10-05 06:17:51,704][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:17:53,080][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:17:53,080][flwr][INFO] - 
[2024-10-05 06:17:53,080][flwr][INFO] - [ROUND 49]
[2024-10-05 06:17:53,080][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:18:08,473][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:18:18,229][flwr][INFO] - fit progress: (49, 61.42965191602707, {'accuracy': 0.8056123940368314}, 1077.10054910928)
[2024-10-05 06:18:18,230][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:18:19,709][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:18:19,709][flwr][INFO] - 
[2024-10-05 06:18:19,710][flwr][INFO] - [ROUND 50]
[2024-10-05 06:18:19,710][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:18:26,742][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:18:35,597][flwr][INFO] - fit progress: (50, 65.77167314291, {'accuracy': 0.7886582870505701}, 1094.468228331767)
[2024-10-05 06:18:35,597][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:18:36,681][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:18:36,682][flwr][INFO] - 
[2024-10-05 06:18:36,682][flwr][INFO] - [ROUND 51]
[2024-10-05 06:18:36,682][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:18:45,998][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:18:54,901][flwr][INFO] - fit progress: (51, 56.04541555047035, {'accuracy': 0.8202280035077463}, 1113.7717350162566)
[2024-10-05 06:18:54,901][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:18:56,102][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:18:56,103][flwr][INFO] - 
[2024-10-05 06:18:56,103][flwr][INFO] - [ROUND 52]
[2024-10-05 06:18:56,103][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:19:10,120][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:19:19,086][flwr][INFO] - fit progress: (52, 68.03166301548481, {'accuracy': 0.7752119263373283}, 1137.9569622175768)
[2024-10-05 06:19:19,086][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:19:20,370][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:19:20,371][flwr][INFO] - 
[2024-10-05 06:19:20,371][flwr][INFO] - [ROUND 53]
[2024-10-05 06:19:20,371][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:19:28,861][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:19:37,647][flwr][INFO] - fit progress: (53, 54.70289260149002, {'accuracy': 0.8345513007892429}, 1156.517603604123)
[2024-10-05 06:19:37,647][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:19:39,106][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:19:39,106][flwr][INFO] - 
[2024-10-05 06:19:39,106][flwr][INFO] - [ROUND 54]
[2024-10-05 06:19:39,106][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:19:39,842][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:19:39,842][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:19:59,137][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:20:08,069][flwr][INFO] - fit progress: (54, 57.13333009183407, {'accuracy': 0.8193510669394913}, 1186.939804976806)
[2024-10-05 06:20:08,069][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:20:09,545][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:20:09,546][flwr][INFO] - 
[2024-10-05 06:20:09,546][flwr][INFO] - [ROUND 55]
[2024-10-05 06:20:09,546][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:20:15,962][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:20:24,797][flwr][INFO] - fit progress: (55, 93.2144475877285, {'accuracy': 0.7109032446653025}, 1203.6682149572298)
[2024-10-05 06:20:24,797][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:20:26,170][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:20:26,170][flwr][INFO] - 
[2024-10-05 06:20:26,170][flwr][INFO] - [ROUND 56]
[2024-10-05 06:20:26,170][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:20:39,366][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:20:48,231][flwr][INFO] - fit progress: (56, 61.06210492551327, {'accuracy': 0.8231511254019293}, 1227.101996101439)
[2024-10-05 06:20:48,231][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:20:49,508][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:20:49,508][flwr][INFO] - 
[2024-10-05 06:20:49,508][flwr][INFO] - [ROUND 57]
[2024-10-05 06:20:49,508][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:21:00,268][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:21:09,148][flwr][INFO] - fit progress: (57, 65.82437926530838, {'accuracy': 0.8035662087109032}, 1248.0193409975618)
[2024-10-05 06:21:09,148][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:21:10,450][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:21:10,451][flwr][INFO] - 
[2024-10-05 06:21:10,451][flwr][INFO] - [ROUND 58]
[2024-10-05 06:21:10,451][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:21:16,384][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:21:25,214][flwr][INFO] - fit progress: (58, 62.90731759369373, {'accuracy': 0.7801812335574393}, 1264.0850330777466)
[2024-10-05 06:21:25,214][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:21:26,385][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:21:26,385][flwr][INFO] - 
[2024-10-05 06:21:26,385][flwr][INFO] - [ROUND 59]
[2024-10-05 06:21:26,386][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:21:41,524][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:21:50,435][flwr][INFO] - fit progress: (59, 59.17308568954468, {'accuracy': 0.8047354574685764}, 1289.3064562296495)
[2024-10-05 06:21:50,436][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:21:51,861][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:21:51,862][flwr][INFO] - 
[2024-10-05 06:21:51,862][flwr][INFO] - [ROUND 60]
[2024-10-05 06:21:51,862][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:22:03,048][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:22:12,420][flwr][INFO] - fit progress: (60, 71.06874394416809, {'accuracy': 0.7620578778135049}, 1311.2913895845413)
[2024-10-05 06:22:12,421][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:22:13,605][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:22:13,606][flwr][INFO] - 
[2024-10-05 06:22:13,606][flwr][INFO] - [ROUND 61]
[2024-10-05 06:22:13,606][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:22:31,367][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:22:40,229][flwr][INFO] - fit progress: (61, 62.338760033249855, {'accuracy': 0.808243203741596}, 1339.0997467730194)
[2024-10-05 06:22:40,229][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:22:41,396][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:22:41,396][flwr][INFO] - 
[2024-10-05 06:22:41,397][flwr][INFO] - [ROUND 62]
[2024-10-05 06:22:41,397][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:22:42,109][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:22:42,109][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:22:52,139][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:23:00,859][flwr][INFO] - fit progress: (62, 86.3784776031971, {'accuracy': 0.6933645133002047}, 1359.7299245037138)
[2024-10-05 06:23:00,859][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:23:02,285][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:23:02,285][flwr][INFO] - 
[2024-10-05 06:23:02,285][flwr][INFO] - [ROUND 63]
[2024-10-05 06:23:02,285][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:23:17,185][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:23:26,025][flwr][INFO] - fit progress: (63, 56.6931079775095, {'accuracy': 0.8178895059923998}, 1384.8962520612404)
[2024-10-05 06:23:26,026][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:23:27,315][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:23:27,316][flwr][INFO] - 
[2024-10-05 06:23:27,316][flwr][INFO] - [ROUND 64]
[2024-10-05 06:23:27,316][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:23:33,836][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:23:42,528][flwr][INFO] - fit progress: (64, 87.0147098004818, {'accuracy': 0.7275650394621456}, 1401.3995196036994)
[2024-10-05 06:23:42,529][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:23:43,889][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:23:43,890][flwr][INFO] - 
[2024-10-05 06:23:43,890][flwr][INFO] - [ROUND 65]
[2024-10-05 06:23:43,890][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:23:57,026][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:24:05,843][flwr][INFO] - fit progress: (65, 52.46396325528622, {'accuracy': 0.8301666179479684}, 1424.7137107709423)
[2024-10-05 06:24:05,843][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:24:07,327][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:24:07,327][flwr][INFO] - 
[2024-10-05 06:24:07,327][flwr][INFO] - [ROUND 66]
[2024-10-05 06:24:07,327][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:24:14,344][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:24:23,153][flwr][INFO] - fit progress: (66, 71.74569356441498, {'accuracy': 0.7471499561531716}, 1442.0242309840396)
[2024-10-05 06:24:23,153][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:24:24,729][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:24:24,729][flwr][INFO] - 
[2024-10-05 06:24:24,729][flwr][INFO] - [ROUND 67]
[2024-10-05 06:24:24,729][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:24:40,344][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:24:49,243][flwr][INFO] - fit progress: (67, 64.87049502134323, {'accuracy': 0.7836889798304589}, 1468.1144101470709)
[2024-10-05 06:24:49,244][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:24:50,410][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:24:50,411][flwr][INFO] - 
[2024-10-05 06:24:50,411][flwr][INFO] - [ROUND 68]
[2024-10-05 06:24:50,411][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:25:01,348][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:25:10,240][flwr][INFO] - fit progress: (68, 60.72431081533432, {'accuracy': 0.791581408944753}, 1489.1115540023893)
[2024-10-05 06:25:10,241][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:25:11,434][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:25:11,434][flwr][INFO] - 
[2024-10-05 06:25:11,435][flwr][INFO] - [ROUND 69]
[2024-10-05 06:25:11,435][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:25:24,582][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:25:33,382][flwr][INFO] - fit progress: (69, 53.376798778772354, {'accuracy': 0.8368897983045893}, 1512.252926722169)
[2024-10-05 06:25:33,382][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:25:34,622][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:25:34,622][flwr][INFO] - 
[2024-10-05 06:25:34,622][flwr][INFO] - [ROUND 70]
[2024-10-05 06:25:34,622][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:25:52,030][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:26:01,277][flwr][INFO] - fit progress: (70, 52.49195894598961, {'accuracy': 0.8231511254019293}, 1540.1483148317784)
[2024-10-05 06:26:01,278][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:26:02,566][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:26:02,566][flwr][INFO] - 
[2024-10-05 06:26:02,566][flwr][INFO] - [ROUND 71]
[2024-10-05 06:26:02,567][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:26:15,080][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:26:24,083][flwr][INFO] - fit progress: (71, 52.831982016563416, {'accuracy': 0.830751242326805}, 1562.9545875759795)
[2024-10-05 06:26:24,084][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:26:25,776][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:26:25,777][flwr][INFO] - 
[2024-10-05 06:26:25,777][flwr][INFO] - [ROUND 72]
[2024-10-05 06:26:25,777][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:26:38,490][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:26:48,098][flwr][INFO] - fit progress: (72, 65.90101838111877, {'accuracy': 0.7833966676410407}, 1586.9690313600004)
[2024-10-05 06:26:48,099][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:26:49,706][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:26:49,707][flwr][INFO] - 
[2024-10-05 06:26:49,707][flwr][INFO] - [ROUND 73]
[2024-10-05 06:26:49,707][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:26:57,206][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:27:06,009][flwr][INFO] - fit progress: (73, 129.11083376407623, {'accuracy': 0.552762350190003}, 1604.8796881772578)
[2024-10-05 06:27:06,009][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:27:07,462][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:27:07,463][flwr][INFO] - 
[2024-10-05 06:27:07,463][flwr][INFO] - [ROUND 74]
[2024-10-05 06:27:07,463][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:27:27,114][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:27:36,746][flwr][INFO] - fit progress: (74, 67.08088764548302, {'accuracy': 0.7725811166325636}, 1635.6175801856443)
[2024-10-05 06:27:36,747][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:27:37,971][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:27:37,971][flwr][INFO] - 
[2024-10-05 06:27:37,971][flwr][INFO] - [ROUND 75]
[2024-10-05 06:27:37,971][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:27:48,259][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:27:57,046][flwr][INFO] - fit progress: (75, 57.81862775981426, {'accuracy': 0.8099970768781058}, 1655.9170657629147)
[2024-10-05 06:27:57,046][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:27:58,444][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:27:58,444][flwr][INFO] - 
[2024-10-05 06:27:58,444][flwr][INFO] - [ROUND 76]
[2024-10-05 06:27:58,444][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:28:10,862][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:28:19,709][flwr][INFO] - fit progress: (76, 54.49847337603569, {'accuracy': 0.8184741303712365}, 1678.580199206248)
[2024-10-05 06:28:19,709][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:28:21,148][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:28:21,148][flwr][INFO] - 
[2024-10-05 06:28:21,148][flwr][INFO] - [ROUND 77]
[2024-10-05 06:28:21,149][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:28:22,027][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:28:22,027][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:28:32,825][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:28:42,015][flwr][INFO] - fit progress: (77, 58.980561420321465, {'accuracy': 0.8076585793627594}, 1700.8862814623863)
[2024-10-05 06:28:42,016][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:28:43,517][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:28:43,517][flwr][INFO] - 
[2024-10-05 06:28:43,518][flwr][INFO] - [ROUND 78]
[2024-10-05 06:28:43,518][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:28:50,658][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:28:59,541][flwr][INFO] - fit progress: (78, 74.374570697546, {'accuracy': 0.757380882782812}, 1718.4122046129778)
[2024-10-05 06:28:59,541][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:29:00,600][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:29:00,600][flwr][INFO] - 
[2024-10-05 06:29:00,600][flwr][INFO] - [ROUND 79]
[2024-10-05 06:29:00,601][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:29:13,624][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:29:22,715][flwr][INFO] - fit progress: (79, 71.34155659377575, {'accuracy': 0.7705349313066355}, 1741.586585414596)
[2024-10-05 06:29:22,716][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:29:23,067][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:29:23,067][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172881, ip=115.145.172.224, actor_id=cf066b1b78e3d89400e6e65901000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f7d64581a20>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:29:24,182][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:29:24,182][flwr][INFO] - 
[2024-10-05 06:29:24,182][flwr][INFO] - [ROUND 80]
[2024-10-05 06:29:24,182][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:29:40,200][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:29:48,878][flwr][INFO] - fit progress: (80, 48.19426853209734, {'accuracy': 0.8412744811458638}, 1767.7489043353125)
[2024-10-05 06:29:48,878][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:29:50,118][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:29:50,119][flwr][INFO] - 
[2024-10-05 06:29:50,119][flwr][INFO] - [ROUND 81]
[2024-10-05 06:29:50,119][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:29:57,624][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:30:06,664][flwr][INFO] - fit progress: (81, 63.28399446606636, {'accuracy': 0.7883659748611517}, 1785.53489656467)
[2024-10-05 06:30:06,664][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:30:07,863][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:30:07,863][flwr][INFO] - 
[2024-10-05 06:30:07,863][flwr][INFO] - [ROUND 82]
[2024-10-05 06:30:07,863][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:30:12,574][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:30:21,411][flwr][INFO] - fit progress: (82, 60.81961336731911, {'accuracy': 0.7886582870505701}, 1800.2816961938515)
[2024-10-05 06:30:21,411][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:30:22,667][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:30:22,667][flwr][INFO] - 
[2024-10-05 06:30:22,667][flwr][INFO] - [ROUND 83]
[2024-10-05 06:30:22,668][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:30:33,517][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:30:42,260][flwr][INFO] - fit progress: (83, 69.4902271926403, {'accuracy': 0.7649809997076878}, 1821.1311208102852)
[2024-10-05 06:30:42,260][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:30:43,459][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:30:43,459][flwr][INFO] - 
[2024-10-05 06:30:43,459][flwr][INFO] - [ROUND 84]
[2024-10-05 06:30:43,459][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:30:44,084][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:30:44,084][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172882, ip=115.145.172.224, actor_id=cd5c03c886049a8bc3e9d8bf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fe6e0275a80>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:30:57,859][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:31:06,780][flwr][INFO] - fit progress: (84, 77.02759422361851, {'accuracy': 0.7679041216018708}, 1845.6511220531538)
[2024-10-05 06:31:06,780][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:31:08,352][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:31:08,352][flwr][INFO] - 
[2024-10-05 06:31:08,352][flwr][INFO] - [ROUND 85]
[2024-10-05 06:31:08,352][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:31:13,858][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:31:22,755][flwr][INFO] - fit progress: (85, 79.3240353167057, {'accuracy': 0.7278573516515638}, 1861.625697481446)
[2024-10-05 06:31:22,755][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:31:23,914][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:31:23,915][flwr][INFO] - 
[2024-10-05 06:31:23,915][flwr][INFO] - [ROUND 86]
[2024-10-05 06:31:23,915][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:31:36,339][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:31:45,233][flwr][INFO] - fit progress: (86, 52.357454873621464, {'accuracy': 0.8266588716749489}, 1884.104125625454)
[2024-10-05 06:31:45,233][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:31:46,581][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:31:46,582][flwr][INFO] - 
[2024-10-05 06:31:46,582][flwr][INFO] - [ROUND 87]
[2024-10-05 06:31:46,582][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:32:01,970][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:32:10,727][flwr][INFO] - fit progress: (87, 59.056809172034264, {'accuracy': 0.8006430868167203}, 1909.598079264164)
[2024-10-05 06:32:10,727][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:32:11,918][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:32:11,918][flwr][INFO] - 
[2024-10-05 06:32:11,918][flwr][INFO] - [ROUND 88]
[2024-10-05 06:32:11,918][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:32:24,547][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:32:33,348][flwr][INFO] - fit progress: (88, 61.75401644408703, {'accuracy': 0.8009353990061385}, 1932.219211912714)
[2024-10-05 06:32:33,349][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:32:34,589][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:32:34,589][flwr][INFO] - 
[2024-10-05 06:32:34,589][flwr][INFO] - [ROUND 89]
[2024-10-05 06:32:34,589][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:32:49,726][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:32:59,188][flwr][INFO] - fit progress: (89, 54.219800978899, {'accuracy': 0.825781935106694}, 1958.059452504851)
[2024-10-05 06:32:59,189][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:33:00,437][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:33:00,437][flwr][INFO] - 
[2024-10-05 06:33:00,438][flwr][INFO] - [ROUND 90]
[2024-10-05 06:33:00,438][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:33:09,650][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:33:18,648][flwr][INFO] - fit progress: (90, 61.53044205904007, {'accuracy': 0.7909967845659164}, 1977.51942501124)
[2024-10-05 06:33:18,649][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:33:19,779][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:33:19,779][flwr][INFO] - 
[2024-10-05 06:33:19,779][flwr][INFO] - [ROUND 91]
[2024-10-05 06:33:19,779][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:33:25,049][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:33:34,707][flwr][INFO] - fit progress: (91, 68.60447958111763, {'accuracy': 0.7620578778135049}, 1993.5784738361835)
[2024-10-05 06:33:34,708][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:33:36,092][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:33:36,092][flwr][INFO] - 
[2024-10-05 06:33:36,093][flwr][INFO] - [ROUND 92]
[2024-10-05 06:33:36,093][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:33:38,812][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:33:38,813][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:33:41,703][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:33:50,698][flwr][INFO] - fit progress: (92, 57.20581705868244, {'accuracy': 0.803273896521485}, 2009.569417577237)
[2024-10-05 06:33:50,699][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:33:51,822][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:33:51,822][flwr][INFO] - 
[2024-10-05 06:33:51,823][flwr][INFO] - [ROUND 93]
[2024-10-05 06:33:51,823][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:33:56,925][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:33:56,925][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:34:00,926][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-10-05 06:34:09,684][flwr][INFO] - fit progress: (93, 78.14869175851345, {'accuracy': 0.7611809412452499}, 2028.5547800511122)
[2024-10-05 06:34:09,684][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:34:10,867][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:34:10,867][flwr][INFO] - 
[2024-10-05 06:34:10,867][flwr][INFO] - [ROUND 94]
[2024-10-05 06:34:10,867][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:34:19,518][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:34:28,506][flwr][INFO] - fit progress: (94, 61.73255583643913, {'accuracy': 0.8061970184156679}, 2047.3776261946186)
[2024-10-05 06:34:28,507][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:34:29,715][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:34:29,715][flwr][INFO] - 
[2024-10-05 06:34:29,716][flwr][INFO] - [ROUND 95]
[2024-10-05 06:34:29,716][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:34:48,052][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:34:57,010][flwr][INFO] - fit progress: (95, 56.694783970713615, {'accuracy': 0.8117509500146156}, 2075.88115521241)
[2024-10-05 06:34:57,010][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:34:58,455][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:34:58,455][flwr][INFO] - 
[2024-10-05 06:34:58,455][flwr][INFO] - [ROUND 96]
[2024-10-05 06:34:58,456][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:35:09,699][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:35:18,625][flwr][INFO] - fit progress: (96, 76.18061684072018, {'accuracy': 0.7743349897690733}, 2097.4965048767626)
[2024-10-05 06:35:18,626][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:35:19,979][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:35:19,979][flwr][INFO] - 
[2024-10-05 06:35:19,979][flwr][INFO] - [ROUND 97]
[2024-10-05 06:35:19,979][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:35:39,886][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:35:48,906][flwr][INFO] - fit progress: (97, 44.33635177463293, {'accuracy': 0.8529669687225957}, 2127.77675875742)
[2024-10-05 06:35:48,906][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:35:49,217][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-10-05 06:35:49,217][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fednova_resnet101/fednova_resnet101/client.py", line 121, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=4172880, ip=115.145.172.224, actor_id=2f6abab7a9dd40473ce685c601000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f4074785a50>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-10-05 06:35:50,064][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-10-05 06:35:50,064][flwr][INFO] - 
[2024-10-05 06:35:50,064][flwr][INFO] - [ROUND 98]
[2024-10-05 06:35:50,064][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:36:01,042][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:36:09,997][flwr][INFO] - fit progress: (98, 57.88115666806698, {'accuracy': 0.8099970768781058}, 2148.8677461743355)
[2024-10-05 06:36:09,997][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:36:11,164][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:36:11,164][flwr][INFO] - 
[2024-10-05 06:36:11,164][flwr][INFO] - [ROUND 99]
[2024-10-05 06:36:11,165][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:36:21,972][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:36:30,896][flwr][INFO] - fit progress: (99, 58.38063086569309, {'accuracy': 0.8047354574685764}, 2169.7667229976505)
[2024-10-05 06:36:30,896][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:36:32,243][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:36:32,244][flwr][INFO] - 
[2024-10-05 06:36:32,244][flwr][INFO] - [ROUND 100]
[2024-10-05 06:36:32,244][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-10-05 06:36:43,673][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-10-05 06:36:52,590][flwr][INFO] - fit progress: (100, 59.37492993474007, {'accuracy': 0.7980122771119555}, 2191.4607782950625)
[2024-10-05 06:36:52,590][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-10-05 06:36:53,849][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-10-05 06:36:53,850][flwr][INFO] - 
[2024-10-05 06:36:53,850][flwr][INFO] - [SUMMARY]
[2024-10-05 06:36:53,850][flwr][INFO] - Run finished 100 round(s) in 2192.72s
[2024-10-05 06:36:53,853][flwr][INFO] - 	History (loss, distributed):
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 1: 2.4103418389956155
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 2: 4.064031325853788
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 3: 2.3343053965857536
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 4: 1.8324802838839018
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 5: 2.513835699000257
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 6: 2.503235263824463
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 7: 1.7814937659672327
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 8: 1.7530009150505066
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 9: 2.265123630824842
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 10: 1.9459028285125206
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 11: 2.3598709106445312
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 12: 1.6230117082595825
[2024-10-05 06:36:53,853][flwr][INFO] - 		round 13: 2.227914333343506
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 14: 1.1062736998904834
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 15: 1.6170990467071533
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 16: 0.7736406127611796
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 17: 0.9074432841719013
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 18: 2.399737690315872
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 19: 1.5861745551228523
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 20: 0.6859385445713997
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 21: 1.0005766723466956
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 22: 1.0161879379903116
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 23: 1.0184975191950798
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 24: 1.267752319574356
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 25: 0.8198063647424852
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 26: 1.5470846475976887
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 27: 1.1616498827934265
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 28: 0.5139753187811652
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 29: 0.9983007550239563
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 30: 0.38488483375736643
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 31: 0.6382037997245789
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 32: 0.4342872471289527
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 33: 0.5090518902088034
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 34: 0.7850742811957995
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 35: 1.8685365114055696
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 36: 0.784800212908458
[2024-10-05 06:36:53,854][flwr][INFO] - 		round 37: 0.7052298188209534
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 38: 0.38996609672904015
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 39: 0.5688871012793647
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 40: 0.3166659828275442
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 41: 0.7015477220217387
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 42: 1.4109952169306137
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 43: 0.45764402638782153
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 44: 1.032868230342865
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 45: 0.47745727002620697
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 46: 0.3431960677746499
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 47: 0.13388888694738088
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 48: 0.2769300199623378
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 49: 0.6315940758929803
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 50: 0.9636287072609211
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 51: 0.3275741447729093
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 52: 0.5707322475386829
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 53: 0.3511574506759644
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 54: 0.4266243195986446
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 55: 1.4554576992988586
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 56: 0.5337216585083345
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 57: 0.5052403624241169
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 58: 0.07348433587896197
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 59: 0.5239509814977645
[2024-10-05 06:36:53,855][flwr][INFO] - 		round 60: 0.6768650710582733
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 61: 0.5932433537461541
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 62: 0.9188691433270773
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 63: 0.0846404880285263
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 64: 0.6524002653057293
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 65: 0.5940824167148487
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 66: 0.22804126756213536
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 67: 0.28814209531992674
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 68: 0.5496097505092621
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 69: 0.16391296096538244
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 70: 0.7269697904586792
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 71: 0.5648717461405574
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 72: 0.4750239453636683
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 73: 1.0330601144920697
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 74: 0.6635274291038513
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 75: 0.1514190728776157
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 76: 1.16040096282959
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 77: 0.5177928706010183
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 78: 0.2037458211183548
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 79: 0.0484028197824955
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 80: 0.11708042822007475
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 81: 0.3711174838244915
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 82: 0.7653024942656748
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 83: 0.73558270972069
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 84: 0.9037355780601501
[2024-10-05 06:36:53,856][flwr][INFO] - 		round 85: 0.15984455589205027
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 86: 0.3557964230959232
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 87: 2.404804253578186
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 88: 0.14360648033947782
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 89: 0.46153071853849625
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 90: 1.5485376250845464
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 91: 1.1281280943325587
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 92: 0.5208965539932251
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 93: 0.23389072631889918
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 94: 0.11311211393159978
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 95: 0.11753787100315094
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 96: 0.46398447042909163
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 97: 1.066272497177124
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 98: 1.5349951684474945
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 99: 0.220385001351436
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 100: 0.13403545125671054
[2024-10-05 06:36:53,857][flwr][INFO] - 	History (loss, centralized):
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 0: 236.33138155937195
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 1: 240.13710713386536
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 2: 229.49417304992676
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 3: 240.28608441352844
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 4: 238.58692264556885
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 5: 223.55761849880219
[2024-10-05 06:36:53,857][flwr][INFO] - 		round 6: 221.4792342185974
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 7: 225.10154855251312
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 8: 210.6286243200302
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 9: 203.32578802108765
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 10: 193.9426153898239
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 11: 175.88834619522095
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 12: 159.3783745765686
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 13: 154.00937366485596
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 14: 171.70036458969116
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 15: 136.1799882054329
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 16: 174.08753561973572
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 17: 141.0701196193695
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 18: 160.43848651647568
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 19: 145.90934896469116
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 20: 115.82511478662491
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 21: 123.15398263931274
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 22: 123.42946928739548
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 23: 129.53362292051315
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 24: 101.48256474733353
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 25: 84.6849856376648
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 26: 93.70872691273689
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 27: 141.74823319911957
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 28: 84.67833137512207
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 29: 100.36049664020538
[2024-10-05 06:36:53,858][flwr][INFO] - 		round 30: 107.96695601940155
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 31: 88.70108416676521
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 32: 76.72184532880783
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 33: 79.7410495877266
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 34: 83.22388049960136
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 35: 84.50949341058731
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 36: 151.26749420166016
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 37: 115.35078549385071
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 38: 86.5917598605156
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 39: 69.33680498600006
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 40: 85.85072594881058
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 41: 103.50084364414215
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 42: 73.80736404657364
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 43: 79.77280139923096
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 44: 88.64577507972717
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 45: 81.27155995368958
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 46: 68.92230534553528
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 47: 68.2544752061367
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 48: 63.726152032613754
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 49: 61.42965191602707
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 50: 65.77167314291
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 51: 56.04541555047035
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 52: 68.03166301548481
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 53: 54.70289260149002
[2024-10-05 06:36:53,859][flwr][INFO] - 		round 54: 57.13333009183407
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 55: 93.2144475877285
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 56: 61.06210492551327
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 57: 65.82437926530838
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 58: 62.90731759369373
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 59: 59.17308568954468
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 60: 71.06874394416809
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 61: 62.338760033249855
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 62: 86.3784776031971
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 63: 56.6931079775095
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 64: 87.0147098004818
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 65: 52.46396325528622
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 66: 71.74569356441498
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 67: 64.87049502134323
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 68: 60.72431081533432
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 69: 53.376798778772354
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 70: 52.49195894598961
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 71: 52.831982016563416
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 72: 65.90101838111877
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 73: 129.11083376407623
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 74: 67.08088764548302
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 75: 57.81862775981426
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 76: 54.49847337603569
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 77: 58.980561420321465
[2024-10-05 06:36:53,860][flwr][INFO] - 		round 78: 74.374570697546
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 79: 71.34155659377575
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 80: 48.19426853209734
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 81: 63.28399446606636
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 82: 60.81961336731911
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 83: 69.4902271926403
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 84: 77.02759422361851
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 85: 79.3240353167057
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 86: 52.357454873621464
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 87: 59.056809172034264
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 88: 61.75401644408703
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 89: 54.219800978899
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 90: 61.53044205904007
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 91: 68.60447958111763
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 92: 57.20581705868244
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 93: 78.14869175851345
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 94: 61.73255583643913
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 95: 56.694783970713615
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 96: 76.18061684072018
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 97: 44.33635177463293
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 98: 57.88115666806698
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 99: 58.38063086569309
[2024-10-05 06:36:53,861][flwr][INFO] - 		round 100: 59.37492993474007
[2024-10-05 06:36:53,861][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-10-05 06:36:53,861][flwr][INFO] - 	{'accuracy': [(1, 0.0),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (2, 0.028846153846153848),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (3, 0.7121212121212122),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (4, 0.5384615384615384),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (5, 0.0),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (6, 0.0),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (7, 0.14285714285714285),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (8, 0.1875),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (9, 0.017543859649122806),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (10, 0.1724137931034483),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (11, 0.16666666666666666),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (12, 0.0),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (13, 0.05263157894736842),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (14, 0.7727272727272727),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (15, 0.0),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (16, 0.7777777777777778),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (17, 0.7671232876712328),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (18, 0.18032786885245902),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (19, 0.5),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (20, 0.8125),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (21, 0.5652173913043478),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (22, 0.6774193548387096),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (23, 0.625),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (24, 0.5),
[2024-10-05 06:36:53,862][flwr][INFO] - 	              (25, 0.8243243243243243),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (26, 0.6666666666666666),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (27, 0.5),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (28, 0.9069767441860465),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (29, 0.6333333333333333),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (30, 0.8928571428571429),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (31, 0.8181818181818182),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (32, 0.9097744360902256),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (33, 0.8275862068965517),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (34, 0.9074074074074074),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (35, 0.13114754098360656),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (36, 0.8671328671328671),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (37, 0.8461538461538461),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (38, 0.9027777777777778),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (39, 0.8148148148148148),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (40, 0.9375),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (41, 0.7037037037037037),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (42, 0.45098039215686275),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (43, 0.9090909090909091),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (44, 0.6),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (45, 0.75),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (46, 0.9603960396039604),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (47, 0.9473684210526315),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (48, 0.9528301886792453),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (49, 0.8942307692307693),
[2024-10-05 06:36:53,863][flwr][INFO] - 	              (50, 0.5862068965517241),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (51, 0.8518518518518519),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (52, 0.8292682926829268),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (53, 0.9333333333333333),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (54, 0.8607594936708861),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (55, 0.55),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (56, 0.8938053097345132),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (57, 0.8307692307692308),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (58, 1.0),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (59, 0.84),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (60, 0.5),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (61, 0.7727272727272727),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (62, 0.64),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (63, 1.0),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (64, 0.711864406779661),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (65, 0.7567567567567568),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (66, 0.9065420560747663),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (67, 0.921875),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (68, 1.0),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (69, 0.9473684210526315),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (70, 0.68),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (71, 0.8378378378378378),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (72, 0.8803418803418803),
[2024-10-05 06:36:53,864][flwr][INFO] - 	              (73, 0.5909090909090909),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (74, 0.6842105263157895),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (75, 0.9444444444444444),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (76, 0.4857142857142857),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (77, 0.8632478632478633),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (78, 1.0),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (79, 0.9705882352941176),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (80, 1.0),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (81, 0.890625),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (82, 0.7189542483660131),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (83, 0.7534246575342466),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (84, 0.6785714285714286),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (85, 0.9583333333333334),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (86, 0.9572649572649573),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (87, 0.2),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (88, 0.9310344827586207),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (89, 0.8888888888888888),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (90, 0.45454545454545453),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (91, 0.5844155844155844),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (92, 0.8035714285714286),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (93, 0.9245283018867925),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (94, 0.9803921568627451),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (95, 1.0),
[2024-10-05 06:36:53,865][flwr][INFO] - 	              (96, 0.8103448275862069),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (97, 0.6666666666666666),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (98, 0.44285714285714284),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (99, 0.9351851851851852),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (100, 0.9565217391304348)]}
[2024-10-05 06:36:53,866][flwr][INFO] - 	History (metrics, centralized):
[2024-10-05 06:36:53,866][flwr][INFO] - 	{'accuracy': [(0, 0.10377082724349605),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (1, 0.07132417421806489),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (2, 0.08389359836305174),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (3, 0.19467991815258695),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (4, 0.16924875767319497),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (5, 0.1864951768488746),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (6, 0.18035662087109033),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (7, 0.11254019292604502),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (8, 0.24291142940660626),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (9, 0.19701841566793335),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (10, 0.28792750657702426),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (11, 0.4361297866121017),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (12, 0.43028354282373577),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (13, 0.48640748319204913),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (14, 0.38059047062262497),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (15, 0.5334697456883952),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (16, 0.3387898275358082),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (17, 0.5258696287635194),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (18, 0.45308389359836304),
[2024-10-05 06:36:53,866][flwr][INFO] - 	              (19, 0.4644840689856767),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (20, 0.617363344051447),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (21, 0.5825781935106694),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (22, 0.6226249634609763),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (23, 0.5814089447529962),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (24, 0.6533177433498977),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (25, 0.7497807658579363),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (26, 0.7331189710610932),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (27, 0.4837766734872844),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (28, 0.707395498392283),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (29, 0.6387021338789828),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (30, 0.623209587839813),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (31, 0.7003800058462438),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (32, 0.7354574685764397),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (33, 0.7439345220695703),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (34, 0.746565331774335),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (35, 0.7141186787489038),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (36, 0.5542239111370945),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (37, 0.6366559485530546),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (38, 0.69073370359544),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (39, 0.7702426191172171),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (40, 0.7307804735457468),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (41, 0.6360713241742181),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (42, 0.7652733118971061),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (43, 0.7404267757965507),
[2024-10-05 06:36:53,867][flwr][INFO] - 	              (44, 0.7208418591055247),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (45, 0.7231803566208711),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (46, 0.7708272434960538),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (47, 0.7766734872844198),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (48, 0.7825197310727857),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (49, 0.8056123940368314),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (50, 0.7886582870505701),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (51, 0.8202280035077463),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (52, 0.7752119263373283),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (53, 0.8345513007892429),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (54, 0.8193510669394913),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (55, 0.7109032446653025),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (56, 0.8231511254019293),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (57, 0.8035662087109032),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (58, 0.7801812335574393),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (59, 0.8047354574685764),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (60, 0.7620578778135049),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (61, 0.808243203741596),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (62, 0.6933645133002047),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (63, 0.8178895059923998),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (64, 0.7275650394621456),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (65, 0.8301666179479684),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (66, 0.7471499561531716),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (67, 0.7836889798304589),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (68, 0.791581408944753),
[2024-10-05 06:36:53,868][flwr][INFO] - 	              (69, 0.8368897983045893),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (70, 0.8231511254019293),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (71, 0.830751242326805),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (72, 0.7833966676410407),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (73, 0.552762350190003),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (74, 0.7725811166325636),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (75, 0.8099970768781058),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (76, 0.8184741303712365),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (77, 0.8076585793627594),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (78, 0.757380882782812),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (79, 0.7705349313066355),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (80, 0.8412744811458638),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (81, 0.7883659748611517),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (82, 0.7886582870505701),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (83, 0.7649809997076878),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (84, 0.7679041216018708),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (85, 0.7278573516515638),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (86, 0.8266588716749489),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (87, 0.8006430868167203),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (88, 0.8009353990061385),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (89, 0.825781935106694),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (90, 0.7909967845659164),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (91, 0.7620578778135049),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (92, 0.803273896521485),
[2024-10-05 06:36:53,869][flwr][INFO] - 	              (93, 0.7611809412452499),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (94, 0.8061970184156679),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (95, 0.8117509500146156),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (96, 0.7743349897690733),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (97, 0.8529669687225957),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (98, 0.8099970768781058),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (99, 0.8047354574685764),
[2024-10-05 06:36:53,870][flwr][INFO] - 	              (100, 0.7980122771119555)]}
[2024-10-05 06:36:53,870][flwr][INFO] - 
