[2024-09-06 14:42:01,661][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-09-06 14:42:04,722][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 168667704320.0, 'node:__internal_head__': 1.0, 'node:115.145.172.224': 1.0, 'object_store_memory': 76571873280.0, 'GPU': 5.0, 'accelerator_type:G': 1.0, 'CPU': 256.0}
[2024-09-06 14:42:04,723][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-09-06 14:42:04,723][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 24, 'num_gpus': 0.125}
[2024-09-06 14:42:04,738][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 10 actors
[2024-09-06 14:42:04,738][flwr][INFO] - [INIT]
[2024-09-06 14:42:04,739][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-06 14:42:09,005][flwr][INFO] - Received initial parameters from one random client
[2024-09-06 14:42:09,006][flwr][INFO] - Evaluating initial global parameters
[2024-09-06 14:42:09,611][flwr][ERROR] - module 'PIL.Image' has no attribute 'ExifTags'
[2024-09-06 14:42:09,614][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/server/server.py", line 490, in run_fl
    hist, elapsed_time = server.fit(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/server/server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet/fedavg_mobilnet/server.py", line 65, in evaluate
    loss, accuracy = test(model, testloader, device=device)
  File "/home/abdenour/fl_with_flower/fedavg_mobilnet/fedavg_mobilnet/utils.py", line 52, in test
    for data in testloader:
  File "/home/abdenour/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/abdenour/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/abdenour/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2865, in __getitems__
    batch = self.__getitem__(keys)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2861, in __getitem__
    return self._getitem(key)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2846, in _getitem
    formatted_output = format_table(
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 633, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 401, in __call__
    return self.format_batch(pa_table)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 515, in format_batch
    batch = self.python_features_decoder.decode_batch(batch)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 222, in decode_batch
    return self.features.decode_batch(batch) if self.features else batch
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/features/features.py", line 2018, in decode_batch
    [
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/features/features.py", line 2019, in <listcomp>
    decode_nested_example(self[column_name], value, token_per_repo_id=token_per_repo_id)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/features/features.py", line 1341, in decode_nested_example
    return schema.decode_example(obj, token_per_repo_id=token_per_repo_id)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/features/image.py", line 189, in decode_example
    if image.getexif().get(PIL.Image.ExifTags.Base.Orientation) is not None:
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'ExifTags'

[2024-09-06 14:42:09,614][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 24, 'num_gpus': 0.125} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 24, 'num_gpus': 0.125}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
