[2024-09-20 17:46:22,788][flwr][INFO] - Starting Flower simulation, config: num_rounds=100, no round_timeout
[2024-09-20 17:46:26,069][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 256.0, 'memory': 150088159437.0, 'node:__internal_head__': 1.0, 'node:115.145.172.224': 1.0, 'object_store_memory': 68609211187.0, 'accelerator_type:G': 1.0, 'GPU': 1.0}
[2024-09-20 17:46:26,070][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-09-20 17:46:26,070][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 16, 'num_gpus': 0.5}
[2024-09-20 17:46:26,090][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
[2024-09-20 17:46:26,091][flwr][INFO] - [INIT]
[2024-09-20 17:46:26,091][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-20 17:46:32,657][flwr][INFO] - Received initial parameters from one random client
[2024-09-20 17:46:32,657][flwr][INFO] - Evaluating initial global parameters
[2024-09-20 17:46:43,751][flwr][INFO] - initial parameters (loss, other metrics): 226.76452708244324, {'accuracy': 0.11370944168371822}
[2024-09-20 17:46:43,751][flwr][INFO] - 
[2024-09-20 17:46:43,751][flwr][INFO] - [ROUND 1]
[2024-09-20 17:46:43,751][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:46:59,214][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:47:00,658][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-09-20 17:47:10,202][flwr][INFO] - fit progress: (1, 238.03488445281982, {'accuracy': 0.07132417421806489}, 26.451019858941436)
[2024-09-20 17:47:10,203][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:47:12,998][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:47:12,998][flwr][INFO] - 
[2024-09-20 17:47:12,998][flwr][INFO] - [ROUND 2]
[2024-09-20 17:47:12,998][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:47:17,646][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 17:47:17,647][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 17:47:24,087][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 17:47:35,830][flwr][INFO] - fit progress: (2, 241.5014524459839, {'accuracy': 0.09090909090909091}, 52.0790832079947)
[2024-09-20 17:47:35,831][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:47:38,562][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:47:38,562][flwr][INFO] - 
[2024-09-20 17:47:38,562][flwr][INFO] - [ROUND 3]
[2024-09-20 17:47:38,562][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:47:50,488][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:48:01,708][flwr][INFO] - fit progress: (3, 289.6629376411438, {'accuracy': 0.09090909090909091}, 77.95720944274217)
[2024-09-20 17:48:01,709][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:48:04,546][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:48:04,546][flwr][INFO] - 
[2024-09-20 17:48:04,547][flwr][INFO] - [ROUND 4]
[2024-09-20 17:48:04,547][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:48:18,348][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:48:29,813][flwr][INFO] - fit progress: (4, 515.0731108188629, {'accuracy': 0.1824028061970184}, 106.06240756670013)
[2024-09-20 17:48:29,814][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:48:32,293][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:48:32,293][flwr][INFO] - 
[2024-09-20 17:48:32,293][flwr][INFO] - [ROUND 5]
[2024-09-20 17:48:32,294][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:48:47,762][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:48:59,132][flwr][INFO] - fit progress: (5, 221.73927521705627, {'accuracy': 0.19467991815258695}, 135.38062045164406)
[2024-09-20 17:48:59,132][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:49:01,697][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:49:01,697][flwr][INFO] - 
[2024-09-20 17:49:01,697][flwr][INFO] - [ROUND 6]
[2024-09-20 17:49:01,697][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:49:13,972][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:49:26,575][flwr][INFO] - fit progress: (6, 218.7551109790802, {'accuracy': 0.16924875767319497}, 162.82373179960996)
[2024-09-20 17:49:26,575][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:49:29,285][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:49:29,286][flwr][INFO] - 
[2024-09-20 17:49:29,286][flwr][INFO] - [ROUND 7]
[2024-09-20 17:49:29,286][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:49:42,898][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:49:55,257][flwr][INFO] - fit progress: (7, 274.564816236496, {'accuracy': 0.1373867290266004}, 191.50623770896345)
[2024-09-20 17:49:55,258][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:49:58,484][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:49:58,484][flwr][INFO] - 
[2024-09-20 17:49:58,484][flwr][INFO] - [ROUND 8]
[2024-09-20 17:49:58,484][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:50:16,622][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:50:28,206][flwr][INFO] - fit progress: (8, 302.46582770347595, {'accuracy': 0.19467991815258695}, 224.45483074570075)
[2024-09-20 17:50:28,206][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:50:31,140][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:50:31,141][flwr][INFO] - 
[2024-09-20 17:50:31,141][flwr][INFO] - [ROUND 9]
[2024-09-20 17:50:31,141][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:50:45,189][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:50:57,216][flwr][INFO] - fit progress: (9, 232.1724978685379, {'accuracy': 0.19467991815258695}, 253.46543006692082)
[2024-09-20 17:50:57,217][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:50:59,558][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:50:59,558][flwr][INFO] - 
[2024-09-20 17:50:59,558][flwr][INFO] - [ROUND 10]
[2024-09-20 17:50:59,558][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:51:14,333][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:51:26,688][flwr][INFO] - fit progress: (10, 239.41824352741241, {'accuracy': 0.1373867290266004}, 282.93676090985537)
[2024-09-20 17:51:26,688][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:51:29,595][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:51:29,595][flwr][INFO] - 
[2024-09-20 17:51:29,595][flwr][INFO] - [ROUND 11]
[2024-09-20 17:51:29,595][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:51:48,201][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:52:00,349][flwr][INFO] - fit progress: (11, 239.22387027740479, {'accuracy': 0.16924875767319497}, 316.59812762076035)
[2024-09-20 17:52:00,350][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:52:03,546][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:52:03,546][flwr][INFO] - 
[2024-09-20 17:52:03,546][flwr][INFO] - [ROUND 12]
[2024-09-20 17:52:03,547][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:52:22,719][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:52:34,633][flwr][INFO] - fit progress: (12, 304.5178427696228, {'accuracy': 0.19467991815258695}, 350.88203378766775)
[2024-09-20 17:52:34,633][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:52:37,054][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:52:37,054][flwr][INFO] - 
[2024-09-20 17:52:37,054][flwr][INFO] - [ROUND 13]
[2024-09-20 17:52:37,054][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:52:43,127][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 17:52:43,127][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 17:52:45,790][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 17:52:58,689][flwr][INFO] - fit progress: (13, 225.38797342777252, {'accuracy': 0.19467991815258695}, 374.93810896156356)
[2024-09-20 17:52:58,690][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:53:01,328][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:53:01,328][flwr][INFO] - 
[2024-09-20 17:53:01,328][flwr][INFO] - [ROUND 14]
[2024-09-20 17:53:01,328][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:53:12,207][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:53:24,242][flwr][INFO] - fit progress: (14, 313.34109258651733, {'accuracy': 0.1373867290266004}, 400.4906194987707)
[2024-09-20 17:53:24,242][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:53:27,309][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:53:27,309][flwr][INFO] - 
[2024-09-20 17:53:27,309][flwr][INFO] - [ROUND 15]
[2024-09-20 17:53:27,309][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:53:37,724][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:53:50,113][flwr][INFO] - fit progress: (15, 221.74233961105347, {'accuracy': 0.1373867290266004}, 426.3620967245661)
[2024-09-20 17:53:50,114][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:53:52,695][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:53:52,695][flwr][INFO] - 
[2024-09-20 17:53:52,696][flwr][INFO] - [ROUND 16]
[2024-09-20 17:53:52,696][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:54:06,131][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 17:54:06,132][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 17:54:06,796][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 17:54:19,128][flwr][INFO] - fit progress: (16, 256.61250472068787, {'accuracy': 0.1373867290266004}, 455.376731346827)
[2024-09-20 17:54:19,128][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:54:21,550][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:54:21,550][flwr][INFO] - 
[2024-09-20 17:54:21,550][flwr][INFO] - [ROUND 17]
[2024-09-20 17:54:21,550][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:54:34,018][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:54:46,477][flwr][INFO] - fit progress: (17, 248.64436793327332, {'accuracy': 0.1373867290266004}, 482.72574046300724)
[2024-09-20 17:54:46,477][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:54:49,285][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:54:49,285][flwr][INFO] - 
[2024-09-20 17:54:49,285][flwr][INFO] - [ROUND 18]
[2024-09-20 17:54:49,285][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:55:09,265][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:55:20,540][flwr][INFO] - fit progress: (18, 240.28642106056213, {'accuracy': 0.19467991815258695}, 516.7890624320135)
[2024-09-20 17:55:20,541][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:55:23,058][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:55:23,058][flwr][INFO] - 
[2024-09-20 17:55:23,058][flwr][INFO] - [ROUND 19]
[2024-09-20 17:55:23,058][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:55:37,606][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:55:49,479][flwr][INFO] - fit progress: (19, 249.1623079776764, {'accuracy': 0.07132417421806489}, 545.7276971926913)
[2024-09-20 17:55:49,479][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:55:51,881][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:55:51,881][flwr][INFO] - 
[2024-09-20 17:55:51,881][flwr][INFO] - [ROUND 20]
[2024-09-20 17:55:51,882][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:56:12,840][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:56:24,645][flwr][INFO] - fit progress: (20, 226.39255845546722, {'accuracy': 0.1824028061970184}, 580.8939856668003)
[2024-09-20 17:56:24,645][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:56:27,551][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:56:27,552][flwr][INFO] - 
[2024-09-20 17:56:27,552][flwr][INFO] - [ROUND 21]
[2024-09-20 17:56:27,552][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:56:31,957][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 17:56:31,958][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 17:56:36,930][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 17:56:48,984][flwr][INFO] - fit progress: (21, 231.67327654361725, {'accuracy': 0.1373867290266004}, 605.233398317825)
[2024-09-20 17:56:48,985][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:56:51,347][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:56:51,347][flwr][INFO] - 
[2024-09-20 17:56:51,347][flwr][INFO] - [ROUND 22]
[2024-09-20 17:56:51,348][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:57:05,089][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:57:17,537][flwr][INFO] - fit progress: (22, 220.8802046775818, {'accuracy': 0.19467991815258695}, 633.7863236479461)
[2024-09-20 17:57:17,538][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:57:20,145][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:57:20,146][flwr][INFO] - 
[2024-09-20 17:57:20,146][flwr][INFO] - [ROUND 23]
[2024-09-20 17:57:20,146][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:57:35,503][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:57:47,221][flwr][INFO] - fit progress: (23, 230.86781120300293, {'accuracy': 0.16924875767319497}, 663.4703651559539)
[2024-09-20 17:57:47,222][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:57:49,899][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:57:49,899][flwr][INFO] - 
[2024-09-20 17:57:49,899][flwr][INFO] - [ROUND 24]
[2024-09-20 17:57:49,899][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:58:10,552][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:58:22,744][flwr][INFO] - fit progress: (24, 228.09581637382507, {'accuracy': 0.1824028061970184}, 698.9927133829333)
[2024-09-20 17:58:22,744][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:58:25,470][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:58:25,470][flwr][INFO] - 
[2024-09-20 17:58:25,470][flwr][INFO] - [ROUND 25]
[2024-09-20 17:58:25,470][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:58:44,048][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:58:56,806][flwr][INFO] - fit progress: (25, 234.344052195549, {'accuracy': 0.19467991815258695}, 733.0544867748395)
[2024-09-20 17:58:56,806][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:58:59,600][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:58:59,600][flwr][INFO] - 
[2024-09-20 17:58:59,600][flwr][INFO] - [ROUND 26]
[2024-09-20 17:58:59,600][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:59:23,202][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 17:59:35,010][flwr][INFO] - fit progress: (26, 218.2693328857422, {'accuracy': 0.19467991815258695}, 771.259127703961)
[2024-09-20 17:59:35,011][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 17:59:37,419][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 17:59:37,419][flwr][INFO] - 
[2024-09-20 17:59:37,419][flwr][INFO] - [ROUND 27]
[2024-09-20 17:59:37,420][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 17:59:53,216][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:00:04,915][flwr][INFO] - fit progress: (27, 220.2818329334259, {'accuracy': 0.24934229757380882}, 801.164400386624)
[2024-09-20 18:00:04,916][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:00:07,692][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:00:07,693][flwr][INFO] - 
[2024-09-20 18:00:07,693][flwr][INFO] - [ROUND 28]
[2024-09-20 18:00:07,693][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:00:20,068][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:00:31,476][flwr][INFO] - fit progress: (28, 221.04694092273712, {'accuracy': 0.1824028061970184}, 827.7248369175941)
[2024-09-20 18:00:31,476][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:00:33,962][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:00:33,963][flwr][INFO] - 
[2024-09-20 18:00:33,963][flwr][INFO] - [ROUND 29]
[2024-09-20 18:00:33,963][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:00:35,052][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:00:35,052][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:00:42,061][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:00:54,222][flwr][INFO] - fit progress: (29, 233.78054022789001, {'accuracy': 0.1373867290266004}, 850.4713155906647)
[2024-09-20 18:00:54,223][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:00:56,682][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:00:56,683][flwr][INFO] - 
[2024-09-20 18:00:56,683][flwr][INFO] - [ROUND 30]
[2024-09-20 18:00:56,683][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:01:08,907][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:01:21,302][flwr][INFO] - fit progress: (30, 221.74854588508606, {'accuracy': 0.1373867290266004}, 877.5509180827066)
[2024-09-20 18:01:21,303][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:01:22,477][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:01:22,477][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:01:23,467][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-20 18:01:23,467][flwr][INFO] - 
[2024-09-20 18:01:23,467][flwr][INFO] - [ROUND 31]
[2024-09-20 18:01:23,467][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:01:35,389][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:01:47,000][flwr][INFO] - fit progress: (31, 456.94386315345764, {'accuracy': 0.1824028061970184}, 903.2491361326538)
[2024-09-20 18:01:47,000][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:01:49,595][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:01:49,596][flwr][INFO] - 
[2024-09-20 18:01:49,596][flwr][INFO] - [ROUND 32]
[2024-09-20 18:01:49,596][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:02:04,222][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:02:16,889][flwr][INFO] - fit progress: (32, 598.0173711776733, {'accuracy': 0.19467991815258695}, 933.1379480906762)
[2024-09-20 18:02:16,890][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:02:19,438][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:02:19,438][flwr][INFO] - 
[2024-09-20 18:02:19,438][flwr][INFO] - [ROUND 33]
[2024-09-20 18:02:19,438][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:02:39,969][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:02:51,974][flwr][INFO] - fit progress: (33, 221.48068571090698, {'accuracy': 0.19467991815258695}, 968.2234941236675)
[2024-09-20 18:02:51,975][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:02:54,518][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:02:54,519][flwr][INFO] - 
[2024-09-20 18:02:54,519][flwr][INFO] - [ROUND 34]
[2024-09-20 18:02:54,519][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:03:13,022][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:03:25,231][flwr][INFO] - fit progress: (34, 230.64493417739868, {'accuracy': 0.16924875767319497}, 1001.4803340248764)
[2024-09-20 18:03:25,232][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:03:27,991][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:03:27,991][flwr][INFO] - 
[2024-09-20 18:03:27,992][flwr][INFO] - [ROUND 35]
[2024-09-20 18:03:27,992][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:03:41,533][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:03:54,312][flwr][INFO] - fit progress: (35, 222.84636735916138, {'accuracy': 0.16924875767319497}, 1030.5606060177088)
[2024-09-20 18:03:54,312][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:03:56,718][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:03:56,719][flwr][INFO] - 
[2024-09-20 18:03:56,719][flwr][INFO] - [ROUND 36]
[2024-09-20 18:03:56,719][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:04:15,774][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:04:28,360][flwr][INFO] - fit progress: (36, 328.5816056728363, {'accuracy': 0.19467991815258695}, 1064.6093840645626)
[2024-09-20 18:04:28,361][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:04:31,092][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:04:31,092][flwr][INFO] - 
[2024-09-20 18:04:31,092][flwr][INFO] - [ROUND 37]
[2024-09-20 18:04:31,092][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:04:45,047][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:04:57,557][flwr][INFO] - fit progress: (37, 220.15153753757477, {'accuracy': 0.07132417421806489}, 1093.806284318678)
[2024-09-20 18:04:57,558][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:05:00,006][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:05:00,006][flwr][INFO] - 
[2024-09-20 18:05:00,006][flwr][INFO] - [ROUND 38]
[2024-09-20 18:05:00,006][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:05:00,957][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:05:00,957][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:05:11,881][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:05:25,006][flwr][INFO] - fit progress: (38, 223.04044568538666, {'accuracy': 0.19467991815258695}, 1121.2551274616271)
[2024-09-20 18:05:25,007][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:05:27,648][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:05:27,648][flwr][INFO] - 
[2024-09-20 18:05:27,648][flwr][INFO] - [ROUND 39]
[2024-09-20 18:05:27,648][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:05:43,889][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:05:56,115][flwr][INFO] - fit progress: (39, 288.0362346172333, {'accuracy': 0.1373867290266004}, 1152.3636328019202)
[2024-09-20 18:05:56,115][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:05:58,758][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:05:58,758][flwr][INFO] - 
[2024-09-20 18:05:58,758][flwr][INFO] - [ROUND 40]
[2024-09-20 18:05:58,758][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:06:22,325][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:06:34,639][flwr][INFO] - fit progress: (40, 241.455011844635, {'accuracy': 0.1824028061970184}, 1190.8880960298702)
[2024-09-20 18:06:34,639][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:06:37,545][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:06:37,545][flwr][INFO] - 
[2024-09-20 18:06:37,545][flwr][INFO] - [ROUND 41]
[2024-09-20 18:06:37,546][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:06:54,684][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:07:06,990][flwr][INFO] - fit progress: (41, 223.49810028076172, {'accuracy': 0.16924875767319497}, 1223.2387051116675)
[2024-09-20 18:07:06,990][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:07:09,539][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:07:09,539][flwr][INFO] - 
[2024-09-20 18:07:09,540][flwr][INFO] - [ROUND 42]
[2024-09-20 18:07:09,540][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:07:26,161][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:07:39,102][flwr][INFO] - fit progress: (42, 326.53988671302795, {'accuracy': 0.07132417421806489}, 1255.3507656226866)
[2024-09-20 18:07:39,102][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:07:41,790][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:07:41,791][flwr][INFO] - 
[2024-09-20 18:07:41,791][flwr][INFO] - [ROUND 43]
[2024-09-20 18:07:41,791][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:07:54,916][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:08:07,515][flwr][INFO] - fit progress: (43, 308.7781081199646, {'accuracy': 0.1581408944752996}, 1283.7638692245819)
[2024-09-20 18:08:07,516][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:08:10,258][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:08:10,258][flwr][INFO] - 
[2024-09-20 18:08:10,258][flwr][INFO] - [ROUND 44]
[2024-09-20 18:08:10,258][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:08:23,771][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:08:36,179][flwr][INFO] - fit progress: (44, 242.62829911708832, {'accuracy': 0.1373867290266004}, 1312.4276984618045)
[2024-09-20 18:08:36,179][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:08:38,773][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:08:38,773][flwr][INFO] - 
[2024-09-20 18:08:38,774][flwr][INFO] - [ROUND 45]
[2024-09-20 18:08:38,774][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:08:42,744][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:08:42,744][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:08:55,193][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:09:07,015][flwr][INFO] - fit progress: (45, 464.49644351005554, {'accuracy': 0.16924875767319497}, 1343.2641932638362)
[2024-09-20 18:09:07,016][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:09:09,874][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:09:09,874][flwr][INFO] - 
[2024-09-20 18:09:09,875][flwr][INFO] - [ROUND 46]
[2024-09-20 18:09:09,875][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:09:22,189][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:09:34,042][flwr][INFO] - fit progress: (46, 220.93594527244568, {'accuracy': 0.19467991815258695}, 1370.291480553802)
[2024-09-20 18:09:34,043][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:09:36,823][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:09:36,823][flwr][INFO] - 
[2024-09-20 18:09:36,824][flwr][INFO] - [ROUND 47]
[2024-09-20 18:09:36,824][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:09:56,575][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:10:09,185][flwr][INFO] - fit progress: (47, 220.8076663017273, {'accuracy': 0.19467991815258695}, 1405.4334437227808)
[2024-09-20 18:10:09,185][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:10:11,875][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:10:11,876][flwr][INFO] - 
[2024-09-20 18:10:11,876][flwr][INFO] - [ROUND 48]
[2024-09-20 18:10:11,876][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:10:22,697][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:10:35,005][flwr][INFO] - fit progress: (48, 450.6055371761322, {'accuracy': 0.19467991815258695}, 1431.2535776370205)
[2024-09-20 18:10:35,005][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:10:37,752][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:10:37,752][flwr][INFO] - 
[2024-09-20 18:10:37,752][flwr][INFO] - [ROUND 49]
[2024-09-20 18:10:37,752][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:10:51,246][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:11:02,998][flwr][INFO] - fit progress: (49, 267.8551571369171, {'accuracy': 0.29026600409237063}, 1459.2468487150036)
[2024-09-20 18:11:02,998][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:11:05,297][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:11:05,298][flwr][INFO] - 
[2024-09-20 18:11:05,298][flwr][INFO] - [ROUND 50]
[2024-09-20 18:11:05,298][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:11:27,463][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:11:39,509][flwr][INFO] - fit progress: (50, 222.25239646434784, {'accuracy': 0.19467991815258695}, 1495.7580782505684)
[2024-09-20 18:11:39,509][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:11:42,040][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:11:42,040][flwr][INFO] - 
[2024-09-20 18:11:42,040][flwr][INFO] - [ROUND 51]
[2024-09-20 18:11:42,040][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:11:51,116][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:11:51,116][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:11:51,117][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:12:03,660][flwr][INFO] - fit progress: (51, 235.25658452510834, {'accuracy': 0.1824028061970184}, 1519.9087506048381)
[2024-09-20 18:12:03,660][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:12:06,336][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:12:06,337][flwr][INFO] - 
[2024-09-20 18:12:06,337][flwr][INFO] - [ROUND 52]
[2024-09-20 18:12:06,337][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:12:28,339][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:12:41,122][flwr][INFO] - fit progress: (52, 244.26254832744598, {'accuracy': 0.16924875767319497}, 1557.37123323977)
[2024-09-20 18:12:41,123][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:12:43,536][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:12:43,536][flwr][INFO] - 
[2024-09-20 18:12:43,536][flwr][INFO] - [ROUND 53]
[2024-09-20 18:12:43,536][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:13:03,025][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:13:14,963][flwr][INFO] - fit progress: (53, 285.55648851394653, {'accuracy': 0.19467991815258695}, 1591.2116822679527)
[2024-09-20 18:13:14,963][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:13:17,686][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:13:17,686][flwr][INFO] - 
[2024-09-20 18:13:17,686][flwr][INFO] - [ROUND 54]
[2024-09-20 18:13:17,686][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:13:29,557][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:13:41,639][flwr][INFO] - fit progress: (54, 247.25791156291962, {'accuracy': 0.1824028061970184}, 1617.887925285846)
[2024-09-20 18:13:41,640][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:13:44,391][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:13:44,391][flwr][INFO] - 
[2024-09-20 18:13:44,391][flwr][INFO] - [ROUND 55]
[2024-09-20 18:13:44,391][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:14:00,803][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:14:13,908][flwr][INFO] - fit progress: (55, 364.3339512348175, {'accuracy': 0.19467991815258695}, 1650.1571803740226)
[2024-09-20 18:14:13,909][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:14:16,394][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:14:16,394][flwr][INFO] - 
[2024-09-20 18:14:16,394][flwr][INFO] - [ROUND 56]
[2024-09-20 18:14:16,394][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:14:29,981][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:14:42,559][flwr][INFO] - fit progress: (56, 331.67673563957214, {'accuracy': 0.1373867290266004}, 1678.808405497577)
[2024-09-20 18:14:42,560][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:14:45,180][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:14:45,180][flwr][INFO] - 
[2024-09-20 18:14:45,180][flwr][INFO] - [ROUND 57]
[2024-09-20 18:14:45,180][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:15:03,806][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:15:15,422][flwr][INFO] - fit progress: (57, 264.59787690639496, {'accuracy': 0.1824028061970184}, 1711.6709321527742)
[2024-09-20 18:15:15,422][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:15:18,037][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:15:18,037][flwr][INFO] - 
[2024-09-20 18:15:18,037][flwr][INFO] - [ROUND 58]
[2024-09-20 18:15:18,037][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:15:38,491][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:15:50,732][flwr][INFO] - fit progress: (58, 251.5600986480713, {'accuracy': 0.1824028061970184}, 1746.9806344448589)
[2024-09-20 18:15:50,732][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:15:53,181][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:15:53,181][flwr][INFO] - 
[2024-09-20 18:15:53,181][flwr][INFO] - [ROUND 59]
[2024-09-20 18:15:53,181][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:16:05,945][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:16:17,440][flwr][INFO] - fit progress: (59, 219.04040503501892, {'accuracy': 0.1824028061970184}, 1773.6894767466001)
[2024-09-20 18:16:17,441][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:16:19,840][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:16:19,840][flwr][INFO] - 
[2024-09-20 18:16:19,841][flwr][INFO] - [ROUND 60]
[2024-09-20 18:16:19,841][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:16:33,588][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:16:45,957][flwr][INFO] - fit progress: (60, 220.8660159111023, {'accuracy': 0.1824028061970184}, 1802.2056990228593)
[2024-09-20 18:16:45,957][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:16:48,401][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:16:48,401][flwr][INFO] - 
[2024-09-20 18:16:48,401][flwr][INFO] - [ROUND 61]
[2024-09-20 18:16:48,402][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:17:08,076][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:17:19,948][flwr][INFO] - fit progress: (61, 270.81936025619507, {'accuracy': 0.19467991815258695}, 1836.1972967758775)
[2024-09-20 18:17:19,949][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:17:22,953][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:17:22,953][flwr][INFO] - 
[2024-09-20 18:17:22,954][flwr][INFO] - [ROUND 62]
[2024-09-20 18:17:22,954][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:17:36,038][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:17:48,106][flwr][INFO] - fit progress: (62, 242.4165644645691, {'accuracy': 0.1824028061970184}, 1864.3549172007479)
[2024-09-20 18:17:48,106][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:17:50,612][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:17:50,612][flwr][INFO] - 
[2024-09-20 18:17:50,612][flwr][INFO] - [ROUND 63]
[2024-09-20 18:17:50,612][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:18:03,001][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:18:15,437][flwr][INFO] - fit progress: (63, 348.6141564846039, {'accuracy': 0.1824028061970184}, 1891.6856977497227)
[2024-09-20 18:18:15,437][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:18:17,892][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:18:17,892][flwr][INFO] - 
[2024-09-20 18:18:17,892][flwr][INFO] - [ROUND 64]
[2024-09-20 18:18:17,893][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:18:46,216][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:18:57,778][flwr][INFO] - fit progress: (64, 296.0308060646057, {'accuracy': 0.19467991815258695}, 1934.0274781589396)
[2024-09-20 18:18:57,779][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:19:00,362][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:19:00,362][flwr][INFO] - 
[2024-09-20 18:19:00,362][flwr][INFO] - [ROUND 65]
[2024-09-20 18:19:00,363][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:19:16,615][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:19:27,571][flwr][INFO] - fit progress: (65, 290.46275782585144, {'accuracy': 0.19467991815258695}, 1963.8197221020237)
[2024-09-20 18:19:27,571][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:19:28,787][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:19:28,787][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:19:29,836][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-20 18:19:29,836][flwr][INFO] - 
[2024-09-20 18:19:29,836][flwr][INFO] - [ROUND 66]
[2024-09-20 18:19:29,837][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:19:49,426][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:20:00,440][flwr][INFO] - fit progress: (66, 250.3443944454193, {'accuracy': 0.19467991815258695}, 1996.6887461049482)
[2024-09-20 18:20:00,440][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:20:03,453][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:20:03,454][flwr][INFO] - 
[2024-09-20 18:20:03,454][flwr][INFO] - [ROUND 67]
[2024-09-20 18:20:03,454][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:20:17,084][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:20:28,878][flwr][INFO] - fit progress: (67, 229.02895879745483, {'accuracy': 0.19467991815258695}, 2025.1267873425968)
[2024-09-20 18:20:28,878][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:20:31,358][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:20:31,359][flwr][INFO] - 
[2024-09-20 18:20:31,359][flwr][INFO] - [ROUND 68]
[2024-09-20 18:20:31,359][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:20:45,011][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:20:56,604][flwr][INFO] - fit progress: (68, 219.4711730480194, {'accuracy': 0.19467991815258695}, 2052.8524566609412)
[2024-09-20 18:20:56,604][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:20:59,202][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:20:59,202][flwr][INFO] - 
[2024-09-20 18:20:59,202][flwr][INFO] - [ROUND 69]
[2024-09-20 18:20:59,202][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:21:15,706][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:21:26,885][flwr][INFO] - fit progress: (69, 226.52731728553772, {'accuracy': 0.19467991815258695}, 2083.133863983676)
[2024-09-20 18:21:26,885][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:21:29,424][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:21:29,424][flwr][INFO] - 
[2024-09-20 18:21:29,424][flwr][INFO] - [ROUND 70]
[2024-09-20 18:21:29,425][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:21:41,120][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:21:53,071][flwr][INFO] - fit progress: (70, 219.1491663455963, {'accuracy': 0.19467991815258695}, 2109.3196565187536)
[2024-09-20 18:21:53,071][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:21:56,108][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:21:56,108][flwr][INFO] - 
[2024-09-20 18:21:56,108][flwr][INFO] - [ROUND 71]
[2024-09-20 18:21:56,108][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:22:14,192][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:22:25,703][flwr][INFO] - fit progress: (71, 280.5509045124054, {'accuracy': 0.19467991815258695}, 2141.9517220216803)
[2024-09-20 18:22:25,703][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:22:28,237][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:22:28,237][flwr][INFO] - 
[2024-09-20 18:22:28,237][flwr][INFO] - [ROUND 72]
[2024-09-20 18:22:28,237][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:22:45,006][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:22:56,979][flwr][INFO] - fit progress: (72, 313.252653837204, {'accuracy': 0.19467991815258695}, 2173.2279820409603)
[2024-09-20 18:22:56,979][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:22:59,406][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:22:59,406][flwr][INFO] - 
[2024-09-20 18:22:59,406][flwr][INFO] - [ROUND 73]
[2024-09-20 18:22:59,406][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:23:13,098][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:23:25,138][flwr][INFO] - fit progress: (73, 230.5376844406128, {'accuracy': 0.19467991815258695}, 2201.3871028018184)
[2024-09-20 18:23:25,139][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:23:27,833][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:23:27,833][flwr][INFO] - 
[2024-09-20 18:23:27,833][flwr][INFO] - [ROUND 74]
[2024-09-20 18:23:27,833][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:23:40,496][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:23:52,085][flwr][INFO] - fit progress: (74, 219.6373189687729, {'accuracy': 0.19467991815258695}, 2228.3336973637342)
[2024-09-20 18:23:52,085][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:23:54,617][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:23:54,617][flwr][INFO] - 
[2024-09-20 18:23:54,617][flwr][INFO] - [ROUND 75]
[2024-09-20 18:23:54,618][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:24:18,462][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:24:30,586][flwr][INFO] - fit progress: (75, 265.5568515062332, {'accuracy': 0.1824028061970184}, 2266.8351172786206)
[2024-09-20 18:24:30,586][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:24:33,223][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:24:33,223][flwr][INFO] - 
[2024-09-20 18:24:33,223][flwr][INFO] - [ROUND 76]
[2024-09-20 18:24:33,223][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:24:49,623][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:25:00,943][flwr][INFO] - fit progress: (76, 241.09146976470947, {'accuracy': 0.16924875767319497}, 2297.1922017829493)
[2024-09-20 18:25:00,943][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:25:03,370][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:25:03,370][flwr][INFO] - 
[2024-09-20 18:25:03,371][flwr][INFO] - [ROUND 77]
[2024-09-20 18:25:03,371][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:25:16,679][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:25:28,815][flwr][INFO] - fit progress: (77, 217.35157907009125, {'accuracy': 0.19467991815258695}, 2325.0636594225653)
[2024-09-20 18:25:28,815][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:25:29,762][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:25:29,763][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:25:30,787][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-20 18:25:30,787][flwr][INFO] - 
[2024-09-20 18:25:30,787][flwr][INFO] - [ROUND 78]
[2024-09-20 18:25:30,787][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:25:42,419][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:25:54,835][flwr][INFO] - fit progress: (78, 220.32001340389252, {'accuracy': 0.19467991815258695}, 2351.083571168594)
[2024-09-20 18:25:54,835][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:25:57,414][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:25:57,414][flwr][INFO] - 
[2024-09-20 18:25:57,414][flwr][INFO] - [ROUND 79]
[2024-09-20 18:25:57,414][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:26:15,110][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:26:26,366][flwr][INFO] - fit progress: (79, 216.60831797122955, {'accuracy': 0.19467991815258695}, 2382.6149734789506)
[2024-09-20 18:26:26,366][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:26:29,209][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:26:29,210][flwr][INFO] - 
[2024-09-20 18:26:29,210][flwr][INFO] - [ROUND 80]
[2024-09-20 18:26:29,210][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:26:47,996][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:27:00,509][flwr][INFO] - fit progress: (80, 251.66179943084717, {'accuracy': 0.1824028061970184}, 2416.7578244009055)
[2024-09-20 18:27:00,510][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:27:03,975][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:27:03,976][flwr][INFO] - 
[2024-09-20 18:27:03,976][flwr][INFO] - [ROUND 81]
[2024-09-20 18:27:03,976][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:27:16,230][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:27:28,221][flwr][INFO] - fit progress: (81, 225.61053836345673, {'accuracy': 0.1824028061970184}, 2444.4696554047987)
[2024-09-20 18:27:28,221][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:27:30,844][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:27:30,844][flwr][INFO] - 
[2024-09-20 18:27:30,844][flwr][INFO] - [ROUND 82]
[2024-09-20 18:27:30,844][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:27:39,468][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:27:39,469][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:27:46,749][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:27:58,852][flwr][INFO] - fit progress: (82, 273.85055005550385, {'accuracy': 0.16924875767319497}, 2475.100702386815)
[2024-09-20 18:27:58,852][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:28:01,362][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:28:01,362][flwr][INFO] - 
[2024-09-20 18:28:01,362][flwr][INFO] - [ROUND 83]
[2024-09-20 18:28:01,363][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:28:13,032][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:28:24,912][flwr][INFO] - fit progress: (83, 226.50710272789001, {'accuracy': 0.16924875767319497}, 2501.1609803838655)
[2024-09-20 18:28:24,913][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:28:27,859][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:28:27,860][flwr][INFO] - 
[2024-09-20 18:28:27,860][flwr][INFO] - [ROUND 84]
[2024-09-20 18:28:27,860][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:28:44,115][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:28:55,914][flwr][INFO] - fit progress: (84, 269.0091918706894, {'accuracy': 0.16924875767319497}, 2532.1627053958364)
[2024-09-20 18:28:55,914][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:28:58,496][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:28:58,496][flwr][INFO] - 
[2024-09-20 18:28:58,496][flwr][INFO] - [ROUND 85]
[2024-09-20 18:28:58,496][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:29:02,922][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:29:02,922][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:29:09,847][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:29:20,647][flwr][INFO] - fit progress: (85, 260.9620455503464, {'accuracy': 0.16924875767319497}, 2556.895890052896)
[2024-09-20 18:29:20,647][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:29:22,024][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:29:22,030][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:29:22,838][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-20 18:29:22,838][flwr][INFO] - 
[2024-09-20 18:29:22,838][flwr][INFO] - [ROUND 86]
[2024-09-20 18:29:22,838][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:29:38,795][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:29:50,388][flwr][INFO] - fit progress: (86, 223.18651282787323, {'accuracy': 0.16924875767319497}, 2586.6366692548618)
[2024-09-20 18:29:50,388][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:29:52,697][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:29:52,698][flwr][INFO] - 
[2024-09-20 18:29:52,698][flwr][INFO] - [ROUND 87]
[2024-09-20 18:29:52,698][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:30:07,196][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:30:18,663][flwr][INFO] - fit progress: (87, 236.18059265613556, {'accuracy': 0.1824028061970184}, 2614.912345883902)
[2024-09-20 18:30:18,664][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:30:21,544][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:30:21,544][flwr][INFO] - 
[2024-09-20 18:30:21,544][flwr][INFO] - [ROUND 88]
[2024-09-20 18:30:21,544][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:30:41,470][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:30:55,145][flwr][INFO] - fit progress: (88, 239.2525885105133, {'accuracy': 0.1824028061970184}, 2651.39412515983)
[2024-09-20 18:30:55,146][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:30:57,796][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:30:57,797][flwr][INFO] - 
[2024-09-20 18:30:57,797][flwr][INFO] - [ROUND 89]
[2024-09-20 18:30:57,797][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:31:09,865][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:31:23,663][flwr][INFO] - fit progress: (89, 247.62877345085144, {'accuracy': 0.1824028061970184}, 2679.9114813557826)
[2024-09-20 18:31:23,663][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:31:26,233][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:31:26,233][flwr][INFO] - 
[2024-09-20 18:31:26,233][flwr][INFO] - [ROUND 90]
[2024-09-20 18:31:26,233][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:31:39,658][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:31:52,749][flwr][INFO] - fit progress: (90, 232.0524388551712, {'accuracy': 0.1824028061970184}, 2708.997799441684)
[2024-09-20 18:31:52,749][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:31:55,823][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:31:55,823][flwr][INFO] - 
[2024-09-20 18:31:55,823][flwr][INFO] - [ROUND 91]
[2024-09-20 18:31:55,823][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:32:00,997][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:32:00,998][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517974, ip=115.145.172.224, actor_id=9a0b25b5e7d3e05f03e4baf701000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7f0398095930>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:32:08,180][flwr][INFO] - aggregate_fit: received 4 results and 1 failures
[2024-09-20 18:32:20,447][flwr][INFO] - fit progress: (91, 309.10893511772156, {'accuracy': 0.1824028061970184}, 2736.6960996119305)
[2024-09-20 18:32:20,447][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:32:23,088][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:32:23,088][flwr][INFO] - 
[2024-09-20 18:32:23,088][flwr][INFO] - [ROUND 92]
[2024-09-20 18:32:23,088][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:32:42,666][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:32:54,103][flwr][INFO] - fit progress: (92, 260.8995577096939, {'accuracy': 0.1824028061970184}, 2770.3515956248157)
[2024-09-20 18:32:54,103][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:32:56,608][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:32:56,608][flwr][INFO] - 
[2024-09-20 18:32:56,608][flwr][INFO] - [ROUND 93]
[2024-09-20 18:32:56,608][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:33:08,653][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:33:21,326][flwr][INFO] - fit progress: (93, 240.86634182929993, {'accuracy': 0.07132417421806489}, 2797.574920120649)
[2024-09-20 18:33:21,326][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:33:23,936][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:33:23,937][flwr][INFO] - 
[2024-09-20 18:33:23,937][flwr][INFO] - [ROUND 94]
[2024-09-20 18:33:23,937][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:33:41,608][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:33:54,256][flwr][INFO] - fit progress: (94, 223.34192621707916, {'accuracy': 0.19467991815258695}, 2830.504835523665)
[2024-09-20 18:33:54,256][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:33:56,596][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:33:56,597][flwr][INFO] - 
[2024-09-20 18:33:56,597][flwr][INFO] - [ROUND 95]
[2024-09-20 18:33:56,597][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:34:09,421][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:34:21,773][flwr][INFO] - fit progress: (95, 220.11687457561493, {'accuracy': 0.1824028061970184}, 2858.0222030538134)
[2024-09-20 18:34:21,774][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:34:24,149][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:34:24,149][flwr][INFO] - 
[2024-09-20 18:34:24,149][flwr][INFO] - [ROUND 96]
[2024-09-20 18:34:24,149][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:34:37,579][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:34:49,326][flwr][INFO] - fit progress: (96, 219.79442286491394, {'accuracy': 0.1824028061970184}, 2885.5745999808423)
[2024-09-20 18:34:49,326][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:34:51,694][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:34:51,694][flwr][INFO] - 
[2024-09-20 18:34:51,694][flwr][INFO] - [ROUND 97]
[2024-09-20 18:34:51,694][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:35:02,721][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:35:14,961][flwr][INFO] - fit progress: (97, 223.28397452831268, {'accuracy': 0.1824028061970184}, 2911.210280911997)
[2024-09-20 18:35:14,962][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:35:17,872][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:35:17,872][flwr][INFO] - 
[2024-09-20 18:35:17,872][flwr][INFO] - [ROUND 98]
[2024-09-20 18:35:17,872][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:35:31,194][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:35:43,142][flwr][INFO] - fit progress: (98, 221.97872304916382, {'accuracy': 0.1824028061970184}, 2939.391010226682)
[2024-09-20 18:35:43,142][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:35:43,911][flwr][ERROR] - Traceback (most recent call last):
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 94, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 398, in get_client_result
    return self._fetch_future_result(cid)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 279, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/abdenour/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

[2024-09-20 18:35:43,912][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 143, in __call__
    return self._call(message, context)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 95, in handle_legacy_message_from_msgtype
    client = client_fn(context)
  File "/home/abdenour/fl_with_flower/fedavg_vgg16/fedavg_vgg16/client.py", line 92, in client_fn
    client_dataset_splits = client_dataset.train_test_split(test_size=0.1, seed=42)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 567, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/fingerprint.py", line 482, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/home/abdenour/.local/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4587, in train_test_split
    raise ValueError(
ValueError: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=3517973, ip=115.145.172.224, actor_id=09a581886006e0bfbb525e9201000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x7fd87c54d960>)
  File "/home/abdenour/.local/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 63, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: With n_samples=1, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-09-20 18:35:45,546][flwr][INFO] - aggregate_evaluate: received 1 results and 1 failures
[2024-09-20 18:35:45,546][flwr][INFO] - 
[2024-09-20 18:35:45,547][flwr][INFO] - [ROUND 99]
[2024-09-20 18:35:45,547][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:35:59,598][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:36:11,431][flwr][INFO] - fit progress: (99, 223.54950189590454, {'accuracy': 0.16924875767319497}, 2967.679833021015)
[2024-09-20 18:36:11,432][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:36:13,827][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:36:13,827][flwr][INFO] - 
[2024-09-20 18:36:13,827][flwr][INFO] - [ROUND 100]
[2024-09-20 18:36:13,828][flwr][INFO] - configure_fit: strategy sampled 5 clients (out of 50)
[2024-09-20 18:36:26,656][flwr][INFO] - aggregate_fit: received 5 results and 0 failures
[2024-09-20 18:36:37,874][flwr][INFO] - fit progress: (100, 217.55576169490814, {'accuracy': 0.1824028061970184}, 2994.123391123023)
[2024-09-20 18:36:37,875][flwr][INFO] - configure_evaluate: strategy sampled 2 clients (out of 50)
[2024-09-20 18:36:40,334][flwr][INFO] - aggregate_evaluate: received 2 results and 0 failures
[2024-09-20 18:36:40,497][flwr][INFO] - 
[2024-09-20 18:36:40,497][flwr][INFO] - [SUMMARY]
[2024-09-20 18:36:40,497][flwr][INFO] - Run finished 100 round(s) in 2996.58s
[2024-09-20 18:36:40,500][flwr][INFO] - 	History (loss, distributed):
[2024-09-20 18:36:40,500][flwr][INFO] - 		round 1: 2.069375991821289
[2024-09-20 18:36:40,500][flwr][INFO] - 		round 2: 1.5784782038794622
[2024-09-20 18:36:40,500][flwr][INFO] - 		round 3: 3.9212178230285644
[2024-09-20 18:36:40,500][flwr][INFO] - 		round 4: 5.1159129593823405
[2024-09-20 18:36:40,500][flwr][INFO] - 		round 5: 1.95104498722974
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 6: 1.9819073463553813
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 7: 3.7062351405620575
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 8: 4.650707878050257
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 9: 1.8702676472840485
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 10: 3.1927158465752234
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 11: 4.038717299699783
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 12: 2.2226469004026024
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 13: 1.848113521285679
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 14: 1.8940544046204666
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 15: 2.053009067262922
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 16: 1.7816875551057898
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 17: 3.8518588414063326
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 18: 2.843622689606041
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 19: 3.138721592286054
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 20: 2.9207026226068633
[2024-09-20 18:36:40,501][flwr][INFO] - 		round 21: 2.42925164103508
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 22: 2.010087044842272
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 23: 2.121665596961975
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 24: 2.0525514602661135
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 25: 2.3184246025728377
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 26: 2.3344229304272197
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 27: 2.09604229927063
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 28: 2.218003193537394
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 29: 2.046025744298609
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 30: 2.009023904800415
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 31: 6.384697164808001
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 32: 5.215981872876485
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 33: 1.643320784849279
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 34: 2.556256192071097
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 35: 2.044339156150818
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 36: 1.5684010452694364
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 37: 1.9168551872516502
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 38: 2.1393023055532705
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 39: 4.669693067962048
[2024-09-20 18:36:40,502][flwr][INFO] - 		round 40: 2.2789281845092773
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 41: 2.154173254966736
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 42: 5.7563666858673095
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 43: 1.50031445423762
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 44: 1.7769354714287653
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 45: 6.945053612484651
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 46: 2.1547314795580776
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 47: 1.9414534016891762
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 48: 4.061887714960804
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 49: 2.240581176831172
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 50: 1.5245214038425021
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 51: 3.1812734263283864
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 52: 3.9210898876190186
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 53: 2.1900373968211087
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 54: 2.555543465273721
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 55: 3.2250498911229575
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 56: 5.168289007963957
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 57: 2.419065282344818
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 58: 3.953941135406494
[2024-09-20 18:36:40,503][flwr][INFO] - 		round 59: 2.2629288893479567
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 60: 1.935929901070065
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 61: 2.622378647327423
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 62: 1.5181811332702637
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 63: 4.37336708370008
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 64: 2.9046181542532783
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 65: 3.036989450454712
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 66: 2.793301910161972
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 67: 2.159603968910549
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 68: 3.2708597018800933
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 69: 2.5299970507621765
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 70: 2.4691579341888428
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 71: 2.1077327330907187
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 72: 2.9324982053828688
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 73: 2.2991130315896235
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 74: 2.2017467816670737
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 75: 2.5311981561232586
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 76: 1.977375105023384
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 77: 2.374330520629883
[2024-09-20 18:36:40,504][flwr][INFO] - 		round 78: 2.262524425983429
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 79: 2.155195051973516
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 80: 3.1885580294059985
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 81: 2.030242405831814
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 82: 3.461551865866018
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 83: 2.3204273634319064
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 84: 2.8561471104621887
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 85: 0.6160692572593689
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 86: 2.7176427841186523
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 87: 1.628301478922367
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 88: 1.518665093771169
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 89: 2.236585653745211
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 90: 2.742870364870344
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 91: 4.680883889898248
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 92: 3.4440112022253184
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 93: 2.3050368920113278
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 94: 2.529911994934082
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 95: 2.2304923057556154
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 96: 2.2689040104548135
[2024-09-20 18:36:40,505][flwr][INFO] - 		round 97: 2.248712576352633
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 98: 1.437400460243225
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 99: 2.269892593909954
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 100: 1.8155214947003584
[2024-09-20 18:36:40,506][flwr][INFO] - 	History (loss, centralized):
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 0: 226.76452708244324
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 1: 238.03488445281982
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 2: 241.5014524459839
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 3: 289.6629376411438
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 4: 515.0731108188629
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 5: 221.73927521705627
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 6: 218.7551109790802
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 7: 274.564816236496
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 8: 302.46582770347595
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 9: 232.1724978685379
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 10: 239.41824352741241
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 11: 239.22387027740479
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 12: 304.5178427696228
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 13: 225.38797342777252
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 14: 313.34109258651733
[2024-09-20 18:36:40,506][flwr][INFO] - 		round 15: 221.74233961105347
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 16: 256.61250472068787
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 17: 248.64436793327332
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 18: 240.28642106056213
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 19: 249.1623079776764
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 20: 226.39255845546722
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 21: 231.67327654361725
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 22: 220.8802046775818
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 23: 230.86781120300293
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 24: 228.09581637382507
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 25: 234.344052195549
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 26: 218.2693328857422
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 27: 220.2818329334259
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 28: 221.04694092273712
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 29: 233.78054022789001
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 30: 221.74854588508606
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 31: 456.94386315345764
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 32: 598.0173711776733
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 33: 221.48068571090698
[2024-09-20 18:36:40,507][flwr][INFO] - 		round 34: 230.64493417739868
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 35: 222.84636735916138
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 36: 328.5816056728363
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 37: 220.15153753757477
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 38: 223.04044568538666
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 39: 288.0362346172333
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 40: 241.455011844635
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 41: 223.49810028076172
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 42: 326.53988671302795
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 43: 308.7781081199646
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 44: 242.62829911708832
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 45: 464.49644351005554
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 46: 220.93594527244568
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 47: 220.8076663017273
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 48: 450.6055371761322
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 49: 267.8551571369171
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 50: 222.25239646434784
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 51: 235.25658452510834
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 52: 244.26254832744598
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 53: 285.55648851394653
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 54: 247.25791156291962
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 55: 364.3339512348175
[2024-09-20 18:36:40,508][flwr][INFO] - 		round 56: 331.67673563957214
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 57: 264.59787690639496
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 58: 251.5600986480713
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 59: 219.04040503501892
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 60: 220.8660159111023
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 61: 270.81936025619507
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 62: 242.4165644645691
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 63: 348.6141564846039
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 64: 296.0308060646057
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 65: 290.46275782585144
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 66: 250.3443944454193
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 67: 229.02895879745483
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 68: 219.4711730480194
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 69: 226.52731728553772
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 70: 219.1491663455963
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 71: 280.5509045124054
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 72: 313.252653837204
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 73: 230.5376844406128
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 74: 219.6373189687729
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 75: 265.5568515062332
[2024-09-20 18:36:40,509][flwr][INFO] - 		round 76: 241.09146976470947
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 77: 217.35157907009125
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 78: 220.32001340389252
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 79: 216.60831797122955
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 80: 251.66179943084717
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 81: 225.61053836345673
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 82: 273.85055005550385
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 83: 226.50710272789001
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 84: 269.0091918706894
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 85: 260.9620455503464
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 86: 223.18651282787323
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 87: 236.18059265613556
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 88: 239.2525885105133
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 89: 247.62877345085144
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 90: 232.0524388551712
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 91: 309.10893511772156
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 92: 260.8995577096939
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 93: 240.86634182929993
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 94: 223.34192621707916
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 95: 220.11687457561493
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 96: 219.79442286491394
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 97: 223.28397452831268
[2024-09-20 18:36:40,510][flwr][INFO] - 		round 98: 221.97872304916382
[2024-09-20 18:36:40,511][flwr][INFO] - 		round 99: 223.54950189590454
[2024-09-20 18:36:40,511][flwr][INFO] - 		round 100: 217.55576169490814
[2024-09-20 18:36:40,511][flwr][INFO] - 	History (metrics, distributed, evaluate):
[2024-09-20 18:36:40,511][flwr][INFO] - 	{'accuracy': [(1, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (2, 0.2222222222222222),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (3, 0.075),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (4, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (5, 0.6470588235294118),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (6, 0.4925373134328358),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (7, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (8, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (9, 0.48148148148148145),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (10, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (11, 0.04861111111111111),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (12, 0.16129032258064518),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (13, 0.15217391304347827),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (14, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (15, 0.047619047619047616),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (16, 0.13043478260869565),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (17, 0.06306306306306306),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (18, 0.0),
[2024-09-20 18:36:40,511][flwr][INFO] - 	              (19, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (20, 0.0457516339869281),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (21, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (22, 0.024096385542168676),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (23, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (24, 0.03333333333333333),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (25, 0.07865168539325842),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (26, 0.043478260869565216),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (27, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (28, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (29, 0.45121951219512196),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (30, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (31, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (32, 0.43333333333333335),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (33, 0.7647058823529411),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (34, 0.05357142857142857),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (35, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (36, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (37, 0.3448275862068966),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (38, 0.043478260869565216),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (39, 0.0),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (40, 0.4),
[2024-09-20 18:36:40,512][flwr][INFO] - 	              (41, 0.05),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (42, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (43, 0.3333333333333333),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (44, 0.2222222222222222),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (45, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (46, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (47, 0.018518518518518517),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (48, 0.2191780821917808),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (49, 0.47692307692307695),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (50, 0.7777777777777778),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (51, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (52, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (53, 0.022727272727272728),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (54, 0.14285714285714285),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (55, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (56, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (57, 0.27),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (58, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (59, 0.15384615384615385),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (60, 0.6944444444444444),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (61, 0.0),
[2024-09-20 18:36:40,513][flwr][INFO] - 	              (62, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (63, 0.03508771929824561),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (64, 0.4285714285714286),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (65, 0.06666666666666667),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (66, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (67, 0.15217391304347827),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (68, 0.7586206896551724),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (69, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (70, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (71, 0.3611111111111111),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (72, 0.33962264150943394),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (73, 0.7121212121212122),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (74, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (75, 0.22448979591836735),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (76, 0.375),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (77, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (78, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (79, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (80, 0.0),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (81, 0.14583333333333334),
[2024-09-20 18:36:40,514][flwr][INFO] - 	              (82, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (83, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (84, 0.08333333333333333),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (85, 1.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (86, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (87, 0.78125),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (88, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (89, 0.4230769230769231),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (90, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (91, 0.42201834862385323),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (92, 0.07692307692307693),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (93, 0.1941747572815534),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (94, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (95, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (96, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (97, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (98, 0.8571428571428571),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (99, 0.0),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (100, 0.7307692307692307)]}
[2024-09-20 18:36:40,515][flwr][INFO] - 	History (metrics, centralized):
[2024-09-20 18:36:40,515][flwr][INFO] - 	{'accuracy': [(0, 0.11370944168371822),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (1, 0.07132417421806489),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (2, 0.09090909090909091),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (3, 0.09090909090909091),
[2024-09-20 18:36:40,515][flwr][INFO] - 	              (4, 0.1824028061970184),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (5, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (6, 0.16924875767319497),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (7, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (8, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (9, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (10, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (11, 0.16924875767319497),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (12, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (13, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (14, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (15, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (16, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (17, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (18, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (19, 0.07132417421806489),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (20, 0.1824028061970184),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (21, 0.1373867290266004),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (22, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (23, 0.16924875767319497),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (24, 0.1824028061970184),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (25, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (26, 0.19467991815258695),
[2024-09-20 18:36:40,516][flwr][INFO] - 	              (27, 0.24934229757380882),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (28, 0.1824028061970184),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (29, 0.1373867290266004),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (30, 0.1373867290266004),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (31, 0.1824028061970184),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (32, 0.19467991815258695),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (33, 0.19467991815258695),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (34, 0.16924875767319497),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (35, 0.16924875767319497),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (36, 0.19467991815258695),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (37, 0.07132417421806489),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (38, 0.19467991815258695),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (39, 0.1373867290266004),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (40, 0.1824028061970184),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (41, 0.16924875767319497),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (42, 0.07132417421806489),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (43, 0.1581408944752996),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (44, 0.1373867290266004),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (45, 0.16924875767319497),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (46, 0.19467991815258695),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (47, 0.19467991815258695),
[2024-09-20 18:36:40,517][flwr][INFO] - 	              (48, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (49, 0.29026600409237063),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (50, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (51, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (52, 0.16924875767319497),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (53, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (54, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (55, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (56, 0.1373867290266004),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (57, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (58, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (59, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (60, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (61, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (62, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (63, 0.1824028061970184),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (64, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (65, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (66, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (67, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (68, 0.19467991815258695),
[2024-09-20 18:36:40,518][flwr][INFO] - 	              (69, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (70, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (71, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (72, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (73, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (74, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (75, 0.1824028061970184),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (76, 0.16924875767319497),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (77, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (78, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (79, 0.19467991815258695),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (80, 0.1824028061970184),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (81, 0.1824028061970184),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (82, 0.16924875767319497),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (83, 0.16924875767319497),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (84, 0.16924875767319497),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (85, 0.16924875767319497),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (86, 0.16924875767319497),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (87, 0.1824028061970184),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (88, 0.1824028061970184),
[2024-09-20 18:36:40,519][flwr][INFO] - 	              (89, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (90, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (91, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (92, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (93, 0.07132417421806489),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (94, 0.19467991815258695),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (95, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (96, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (97, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (98, 0.1824028061970184),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (99, 0.16924875767319497),
[2024-09-20 18:36:40,520][flwr][INFO] - 	              (100, 0.1824028061970184)]}
[2024-09-20 18:36:40,520][flwr][INFO] - 
